In [1]:
# ============================================
# STEP 1) TILING + NEGATIVE SAMPLING + EVENT-ID FILENAMES
# ============================================

!pip -q install segmentation_models_pytorch

from google.colab import drive
drive.mount('/content/drive')

import os, zipfile, random
import numpy as np
import rasterio
from rasterio.windows import Window
from tqdm import tqdm

ZIP_ROOT  = "/content/drive/MyDrive/burned_area"
BASE_ROOT = "/content/burned_area"
OUT       = "/content/burned_tiles"

os.makedirs(BASE_ROOT, exist_ok=True)
os.makedirs(f"{OUT}/x", exist_ok=True)
os.makedirs(f"{OUT}/y", exist_ok=True)

# --- unzip all parts ---
for fname in sorted(os.listdir(ZIP_ROOT)):
    if fname.endswith(".zip"):
        part_name = fname.replace(".zip", "")
        out_dir = os.path.join(BASE_ROOT, part_name)
        os.makedirs(out_dir, exist_ok=True)
        print(f"Açılıyor: {fname}")
        with zipfile.ZipFile(os.path.join(ZIP_ROOT, fname), "r") as z:
            z.extractall(out_dir)

TILE = 256

# NEGATIVE SAMPLING SETTINGS
KEEP_NEG_RATIO = 0.15   # 0.10-0.30 arası deneyebilirsin
NEG_PER_POS_CAP = 2.0   # negatifleri pozitiflere göre üstten kıs (örn 2.0 => en fazla 2x negatif)

rng = np.random.default_rng(42)

pos_count = 0
neg_count = 0

# --- iterate PART1..PART5 ---
for part in sorted(os.listdir(BASE_ROOT)):
    part_dir = os.path.join(BASE_ROOT, part)
    if not os.path.isdir(part_dir):
        continue

    # inside: real dataset folder
    subdirs = [d for d in os.listdir(part_dir) if os.path.isdir(os.path.join(part_dir, d))]
    if not subdirs:
        continue
    ROOT = os.path.join(part_dir, subdirs[0])
    print(f"\nİşleniyor: {ROOT}")

    # events
    for event in tqdm(sorted(os.listdir(ROOT))):
        evdir = os.path.join(ROOT, event)
        if not os.path.isdir(evdir):
            continue

        masks = [f for f in os.listdir(evdir) if "mask" in f.lower()]
        s2s = [
            f for f in os.listdir(evdir)
            if f.lower().startswith("sentinel2_")
            and f.lower().endswith(".tiff")
            and "cloud" not in f.lower()
        ]
        if not masks or not s2s:
            continue

        # mask read (assume same H,W as images)
        with rasterio.open(os.path.join(evdir, masks[0])) as msk_src:
            mask_arr = msk_src.read(1)

        for s2 in sorted(s2s):
            with rasterio.open(os.path.join(evdir, s2)) as src:
                if src.count < 3:
                    continue

                H, W = src.height, src.width

                for top in range(0, H - TILE + 1, TILE):
                    for left in range(0, W - TILE + 1, TILE):
                        w = Window(left, top, TILE, TILE)

                        img_patch = src.read([1, 2, 3], window=w).astype(np.float32)  # (3,H,W)
                        mask_patch = mask_arr[top:top+TILE, left:left+TILE]

                        is_pos = (mask_patch > 0).any()

                        # --- balance logic ---
                        if not is_pos:
                            # random downsample negatives
                            if rng.random() > KEEP_NEG_RATIO:
                                continue
                            # cap negatives vs positives
                            if pos_count > 0 and neg_count >= int(NEG_PER_POS_CAP * pos_count):
                                continue

                        # event id & spatial id in filename
                        base_id = f"{part}__{event}__{os.path.splitext(s2)[0]}__t{top}_l{left}"
                        np.save(f"{OUT}/x/{base_id}.npy", img_patch)
                        np.save(f"{OUT}/y/{base_id}.npy", mask_patch)

                        if is_pos:
                            pos_count += 1
                        else:
                            neg_count += 1

print(f"\nSaved patches => pos={pos_count}, neg={neg_count}, total={pos_count+neg_count}")
print("OUT:", OUT)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.8/154.8 kB 13.9 MB/s eta 0:00:00
Mounted at /content/drive
Açılıyor: Satellite_burned_area_dataset_part1.zip
Açılıyor: Satellite_burned_area_dataset_part2.zip
Açılıyor: Satellite_burned_area_dataset_part3.zip
Açılıyor: Satellite_burned_area_dataset_part4.zip
Açılıyor: Satellite_burned_area_dataset_part5.zip

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part1/Satellite_burned_area_dataset_part1

  0%|          | 0/17 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/rasterio/__init__.py:367: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, thread_safe=thread_safe, **kwargs)
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
  6%|▌         | 1/17 [00:00<00:13,  1.17it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 12%|█▏        | 2/17 [00:01<00:11,  1.29it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 18%|█▊        | 3/17 [00:02<00:10,  1.31it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 24%|██▎       | 4/17 [00:03<00:10,  1.29it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 29%|██▉       | 5/17 [00:03<00:09,  1.30it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 35%|███▌      | 6/17 [00:04<00:08,  1.33it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 41%|████      | 7/17 [00:05<00:07,  1.30it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 47%|████▋     | 8/17 [00:06<00:06,  1.32it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 53%|█████▎    | 9/17 [00:06<00:05,  1.44it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 59%|█████▉    | 10/17 [00:07<00:04,  1.57it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 65%|██████▍   | 11/17 [00:07<00:03,  1.79it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-29.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 71%|███████   | 12/17 [00:10<00:05,  1.19s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-29.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 76%|███████▋  | 13/17 [00:13<00:06,  1.70s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 82%|████████▏ | 14/17 [00:13<00:03,  1.28s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 88%|████████▊ | 15/17 [00:15<00:02,  1.44s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 94%|█████████▍| 16/17 [00:15<00:01,  1.11s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-26.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-16.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 17/17 [00:15<00:00,  1.09it/s]

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part2/Satellite_burned_area_dataset_part2

  0%|          | 0/11 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
  9%|▉         | 1/11 [00:00<00:06,  1.66it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 18%|█▊        | 2/11 [00:02<00:11,  1.23s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 27%|██▋       | 3/11 [00:03<00:08,  1.11s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 36%|███▋      | 4/11 [00:03<00:05,  1.39it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 45%|████▌     | 5/11 [00:03<00:03,  1.93it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 55%|█████▍    | 6/11 [00:03<00:01,  2.53it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 64%|██████▎   | 7/11 [00:03<00:01,  3.18it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-12.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 73%|███████▎  | 8/11 [00:15<00:11,  3.93s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-04-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-05-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 91%|█████████ | 10/11 [00:16<00:02,  2.22s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-16.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-08-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 11/11 [00:17<00:00,  1.55s/it]

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part3/Satellite_burned_area_dataset_part3

  0%|          | 0/29 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
  3%|▎         | 1/29 [00:00<00:14,  1.91it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-11.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 10%|█         | 3/29 [00:00<00:05,  5.01it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-11.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 14%|█▍        | 4/29 [00:00<00:04,  5.56it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-11.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 17%|█▋        | 5/29 [00:01<00:05,  4.14it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-26.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-26.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 24%|██▍       | 7/29 [00:01<00:03,  6.14it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-13.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 28%|██▊       | 8/29 [00:02<00:06,  3.29it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 31%|███       | 9/29 [00:05<00:24,  1.24s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-29.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 34%|███▍      | 10/29 [00:07<00:24,  1.30s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 38%|███▊      | 11/29 [00:07<00:19,  1.06s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 41%|████▏     | 12/29 [00:07<00:13,  1.25it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 52%|█████▏    | 15/29 [00:08<00:05,  2.42it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 55%|█████▌    | 16/29 [00:08<00:04,  2.61it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-23.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 59%|█████▊    | 17/29 [00:08<00:04,  2.75it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-23.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 62%|██████▏   | 18/29 [00:09<00:03,  2.93it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-08.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 66%|██████▌   | 19/29 [00:10<00:05,  1.90it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part4/Satellite_burned_area_dataset_part4

  0%|          | 0/7 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 14%|█▍        | 1/7 [00:03<00:19,  3.22s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 29%|██▊       | 2/7 [00:04<00:11,  2.24s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-10.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 43%|████▎     | 3/7 [00:06<00:08,  2.12s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 57%|█████▋    | 4/7 [00:09<00:07,  2.38s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 71%|███████▏  | 5/7 [00:12<00:05,  2.51s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 86%|████████▌ | 6/7 [00:14<00:02,  2.45s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 7/7 [00:16<00:00,  2.37s/it]

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part5/Satellite_burned_area_dataset_part5

  0%|          | 0/9 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 11%|█         | 1/9 [00:00<00:05,  1.46it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 22%|██▏       | 2/9 [00:01<00:06,  1.16it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-23.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 33%|███▎      | 3/9 [00:01<00:03,  1.90it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 44%|████▍     | 4/9 [00:02<00:02,  2.30it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 56%|█████▌    | 5/9 [00:02<00:01,  2.60it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 67%|██████▋   | 6/9 [00:02<00:01,  2.69it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 78%|███████▊  | 7/9 [00:02<00:00,  3.08it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 89%|████████▉ | 8/9 [00:03<00:00,  1.96it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2019-05-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2019-06-30.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 9/9 [00:07<00:00,  1.25it/s]

Saved patches => pos=2330, neg=544, total=2874
OUT: /content/burned_tiles

In [2]:
import os
import random
import numpy as np

TILES_DIR = "/content/burned_tiles"
x_dir = os.path.join(TILES_DIR, "x")
y_dir = os.path.join(TILES_DIR, "y")

ids = sorted([os.path.splitext(f)[0] for f in os.listdir(x_dir) if f.endswith(".npy")])

random.seed(42)
random.shuffle(ids)

n = len(ids)
train_ids = ids[:int(0.7*n)]
val_ids   = ids[int(0.7*n):int(0.85*n)]
test_ids  = ids[int(0.85*n):]

print("Train:", len(train_ids), "Val:", len(val_ids), "Test:", len(test_ids))

Train: 2011 Val: 431 Test: 432

In [3]:
import numpy as np, os
from tqdm import tqdm

def stats(ids, tiles_dir):
    pos = 0
    total = 0
    frac_list = []
    for id_ in tqdm(ids):
        y = np.load(os.path.join(tiles_dir, "y", f"{id_}.npy"))
        total += 1
        frac = (y > 0).mean()
        frac_list.append(frac)
        if frac > 0:
            pos += 1
    return {
        "total": total,
        "pos_patches": pos,
        "neg_patches": total - pos,
        "avg_burn_frac": float(np.mean(frac_list)),
        "median_burn_frac": float(np.median(frac_list)),
    }

In [4]:
# Split + stats hücrelerini (STEP2 + STEP3) çalıştır

print("TRAIN", stats(train_ids, OUT))
print("VAL  ", stats(val_ids, OUT))
print("TEST ", stats(test_ids, OUT))

100%|██████████| 2011/2011 [00:00<00:00, 3867.39it/s]

TRAIN {'total': 2011, 'pos_patches': 1628, 'neg_patches': 383, 'avg_burn_frac': 0.423407624338113, 'median_burn_frac': 0.266998291015625}

100%|██████████| 431/431 [00:00<00:00, 4009.91it/s]

VAL   {'total': 431, 'pos_patches': 358, 'neg_patches': 73, 'avg_burn_frac': 0.47491196634597954, 'median_burn_frac': 0.43804931640625}

100%|██████████| 432/432 [00:00<00:00, 3767.34it/s]

TEST  {'total': 432, 'pos_patches': 344, 'neg_patches': 88, 'avg_burn_frac': 0.42166434393988717, 'median_burn_frac': 0.22507476806640625}

In [5]:
import torch
from torch.utils.data import Dataset
import numpy as np
import os

class BurnedPatchDataset(Dataset):
    def __init__(self, tiles_dir, ids, normalize=True):
        self.tiles_dir = tiles_dir
        self.ids = ids
        self.normalize = normalize

    def __len__(self):
        return len(self.ids)

    def __getitem__(self, idx):
        id_ = self.ids[idx]

        x = np.load(os.path.join(self.tiles_dir, "x", f"{id_}.npy"))
        y = np.load(os.path.join(self.tiles_dir, "y", f"{id_}.npy"))

        # (H,W,C) gelirse düzelt
        if x.ndim == 3 and x.shape[-1] == 3:
            x = np.transpose(x, (2, 0, 1))

        x = x.astype(np.float32)
        if self.normalize:
            x = x / 255.0

        y = (y > 0).astype(np.int64)

        return torch.from_numpy(x), torch.from_numpy(y)

## **Dataset and DataLoader Definition**

A custom PyTorch `Dataset` class is implemented to load image–mask pairs from disk.
Each sample consists of:
- A normalized RGB image tensor of shape (3, 256, 256)
- A binary segmentation mask of shape (256, 256)

PyTorch `DataLoader`s are used to enable efficient mini-batch loading and shuffling during training.

In [6]:
from torch.utils.data import DataLoader
TILES_DIR = "/content/burned_tiles"
train_ds = BurnedPatchDataset(TILES_DIR, train_ids)
val_ds   = BurnedPatchDataset(TILES_DIR, val_ids)
test_ds  = BurnedPatchDataset(TILES_DIR, test_ids)

train_loader = DataLoader(train_ds, batch_size=8, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=8, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=8, shuffle=False)

## **Model Architecture**

The segmentation model is based on the U-Net architecture with a ResNet18 encoder pretrained on ImageNet.

**Architecture details:**
- Encoder: ResNet18 (pretrained)
- Decoder: U-Net decoder
- Input channels: 3 (RGB)
- Output: 1-channel binary segmentation mask

U-Net is well-suited for this task due to its ability to preserve spatial details through skip connections.

In [7]:
import segmentation_models_pytorch as smp
import torch

model = smp.Unet(
    encoder_name="resnet18",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/46.8M [00:00<?, ?B/s]

# **Training U-NET**

In [ ]:
# ============================================================
# CONTROLLED ABLATION PIPELINE + SAVE EVERYTHING (Drive)
# FIXED: AMP/scaler bug + robust saving paths
# ============================================================
import os, copy, random, math, json
import numpy as np
import torch
import segmentation_models_pytorch as smp
from tqdm import tqdm



# === CHANGE THIS: where to save runs in your Drive ===
RUNS_DIR = "/content/drive/MyDrive/burned_area_outputs_unet"   # <- istediğin klasör
os.makedirs(RUNS_DIR, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

def build_model(encoder_name="resnet18", encoder_weights="imagenet"):
    return smp.Unet(
        encoder_name=encoder_name,
        encoder_weights=encoder_weights,
        in_channels=3,
        classes=1,
    )

def make_loss(loss_cfg):
    name = loss_cfg["name"]

    if name == "bce":
        bce = torch.nn.BCEWithLogitsLoss()
        return lambda logits, y: bce(logits, y), "BCE"

    if name == "bce_dice":
        bce = torch.nn.BCEWithLogitsLoss()
        dice = smp.losses.DiceLoss(mode="binary")
        w_bce  = loss_cfg.get("w_bce", 1.0)
        w_dice = loss_cfg.get("w_dice", 1.0)
        return (lambda logits, y: w_bce*bce(logits, y) + w_dice*dice(logits, y),
                f"BCE+Dice({w_bce},{w_dice})")

    if name == "focal_dice":
        alpha = loss_cfg.get("alpha", 0.8)
        gamma = loss_cfg.get("gamma", 2.0)
        focal = smp.losses.FocalLoss(mode="binary", alpha=alpha, gamma=gamma)
        dice  = smp.losses.DiceLoss(mode="binary")
        w_focal = loss_cfg.get("w_focal", 1.0)
        w_dice  = loss_cfg.get("w_dice", 1.0)
        return (lambda logits, y: w_focal*focal(logits, y) + w_dice*dice(logits, y),
                f"Focal(a={alpha},g={gamma})+Dice")

    raise ValueError(f"Unknown loss: {name}")

@torch.no_grad()
def dice_iou_from_logits(logits, y, thr=0.5, eps=1e-7):
    probs = torch.sigmoid(logits)
    pred = (probs > thr).float()
    inter = (pred * y).sum(dim=(1,2,3))

    union_d = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3))
    dice = ((2*inter + eps) / (union_d + eps)).mean().item()

    union_i = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3)) - inter
    iou = ((inter + eps) / (union_i + eps)).mean().item()
    return dice, iou

def run_epoch(model, loader, loss_fn, optimizer=None, use_amp=False, scaler=None, grad_clip=None, desc=""):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    tot_loss = 0.0
    tot_dice = 0.0
    tot_iou  = 0.0
    n = 0

    # eval'de no_grad kullan
    context = torch.enable_grad() if is_train else torch.no_grad()
    with context:
        for x, y in tqdm(loader, desc=desc):
            x = x.to(device, non_blocking=True)
            y = y.unsqueeze(1).float().to(device, non_blocking=True)

            if is_train:
                optimizer.zero_grad(set_to_none=True)

            if use_amp:
                with torch.cuda.amp.autocast(True):
                    logits = model(x)
                    loss = loss_fn(logits, y)
            else:
                logits = model(x)
                loss = loss_fn(logits, y)

            if is_train:
                if use_amp:
                    scaler.scale(loss).backward()
                    if grad_clip is not None:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    if grad_clip is not None:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
                    optimizer.step()

            # metric (logits'ten)
            dice, iou = dice_iou_from_logits(logits, y)

            tot_loss += float(loss.item())
            tot_dice += dice
            tot_iou  += iou
            n += 1

    if n == 0:
        return math.nan, math.nan, math.nan
    return tot_loss/n, tot_dice/n, tot_iou/n

def save_csv(path, rows, header):
    with open(path, "w") as f:
        f.write(",".join(header) + "\n")
        for r in rows:
            f.write(",".join(str(r.get(h,"")) for h in header) + "\n")

def train_one(cfg):
    set_seed(cfg.get("seed", 42))

    # ---- run folder ----
    run_dir = os.path.join(RUNS_DIR, cfg["name"])
    os.makedirs(run_dir, exist_ok=True)

    # save config
    with open(os.path.join(run_dir, "config.json"), "w") as f:
        json.dump(cfg, f, indent=2)

    best_path = os.path.join(run_dir, "best.pth")
    last_path = os.path.join(run_dir, "last.pth")
    hist_path = os.path.join(run_dir, "history.csv")

    model = build_model(cfg["encoder"], cfg["weights"]).to(device)
    loss_fn, loss_pretty = make_loss(cfg["loss"])

    # optimizer
    opt = cfg["optimizer"]["name"]
    lr  = cfg["optimizer"]["lr"]
    wd  = cfg["optimizer"].get("weight_decay", 0.0)
    if opt == "adam":
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
    elif opt == "adamw":
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
    else:
        raise ValueError(opt)

    # scheduler (optional)
    scheduler = None
    if cfg.get("scheduler", None):
        sc = cfg["scheduler"]
        if sc["name"] == "plateau":
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                optimizer, mode=sc.get("mode","min"),
                factor=sc.get("factor",0.5),
                patience=sc.get("patience",2),
                min_lr=sc.get("min_lr",1e-6),
            )
        elif sc["name"] == "cosine":
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer, T_max=sc.get("T_max", cfg["epochs"])
            )
        else:
            raise ValueError(sc["name"])

    # AMP
    use_amp = bool(cfg.get("amp", True)) and torch.cuda.is_available()
    scaler = torch.cuda.amp.GradScaler(enabled=use_amp) if use_amp else None

    # freeze
    freeze_epochs = int(cfg.get("freeze_epochs", 0))
    if freeze_epochs > 0:
        for p in model.encoder.parameters():
            p.requires_grad = False

    # early stopping
    es = cfg.get("early_stopping", {"enabled": False})
    es_enabled = bool(es.get("enabled", False))
    monitor = es.get("monitor","val_dice")
    mode    = es.get("mode","max")
    patience = int(es.get("patience", 6))

    best = -1e9 if mode=="max" else 1e9
    best_epoch = -1
    bad = 0

    grad_clip = cfg.get("grad_clip", None)
    plateau_on = cfg.get("plateau_on","val_loss")

    history = []

    for epoch in range(1, cfg["epochs"]+1):
        # unfreeze
        if freeze_epochs > 0 and epoch == freeze_epochs + 1:
            for p in model.encoder.parameters():
                p.requires_grad = True
            if cfg.get("reset_opt_on_unfreeze", True):
                new_lr = cfg.get("lr_unfreeze", lr)
                if opt == "adam":
                    optimizer = torch.optim.Adam(model.parameters(), lr=new_lr, weight_decay=wd)
                else:
                    optimizer = torch.optim.AdamW(model.parameters(), lr=new_lr, weight_decay=wd)

                # rebuild scheduler if exists
                if cfg.get("scheduler", None):
                    sc = cfg["scheduler"]
                    if sc["name"] == "plateau":
                        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                            optimizer, mode=sc.get("mode","min"),
                            factor=sc.get("factor",0.5),
                            patience=sc.get("patience",2),
                            min_lr=sc.get("min_lr",1e-6),
                        )
                    elif sc["name"] == "cosine":
                        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                            optimizer, T_max=sc.get("T_max", cfg["epochs"])
                        )

                scaler = torch.cuda.amp.GradScaler(enabled=use_amp) if use_amp else None

        tl, td, ti = run_epoch(
            model, train_loader, loss_fn,
            optimizer=optimizer,
            use_amp=use_amp, scaler=scaler,
            grad_clip=grad_clip,
            desc=f"{cfg['name']} | {epoch}/{cfg['epochs']} TRAIN"
        )

        vl, vd, vi = run_epoch(
            model, val_loader, loss_fn,
            optimizer=None,
            use_amp=use_amp, scaler=scaler,
            grad_clip=None,
            desc=f"{cfg['name']} | {epoch}/{cfg['epochs']} VAL"
        )

        # scheduler
        if scheduler is not None:
            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
                metric = vl if plateau_on=="val_loss" else (1.0 - vd)
                scheduler.step(metric)
            else:
                scheduler.step()

        lr_now = optimizer.param_groups[0]["lr"]
        row = {
            "epoch": epoch,
            "lr": lr_now,
            "train_loss": tl,
            "train_dice": td,
            "train_iou": ti,
            "val_loss": vl,
            "val_dice": vd,
            "val_iou": vi,
        }
        history.append(row)

        print(f"[{cfg['name']}] ep{epoch:02d} | TL {tl:.4f} | VL {vl:.4f} | VD {vd:.4f} | VI {vi:.4f} | LR {lr_now:.2e}")

        # always save LAST
        torch.save(
            {"epoch": epoch, "model": model.state_dict(), "cfg": cfg, "history": history},
            last_path
        )

        # best by monitor
        current = vd if monitor=="val_dice" else vl
        improved = (current > best) if mode=="max" else (current < best)

        if improved:
            best = current
            best_epoch = epoch
            bad = 0
            torch.save(
                {"epoch": epoch, "model": model.state_dict(), "cfg": cfg, "best": best, "history": history},
                best_path
            )
            print(f"  ✓ best saved ({monitor}={best:.6f}) -> {best_path}")
        else:
            if es_enabled:
                bad += 1
                if bad >= patience:
                    print(f"⛔ early stop (best ep={best_epoch}, best {monitor}={best:.6f})")
                    break

    # save history.csv
    header = ["epoch","lr","train_loss","train_dice","train_iou","val_loss","val_dice","val_iou"]
    save_csv(hist_path, history, header)

    # TEST with BEST (fallback to LAST if best missing)
    ckpt_path = best_path if os.path.exists(best_path) else last_path
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt["model"])
    model.eval()

    test_loss, test_dice, test_iou = run_epoch(
        model, test_loader, loss_fn,
        optimizer=None,
        use_amp=use_amp, scaler=scaler,
        desc=f"{cfg['name']} | TEST ({'best' if ckpt_path==best_path else 'last'})"
    )

    summary = {
        "name": cfg["name"],
        "run_dir": run_dir,
        "best_path": best_path,
        "last_path": last_path,
        "hist_path": hist_path,
        "best_epoch": ckpt.get("epoch", None),
        "best_metric": ckpt.get("best", None),
        "test_loss": test_loss,
        "test_dice": test_dice,
        "test_iou": test_iou,
    }
    return summary

# ============================================================
# CONDITIONS
# ============================================================
BASE = {
    "name": "C00_BASE",
    "seed": 42,
    "encoder": "resnet18",
    "weights": "imagenet",
    "epochs": 30,
    "loss": {"name": "bce_dice", "w_bce": 1.0, "w_dice": 1.0},
    "optimizer": {"name": "adamw", "lr": 1e-4, "weight_decay": 1e-4},
    "scheduler": None,
    "plateau_on": "val_loss",
    "amp": False,          # True istersen otomatik scaler/amp çalışır
    "grad_clip": None,
    "freeze_epochs": 0,
    "reset_opt_on_unfreeze": True,
    "lr_unfreeze": 1e-4,
    "early_stopping": {"enabled": False, "monitor":"val_dice", "mode":"max", "patience":6},
}

ABLATIONS = [
    ("loss", {"name": "bce"}, "loss=BCE"),
    ("loss", {"name": "focal_dice", "alpha":0.8, "gamma":2.0}, "loss=Focal+Dice"),
    ("scheduler", {"name":"plateau","mode":"min","factor":0.5,"patience":2,"min_lr":1e-6}, "sched=plateau"),
    ("amp", True, "amp=on"),
    ("grad_clip", 1.0, "clip=1.0"),
    ("freeze_epochs", 2, "freeze=2ep"),
    ("early_stopping", {"enabled": True, "monitor":"val_dice", "mode":"max", "patience":6}, "ES=on"),
    ("optimizer.lr", 5e-5, "lr=5e-5"),
    ("optimizer.lr", 2e-4, "lr=2e-4"),
]

def apply_change(cfg, path, value):
    keys = path.split(".")
    ref = cfg
    for k in keys[:-1]:
        ref = ref[k]
    ref[keys[-1]] = value

def build_conditions(base_cfg, ablations):
    conds = [copy.deepcopy(base_cfg)]
    for i, (path, val, tag) in enumerate(ablations, start=1):
        c = copy.deepcopy(base_cfg)
        c["name"] = f"C{i:02d}_{tag}"
        apply_change(c, path, val)
        conds.append(c)
    return conds

CONDITIONS = build_conditions(BASE, ABLATIONS)

# ============================================================
# RUN ALL
# ============================================================
summaries = []
for cfg in CONDITIONS:
    summaries.append(train_one(cfg))

print("\n\nSaved runs under:", RUNS_DIR)
for s in summaries:
    print(s["name"], "->", s["run_dir"])
    print("  best:", s["best_path"])
    print("  last:", s["last_path"])
    print("  hist:", s["hist_path"])
    print("  best_epoch:", s["best_epoch"], "| test_dice:", f"{s['test_dice']:.4f}", "| test_iou:", f"{s['test_iou']:.4f}")

C00_BASE | 1/30 TRAIN: 100%|██████████| 252/252 [00:08<00:00, 28.34it/s]
C00_BASE | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.77it/s]

[C00_BASE] ep01 | TL 1.0161 | VL 0.8118 | VD 0.4622 | VI 0.4125 | LR 1.00e-04
  ✓ best saved (val_dice=0.462162) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.44it/s]
C00_BASE | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.40it/s]

[C00_BASE] ep02 | TL 0.8206 | VL 0.7362 | VD 0.5006 | VI 0.4490 | LR 1.00e-04
  ✓ best saved (val_dice=0.500566) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.20it/s]
C00_BASE | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.22it/s]

[C00_BASE] ep03 | TL 0.7102 | VL 0.7448 | VD 0.4512 | VI 0.4051 | LR 1.00e-04

C00_BASE | 4/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.41it/s]
C00_BASE | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.82it/s]

[C00_BASE] ep04 | TL 0.5684 | VL 0.8340 | VD 0.4937 | VI 0.4429 | LR 1.00e-04

C00_BASE | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.59it/s]
C00_BASE | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.79it/s]

[C00_BASE] ep05 | TL 0.5400 | VL 0.8042 | VD 0.5401 | VI 0.4851 | LR 1.00e-04
  ✓ best saved (val_dice=0.540093) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 6/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.40it/s]
C00_BASE | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.67it/s]

[C00_BASE] ep06 | TL 0.4127 | VL 0.6064 | VD 0.6222 | VI 0.5735 | LR 1.00e-04
  ✓ best saved (val_dice=0.622159) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.44it/s]
C00_BASE | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.64it/s]

[C00_BASE] ep07 | TL 0.4139 | VL 0.8083 | VD 0.5658 | VI 0.5193 | LR 1.00e-04

C00_BASE | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.43it/s]
C00_BASE | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.04it/s]

[C00_BASE] ep08 | TL 0.3586 | VL 0.6412 | VD 0.6234 | VI 0.5782 | LR 1.00e-04
  ✓ best saved (val_dice=0.623389) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.29it/s]
C00_BASE | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.53it/s]

[C00_BASE] ep09 | TL 0.3212 | VL 0.6536 | VD 0.6417 | VI 0.5906 | LR 1.00e-04
  ✓ best saved (val_dice=0.641675) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 10/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.11it/s]
C00_BASE | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.81it/s]

[C00_BASE] ep10 | TL 0.2668 | VL 0.5602 | VD 0.6338 | VI 0.5878 | LR 1.00e-04

C00_BASE | 11/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.82it/s]
C00_BASE | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.68it/s]

[C00_BASE] ep11 | TL 0.3016 | VL 0.6013 | VD 0.6505 | VI 0.6072 | LR 1.00e-04
  ✓ best saved (val_dice=0.650516) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.89it/s]
C00_BASE | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.66it/s]

[C00_BASE] ep12 | TL 0.2367 | VL 0.6389 | VD 0.6465 | VI 0.6021 | LR 1.00e-04

C00_BASE | 13/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.91it/s]
C00_BASE | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.07it/s]

[C00_BASE] ep13 | TL 0.2250 | VL 0.5435 | VD 0.6450 | VI 0.5973 | LR 1.00e-04

C00_BASE | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.41it/s]
C00_BASE | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.26it/s]

[C00_BASE] ep14 | TL 0.2508 | VL 0.5719 | VD 0.6440 | VI 0.5995 | LR 1.00e-04

C00_BASE | 15/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.65it/s]
C00_BASE | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.58it/s]

[C00_BASE] ep15 | TL 0.2347 | VL 0.6213 | VD 0.6000 | VI 0.5406 | LR 1.00e-04

C00_BASE | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.91it/s]
C00_BASE | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.52it/s]

[C00_BASE] ep16 | TL 0.2248 | VL 0.6117 | VD 0.6484 | VI 0.6029 | LR 1.00e-04

C00_BASE | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.50it/s]
C00_BASE | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.79it/s]

[C00_BASE] ep17 | TL 0.1685 | VL 0.5486 | VD 0.6493 | VI 0.6003 | LR 1.00e-04

C00_BASE | 18/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.37it/s]
C00_BASE | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.48it/s]

[C00_BASE] ep18 | TL 0.1931 | VL 0.6306 | VD 0.6468 | VI 0.5989 | LR 1.00e-04

C00_BASE | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.16it/s]
C00_BASE | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.37it/s]

[C00_BASE] ep19 | TL 0.1435 | VL 0.9155 | VD 0.5779 | VI 0.5156 | LR 1.00e-04

C00_BASE | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.10it/s]
C00_BASE | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.11it/s]

[C00_BASE] ep20 | TL 0.1279 | VL 0.5406 | VD 0.6829 | VI 0.6402 | LR 1.00e-04
  ✓ best saved (val_dice=0.682901) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 21/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.95it/s]
C00_BASE | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.78it/s]

[C00_BASE] ep21 | TL 0.1922 | VL 0.7562 | VD 0.6060 | VI 0.5529 | LR 1.00e-04

C00_BASE | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.61it/s]
C00_BASE | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.78it/s]

[C00_BASE] ep22 | TL 0.1307 | VL 0.5372 | VD 0.6763 | VI 0.6341 | LR 1.00e-04

C00_BASE | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.22it/s]
C00_BASE | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.74it/s]

[C00_BASE] ep23 | TL 0.1859 | VL 0.7227 | VD 0.5843 | VI 0.5338 | LR 1.00e-04

C00_BASE | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.31it/s]
C00_BASE | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.78it/s]

[C00_BASE] ep24 | TL 0.1621 | VL 0.6088 | VD 0.6427 | VI 0.5989 | LR 1.00e-04

C00_BASE | 25/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.07it/s]
C00_BASE | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.24it/s]

[C00_BASE] ep25 | TL 0.1665 | VL 0.5623 | VD 0.6659 | VI 0.6240 | LR 1.00e-04

C00_BASE | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.51it/s]
C00_BASE | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.22it/s]

[C00_BASE] ep26 | TL 0.1220 | VL 0.6105 | VD 0.6514 | VI 0.6110 | LR 1.00e-04

C00_BASE | 27/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.98it/s]
C00_BASE | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.09it/s]

[C00_BASE] ep27 | TL 0.1030 | VL 0.6385 | VD 0.6830 | VI 0.6445 | LR 1.00e-04
  ✓ best saved (val_dice=0.682992) -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth

C00_BASE | 28/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.92it/s]
C00_BASE | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.19it/s]

[C00_BASE] ep28 | TL 0.1079 | VL 0.5746 | VD 0.6751 | VI 0.6346 | LR 1.00e-04

C00_BASE | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.22it/s]
C00_BASE | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.52it/s]

[C00_BASE] ep29 | TL 0.0869 | VL 0.6187 | VD 0.6786 | VI 0.6365 | LR 1.00e-04

C00_BASE | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.72it/s]
C00_BASE | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.71it/s]

[C00_BASE] ep30 | TL 0.0806 | VL 0.5606 | VD 0.6772 | VI 0.6378 | LR 1.00e-04

C00_BASE | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 69.25it/s]
C01_loss=BCE | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.24it/s]
C01_loss=BCE | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.68it/s]

[C01_loss=BCE] ep01 | TL 0.5869 | VL 0.5167 | VD 0.4362 | VI 0.3822 | LR 1.00e-04
  ✓ best saved (val_dice=0.436225) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.11it/s]
C01_loss=BCE | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.74it/s]

[C01_loss=BCE] ep02 | TL 0.4742 | VL 0.4527 | VD 0.4954 | VI 0.4443 | LR 1.00e-04
  ✓ best saved (val_dice=0.495431) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.96it/s]
C01_loss=BCE | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.80it/s]

[C01_loss=BCE] ep03 | TL 0.4104 | VL 0.5941 | VD 0.3582 | VI 0.3190 | LR 1.00e-04

C01_loss=BCE | 4/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.86it/s]
C01_loss=BCE | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.62it/s]

[C01_loss=BCE] ep04 | TL 0.3358 | VL 0.4166 | VD 0.5299 | VI 0.4789 | LR 1.00e-04
  ✓ best saved (val_dice=0.529937) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 5/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.77it/s]
C01_loss=BCE | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.62it/s]

[C01_loss=BCE] ep05 | TL 0.3061 | VL 0.4777 | VD 0.5956 | VI 0.5436 | LR 1.00e-04
  ✓ best saved (val_dice=0.595590) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.85it/s]
C01_loss=BCE | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.78it/s]

[C01_loss=BCE] ep06 | TL 0.2420 | VL 0.3621 | VD 0.6333 | VI 0.5851 | LR 1.00e-04
  ✓ best saved (val_dice=0.633305) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.16it/s]
C01_loss=BCE | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.32it/s]

[C01_loss=BCE] ep07 | TL 0.2431 | VL 0.3236 | VD 0.6489 | VI 0.6026 | LR 1.00e-04
  ✓ best saved (val_dice=0.648877) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.69it/s]
C01_loss=BCE | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.27it/s]

[C01_loss=BCE] ep08 | TL 0.2015 | VL 0.4562 | VD 0.5627 | VI 0.5038 | LR 1.00e-04

C01_loss=BCE | 9/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.77it/s]
C01_loss=BCE | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.27it/s]

[C01_loss=BCE] ep09 | TL 0.1850 | VL 0.5530 | VD 0.5498 | VI 0.4955 | LR 1.00e-04

C01_loss=BCE | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.21it/s]
C01_loss=BCE | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.59it/s]

[C01_loss=BCE] ep10 | TL 0.1605 | VL 0.3572 | VD 0.6329 | VI 0.5853 | LR 1.00e-04

C01_loss=BCE | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.47it/s]
C01_loss=BCE | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.64it/s]

[C01_loss=BCE] ep11 | TL 0.1785 | VL 0.3866 | VD 0.6075 | VI 0.5602 | LR 1.00e-04

C01_loss=BCE | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.49it/s]
C01_loss=BCE | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.10it/s]

[C01_loss=BCE] ep12 | TL 0.1517 | VL 0.3721 | VD 0.6286 | VI 0.5857 | LR 1.00e-04

C01_loss=BCE | 13/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.53it/s]
C01_loss=BCE | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.44it/s]

[C01_loss=BCE] ep13 | TL 0.1230 | VL 0.3313 | VD 0.6470 | VI 0.5994 | LR 1.00e-04

C01_loss=BCE | 14/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.64it/s]
C01_loss=BCE | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.43it/s]

[C01_loss=BCE] ep14 | TL 0.1565 | VL 0.4633 | VD 0.6107 | VI 0.5668 | LR 1.00e-04

C01_loss=BCE | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.60it/s]
C01_loss=BCE | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.23it/s]

[C01_loss=BCE] ep15 | TL 0.1345 | VL 0.7630 | VD 0.3504 | VI 0.2875 | LR 1.00e-04

C01_loss=BCE | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.34it/s]
C01_loss=BCE | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.87it/s]

[C01_loss=BCE] ep16 | TL 0.1301 | VL 0.3826 | VD 0.6488 | VI 0.6036 | LR 1.00e-04

C01_loss=BCE | 17/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.59it/s]
C01_loss=BCE | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.59it/s]

[C01_loss=BCE] ep17 | TL 0.0985 | VL 0.3519 | VD 0.6553 | VI 0.6148 | LR 1.00e-04
  ✓ best saved (val_dice=0.655345) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.43it/s]
C01_loss=BCE | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.24it/s]

[C01_loss=BCE] ep18 | TL 0.1113 | VL 0.4247 | VD 0.6536 | VI 0.6070 | LR 1.00e-04

C01_loss=BCE | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.64it/s]
C01_loss=BCE | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.54it/s]

[C01_loss=BCE] ep19 | TL 0.0978 | VL 0.3857 | VD 0.6647 | VI 0.6218 | LR 1.00e-04
  ✓ best saved (val_dice=0.664676) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.33it/s]
C01_loss=BCE | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.89it/s]

[C01_loss=BCE] ep20 | TL 0.0752 | VL 0.3310 | VD 0.6719 | VI 0.6285 | LR 1.00e-04
  ✓ best saved (val_dice=0.671874) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.75it/s]
C01_loss=BCE | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.95it/s]

[C01_loss=BCE] ep21 | TL 0.0730 | VL 0.3417 | VD 0.6576 | VI 0.6122 | LR 1.00e-04

C01_loss=BCE | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.86it/s]
C01_loss=BCE | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.52it/s]

[C01_loss=BCE] ep22 | TL 0.0624 | VL 0.3349 | VD 0.6864 | VI 0.6437 | LR 1.00e-04
  ✓ best saved (val_dice=0.686383) -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth

C01_loss=BCE | 23/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.57it/s]
C01_loss=BCE | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.06it/s]

[C01_loss=BCE] ep23 | TL 0.1047 | VL 0.8615 | VD 0.2315 | VI 0.1872 | LR 1.00e-04

C01_loss=BCE | 24/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.68it/s]
C01_loss=BCE | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.20it/s]

[C01_loss=BCE] ep24 | TL 0.1391 | VL 0.3720 | VD 0.6366 | VI 0.5857 | LR 1.00e-04

C01_loss=BCE | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.11it/s]
C01_loss=BCE | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.35it/s]

[C01_loss=BCE] ep25 | TL 0.1136 | VL 0.3311 | VD 0.6848 | VI 0.6417 | LR 1.00e-04

C01_loss=BCE | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.06it/s]
C01_loss=BCE | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.10it/s]

[C01_loss=BCE] ep26 | TL 0.0732 | VL 0.4401 | VD 0.6501 | VI 0.5977 | LR 1.00e-04

C01_loss=BCE | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.77it/s]
C01_loss=BCE | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.43it/s]

[C01_loss=BCE] ep27 | TL 0.0765 | VL 0.3356 | VD 0.6762 | VI 0.6323 | LR 1.00e-04

C01_loss=BCE | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.39it/s]
C01_loss=BCE | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.14it/s]

[C01_loss=BCE] ep28 | TL 0.0749 | VL 0.3464 | VD 0.6767 | VI 0.6341 | LR 1.00e-04

C01_loss=BCE | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.58it/s]
C01_loss=BCE | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.22it/s]

[C01_loss=BCE] ep29 | TL 0.0605 | VL 0.3695 | VD 0.6843 | VI 0.6422 | LR 1.00e-04

C01_loss=BCE | 30/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.57it/s]
C01_loss=BCE | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.33it/s]

[C01_loss=BCE] ep30 | TL 0.0521 | VL 0.3769 | VD 0.6702 | VI 0.6295 | LR 1.00e-04

C01_loss=BCE | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 68.10it/s]
C02_loss=Focal+Dice | 1/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.53it/s]
C02_loss=Focal+Dice | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.69it/s]

[C02_loss=Focal+Dice] ep01 | TL 0.4956 | VL 0.4231 | VD 0.5326 | VI 0.4766 | LR 1.00e-04
  ✓ best saved (val_dice=0.532594) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 2/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.91it/s]
C02_loss=Focal+Dice | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.61it/s]

[C02_loss=Focal+Dice] ep02 | TL 0.4253 | VL 0.3981 | VD 0.5173 | VI 0.4601 | LR 1.00e-04

C02_loss=Focal+Dice | 3/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.20it/s]
C02_loss=Focal+Dice | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.32it/s]

[C02_loss=Focal+Dice] ep03 | TL 0.3736 | VL 0.3661 | VD 0.5288 | VI 0.4756 | LR 1.00e-04

C02_loss=Focal+Dice | 4/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.94it/s]
C02_loss=Focal+Dice | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.29it/s]

[C02_loss=Focal+Dice] ep04 | TL 0.3213 | VL 0.3267 | VD 0.5098 | VI 0.4607 | LR 1.00e-04

C02_loss=Focal+Dice | 5/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.80it/s]
C02_loss=Focal+Dice | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.56it/s]

[C02_loss=Focal+Dice] ep05 | TL 0.2857 | VL 0.4202 | VD 0.5588 | VI 0.5008 | LR 1.00e-04
  ✓ best saved (val_dice=0.558840) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 6/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.74it/s]
C02_loss=Focal+Dice | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.20it/s]

[C02_loss=Focal+Dice] ep06 | TL 0.2331 | VL 0.3267 | VD 0.5901 | VI 0.5405 | LR 1.00e-04
  ✓ best saved (val_dice=0.590111) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 7/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.66it/s]
C02_loss=Focal+Dice | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.66it/s]

[C02_loss=Focal+Dice] ep07 | TL 0.2364 | VL 0.3319 | VD 0.6268 | VI 0.5716 | LR 1.00e-04
  ✓ best saved (val_dice=0.626765) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 8/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.69it/s]
C02_loss=Focal+Dice | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.73it/s]

[C02_loss=Focal+Dice] ep08 | TL 0.2068 | VL 0.3088 | VD 0.6223 | VI 0.5708 | LR 1.00e-04

C02_loss=Focal+Dice | 9/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.65it/s]
C02_loss=Focal+Dice | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.43it/s]

[C02_loss=Focal+Dice] ep09 | TL 0.1718 | VL 0.3342 | VD 0.6235 | VI 0.5698 | LR 1.00e-04

C02_loss=Focal+Dice | 10/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.67it/s]
C02_loss=Focal+Dice | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.46it/s]

[C02_loss=Focal+Dice] ep10 | TL 0.1603 | VL 0.3524 | VD 0.6150 | VI 0.5665 | LR 1.00e-04

C02_loss=Focal+Dice | 11/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.72it/s]
C02_loss=Focal+Dice | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.47it/s]

[C02_loss=Focal+Dice] ep11 | TL 0.1901 | VL 0.4708 | VD 0.6261 | VI 0.5720 | LR 1.00e-04

C02_loss=Focal+Dice | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.17it/s]
C02_loss=Focal+Dice | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.63it/s]

[C02_loss=Focal+Dice] ep12 | TL 0.1549 | VL 0.4947 | VD 0.5979 | VI 0.5480 | LR 1.00e-04

C02_loss=Focal+Dice | 13/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.89it/s]
C02_loss=Focal+Dice | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.41it/s]

[C02_loss=Focal+Dice] ep13 | TL 0.1367 | VL 0.2808 | VD 0.6446 | VI 0.5924 | LR 1.00e-04
  ✓ best saved (val_dice=0.644604) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 14/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.76it/s]
C02_loss=Focal+Dice | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.73it/s]

[C02_loss=Focal+Dice] ep14 | TL 0.1412 | VL 0.3138 | VD 0.6564 | VI 0.6095 | LR 1.00e-04
  ✓ best saved (val_dice=0.656448) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 15/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.92it/s]
C02_loss=Focal+Dice | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.11it/s]

[C02_loss=Focal+Dice] ep15 | TL 0.1250 | VL 0.4596 | VD 0.5676 | VI 0.5000 | LR 1.00e-04

C02_loss=Focal+Dice | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.53it/s]
C02_loss=Focal+Dice | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.03it/s]

[C02_loss=Focal+Dice] ep16 | TL 0.1207 | VL 0.3167 | VD 0.6627 | VI 0.6142 | LR 1.00e-04
  ✓ best saved (val_dice=0.662700) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.05it/s]
C02_loss=Focal+Dice | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.84it/s]

[C02_loss=Focal+Dice] ep17 | TL 0.0947 | VL 0.3283 | VD 0.6627 | VI 0.6138 | LR 1.00e-04

C02_loss=Focal+Dice | 18/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.18it/s]
C02_loss=Focal+Dice | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.87it/s]

[C02_loss=Focal+Dice] ep18 | TL 0.0908 | VL 0.3160 | VD 0.6675 | VI 0.6213 | LR 1.00e-04
  ✓ best saved (val_dice=0.667510) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 19/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.25it/s]
C02_loss=Focal+Dice | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.13it/s]

[C02_loss=Focal+Dice] ep19 | TL 0.0746 | VL 0.4300 | VD 0.6454 | VI 0.5988 | LR 1.00e-04

C02_loss=Focal+Dice | 20/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.88it/s]
C02_loss=Focal+Dice | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.57it/s]

[C02_loss=Focal+Dice] ep20 | TL 0.0732 | VL 0.4138 | VD 0.6579 | VI 0.6111 | LR 1.00e-04

C02_loss=Focal+Dice | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.08it/s]
C02_loss=Focal+Dice | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.20it/s]

[C02_loss=Focal+Dice] ep21 | TL 0.1136 | VL 0.3173 | VD 0.6641 | VI 0.6166 | LR 1.00e-04

C02_loss=Focal+Dice | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.62it/s]
C02_loss=Focal+Dice | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.69it/s]

[C02_loss=Focal+Dice] ep22 | TL 0.0805 | VL 0.3026 | VD 0.6653 | VI 0.6167 | LR 1.00e-04

C02_loss=Focal+Dice | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.41it/s]
C02_loss=Focal+Dice | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.23it/s]

[C02_loss=Focal+Dice] ep23 | TL 0.0767 | VL 0.3011 | VD 0.6550 | VI 0.6058 | LR 1.00e-04

C02_loss=Focal+Dice | 24/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.38it/s]
C02_loss=Focal+Dice | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.78it/s]

[C02_loss=Focal+Dice] ep24 | TL 0.0732 | VL 0.2894 | VD 0.6964 | VI 0.6515 | LR 1.00e-04
  ✓ best saved (val_dice=0.696373) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 25/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.68it/s]
C02_loss=Focal+Dice | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.71it/s]

[C02_loss=Focal+Dice] ep25 | TL 0.0544 | VL 0.3315 | VD 0.7018 | VI 0.6587 | LR 1.00e-04
  ✓ best saved (val_dice=0.701814) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 26/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.91it/s]
C02_loss=Focal+Dice | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.45it/s]

[C02_loss=Focal+Dice] ep26 | TL 0.0627 | VL 0.3422 | VD 0.6925 | VI 0.6497 | LR 1.00e-04

C02_loss=Focal+Dice | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.15it/s]
C02_loss=Focal+Dice | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.15it/s]

[C02_loss=Focal+Dice] ep27 | TL 0.0696 | VL 0.3624 | VD 0.6613 | VI 0.6111 | LR 1.00e-04

C02_loss=Focal+Dice | 28/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.34it/s]
C02_loss=Focal+Dice | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.22it/s]

[C02_loss=Focal+Dice] ep28 | TL 0.0887 | VL 0.3544 | VD 0.6756 | VI 0.6288 | LR 1.00e-04

C02_loss=Focal+Dice | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.18it/s]
C02_loss=Focal+Dice | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.15it/s]

[C02_loss=Focal+Dice] ep29 | TL 0.0556 | VL 0.3195 | VD 0.7048 | VI 0.6616 | LR 1.00e-04
  ✓ best saved (val_dice=0.704755) -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.91it/s]
C02_loss=Focal+Dice | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.67it/s]

[C02_loss=Focal+Dice] ep30 | TL 0.0633 | VL 0.3836 | VD 0.6907 | VI 0.6457 | LR 1.00e-04

C02_loss=Focal+Dice | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 69.93it/s]
C03_sched=plateau | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.15it/s]
C03_sched=plateau | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.91it/s]

[C03_sched=plateau] ep01 | TL 1.0161 | VL 0.8118 | VD 0.4622 | VI 0.4125 | LR 1.00e-04
  ✓ best saved (val_dice=0.462162) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.44it/s]
C03_sched=plateau | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.72it/s]

[C03_sched=plateau] ep02 | TL 0.8206 | VL 0.7362 | VD 0.5006 | VI 0.4490 | LR 1.00e-04
  ✓ best saved (val_dice=0.500566) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.53it/s]
C03_sched=plateau | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.99it/s]

[C03_sched=plateau] ep03 | TL 0.7102 | VL 0.7448 | VD 0.4512 | VI 0.4051 | LR 1.00e-04

C03_sched=plateau | 4/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.60it/s]
C03_sched=plateau | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.38it/s]

[C03_sched=plateau] ep04 | TL 0.5684 | VL 0.8340 | VD 0.4937 | VI 0.4429 | LR 1.00e-04

C03_sched=plateau | 5/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.46it/s]
C03_sched=plateau | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.28it/s]

[C03_sched=plateau] ep05 | TL 0.5400 | VL 0.8042 | VD 0.5401 | VI 0.4851 | LR 5.00e-05
  ✓ best saved (val_dice=0.540093) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.35it/s]
C03_sched=plateau | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.62it/s]

[C03_sched=plateau] ep06 | TL 0.3826 | VL 0.5344 | VD 0.6454 | VI 0.6032 | LR 5.00e-05
  ✓ best saved (val_dice=0.645359) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 7/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.57it/s]
C03_sched=plateau | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.61it/s]

[C03_sched=plateau] ep07 | TL 0.3463 | VL 0.5697 | VD 0.6290 | VI 0.5871 | LR 5.00e-05

C03_sched=plateau | 8/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.06it/s]
C03_sched=plateau | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.37it/s]

[C03_sched=plateau] ep08 | TL 0.3068 | VL 0.5244 | VD 0.6431 | VI 0.5991 | LR 5.00e-05

C03_sched=plateau | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.11it/s]
C03_sched=plateau | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.81it/s]

[C03_sched=plateau] ep09 | TL 0.2737 | VL 0.5661 | VD 0.6465 | VI 0.6029 | LR 5.00e-05
  ✓ best saved (val_dice=0.646486) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 10/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.43it/s]
C03_sched=plateau | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.18it/s]

[C03_sched=plateau] ep10 | TL 0.2401 | VL 0.5315 | VD 0.6397 | VI 0.5960 | LR 5.00e-05

C03_sched=plateau | 11/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.95it/s]
C03_sched=plateau | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.98it/s]

[C03_sched=plateau] ep11 | TL 0.2665 | VL 0.6830 | VD 0.6097 | VI 0.5626 | LR 2.50e-05

C03_sched=plateau | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.90it/s]
C03_sched=plateau | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.66it/s]

[C03_sched=plateau] ep12 | TL 0.2048 | VL 0.5029 | VD 0.6645 | VI 0.6203 | LR 2.50e-05
  ✓ best saved (val_dice=0.664549) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.21it/s]
C03_sched=plateau | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.01it/s]

[C03_sched=plateau] ep13 | TL 0.1857 | VL 0.4922 | VD 0.6742 | VI 0.6292 | LR 2.50e-05
  ✓ best saved (val_dice=0.674170) -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth

C03_sched=plateau | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.58it/s]
C03_sched=plateau | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.71it/s]

[C03_sched=plateau] ep14 | TL 0.1857 | VL 0.5426 | VD 0.6640 | VI 0.6206 | LR 2.50e-05

C03_sched=plateau | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.10it/s]
C03_sched=plateau | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.75it/s]

[C03_sched=plateau] ep15 | TL 0.1927 | VL 0.4983 | VD 0.6596 | VI 0.6135 | LR 2.50e-05

C03_sched=plateau | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.91it/s]
C03_sched=plateau | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.34it/s]

[C03_sched=plateau] ep16 | TL 0.1722 | VL 0.5153 | VD 0.6629 | VI 0.6182 | LR 1.25e-05

C03_sched=plateau | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.32it/s]
C03_sched=plateau | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.01it/s]

[C03_sched=plateau] ep17 | TL 0.1444 | VL 0.4972 | VD 0.6640 | VI 0.6190 | LR 1.25e-05

C03_sched=plateau | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.15it/s]
C03_sched=plateau | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.59it/s]

[C03_sched=plateau] ep18 | TL 0.1476 | VL 0.5205 | VD 0.6648 | VI 0.6209 | LR 1.25e-05

C03_sched=plateau | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.30it/s]
C03_sched=plateau | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.60it/s]

[C03_sched=plateau] ep19 | TL 0.1326 | VL 0.5030 | VD 0.6658 | VI 0.6215 | LR 6.25e-06

C03_sched=plateau | 20/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.99it/s]
C03_sched=plateau | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.91it/s]

[C03_sched=plateau] ep20 | TL 0.1304 | VL 0.5057 | VD 0.6596 | VI 0.6147 | LR 6.25e-06

C03_sched=plateau | 21/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.91it/s]
C03_sched=plateau | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.13it/s]

[C03_sched=plateau] ep21 | TL 0.1323 | VL 0.4979 | VD 0.6690 | VI 0.6251 | LR 6.25e-06

C03_sched=plateau | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.21it/s]
C03_sched=plateau | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.13it/s]

[C03_sched=plateau] ep22 | TL 0.1219 | VL 0.5010 | VD 0.6647 | VI 0.6207 | LR 3.13e-06

C03_sched=plateau | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.82it/s]
C03_sched=plateau | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.50it/s]

[C03_sched=plateau] ep23 | TL 0.1401 | VL 0.4981 | VD 0.6655 | VI 0.6208 | LR 3.13e-06

C03_sched=plateau | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.02it/s]
C03_sched=plateau | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.96it/s]

[C03_sched=plateau] ep24 | TL 0.1417 | VL 0.5091 | VD 0.6680 | VI 0.6242 | LR 3.13e-06

C03_sched=plateau | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.74it/s]
C03_sched=plateau | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.92it/s]

[C03_sched=plateau] ep25 | TL 0.1179 | VL 0.5198 | VD 0.6611 | VI 0.6169 | LR 1.56e-06

C03_sched=plateau | 26/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.33it/s]
C03_sched=plateau | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.19it/s]

[C03_sched=plateau] ep26 | TL 0.1294 | VL 0.5144 | VD 0.6628 | VI 0.6192 | LR 1.56e-06

C03_sched=plateau | 27/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.28it/s]
C03_sched=plateau | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.62it/s]

[C03_sched=plateau] ep27 | TL 0.1246 | VL 0.5140 | VD 0.6648 | VI 0.6210 | LR 1.56e-06

C03_sched=plateau | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.13it/s]
C03_sched=plateau | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.03it/s]

[C03_sched=plateau] ep28 | TL 0.1320 | VL 0.5175 | VD 0.6580 | VI 0.6151 | LR 1.00e-06

C03_sched=plateau | 29/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.81it/s]
C03_sched=plateau | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.56it/s]

[C03_sched=plateau] ep29 | TL 0.1146 | VL 0.5111 | VD 0.6670 | VI 0.6225 | LR 1.00e-06

C03_sched=plateau | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.76it/s]
C03_sched=plateau | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.31it/s]

[C03_sched=plateau] ep30 | TL 0.1196 | VL 0.5110 | VD 0.6664 | VI 0.6226 | LR 1.00e-06

C03_sched=plateau | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 67.93it/s]
/tmp/ipython-input-3548071429.py:183: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp) if use_amp else None
C04_amp=on | 1/30 TRAIN:   0%|          | 0/252 [00:00<?, ?it/s]/tmp/ipython-input-3548071429.py:95: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(True):
C04_amp=on | 1/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.35it/s]
C04_amp=on | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 63.64it/s]

[C04_amp=on] ep01 | TL 1.0274 | VL 0.8273 | VD 0.4348 | VI 0.3884 | LR 1.00e-04
  ✓ best saved (val_dice=0.434758) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.90it/s]
C04_amp=on | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.92it/s]

[C04_amp=on] ep02 | TL 0.8293 | VL 0.7800 | VD 0.5318 | VI 0.4795 | LR 1.00e-04
  ✓ best saved (val_dice=0.531779) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.79it/s]
C04_amp=on | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.65it/s]

[C04_amp=on] ep03 | TL 0.7258 | VL 0.7480 | VD 0.4931 | VI 0.4430 | LR 1.00e-04

C04_amp=on | 4/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.51it/s]
C04_amp=on | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.06it/s]

[C04_amp=on] ep04 | TL 0.5872 | VL 0.6663 | VD 0.6039 | VI 0.5503 | LR 1.00e-04
  ✓ best saved (val_dice=0.603859) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 5/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.28it/s]
C04_amp=on | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.03it/s]

[C04_amp=on] ep05 | TL 0.5187 | VL 0.6269 | VD 0.5995 | VI 0.5517 | LR 1.00e-04

C04_amp=on | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.88it/s]
C04_amp=on | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.32it/s]

[C04_amp=on] ep06 | TL 0.4266 | VL 0.6549 | VD 0.6355 | VI 0.5823 | LR 1.00e-04
  ✓ best saved (val_dice=0.635487) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.20it/s]
C04_amp=on | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.34it/s]

[C04_amp=on] ep07 | TL 0.4211 | VL 0.5829 | VD 0.6401 | VI 0.5961 | LR 1.00e-04
  ✓ best saved (val_dice=0.640122) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.57it/s]
C04_amp=on | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.62it/s]

[C04_amp=on] ep08 | TL 0.3840 | VL 0.5578 | VD 0.6315 | VI 0.5860 | LR 1.00e-04

C04_amp=on | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.54it/s]
C04_amp=on | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.03it/s]

[C04_amp=on] ep09 | TL 0.3029 | VL 1.0245 | VD 0.6060 | VI 0.5499 | LR 1.00e-04

C04_amp=on | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.32it/s]
C04_amp=on | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.02it/s]

[C04_amp=on] ep10 | TL 0.2739 | VL 0.8697 | VD 0.5591 | VI 0.5063 | LR 1.00e-04

C04_amp=on | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.70it/s]
C04_amp=on | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.37it/s]

[C04_amp=on] ep11 | TL 0.3099 | VL 0.9457 | VD 0.5532 | VI 0.4996 | LR 1.00e-04

C04_amp=on | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.90it/s]
C04_amp=on | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.32it/s]

[C04_amp=on] ep12 | TL 0.2534 | VL 0.6160 | VD 0.6527 | VI 0.6070 | LR 1.00e-04
  ✓ best saved (val_dice=0.652690) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.27it/s]
C04_amp=on | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.46it/s]

[C04_amp=on] ep13 | TL 0.2423 | VL 0.5489 | VD 0.6693 | VI 0.6211 | LR 1.00e-04
  ✓ best saved (val_dice=0.669303) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 14/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.67it/s]
C04_amp=on | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.71it/s]

[C04_amp=on] ep14 | TL 0.2314 | VL 0.5779 | VD 0.6670 | VI 0.6228 | LR 1.00e-04

C04_amp=on | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.92it/s]
C04_amp=on | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.89it/s]

[C04_amp=on] ep15 | TL 0.2112 | VL 1.3529 | VD 0.5751 | VI 0.5180 | LR 1.00e-04

C04_amp=on | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.05it/s]
C04_amp=on | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.14it/s]

[C04_amp=on] ep16 | TL 0.1979 | VL 0.5802 | VD 0.6584 | VI 0.6161 | LR 1.00e-04

C04_amp=on | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.63it/s]
C04_amp=on | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.88it/s]

[C04_amp=on] ep17 | TL 0.1888 | VL 0.6006 | VD 0.6517 | VI 0.6047 | LR 1.00e-04

C04_amp=on | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.34it/s]
C04_amp=on | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.98it/s]

[C04_amp=on] ep18 | TL 0.2099 | VL 0.5276 | VD 0.6735 | VI 0.6289 | LR 1.00e-04
  ✓ best saved (val_dice=0.673506) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 19/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.64it/s]
C04_amp=on | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.68it/s]

[C04_amp=on] ep19 | TL 0.1629 | VL 0.5860 | VD 0.6436 | VI 0.5996 | LR 1.00e-04

C04_amp=on | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.03it/s]
C04_amp=on | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.68it/s]

[C04_amp=on] ep20 | TL 0.1340 | VL 0.5409 | VD 0.6522 | VI 0.6058 | LR 1.00e-04

C04_amp=on | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.46it/s]
C04_amp=on | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.87it/s]

[C04_amp=on] ep21 | TL 0.1428 | VL 0.5522 | VD 0.6613 | VI 0.6164 | LR 1.00e-04

C04_amp=on | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.06it/s]
C04_amp=on | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.12it/s]

[C04_amp=on] ep22 | TL 0.1116 | VL 0.5417 | VD 0.6692 | VI 0.6279 | LR 1.00e-04

C04_amp=on | 23/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.20it/s]
C04_amp=on | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.63it/s]

[C04_amp=on] ep23 | TL 0.1365 | VL 1.5395 | VD 0.5780 | VI 0.5211 | LR 1.00e-04

C04_amp=on | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.90it/s]
C04_amp=on | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.74it/s]

[C04_amp=on] ep24 | TL 0.2111 | VL 0.7598 | VD 0.6241 | VI 0.5801 | LR 1.00e-04

C04_amp=on | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.53it/s]
C04_amp=on | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.00it/s]

[C04_amp=on] ep25 | TL 0.1502 | VL 0.6133 | VD 0.6706 | VI 0.6262 | LR 1.00e-04

C04_amp=on | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.06it/s]
C04_amp=on | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.17it/s]

[C04_amp=on] ep26 | TL 0.1496 | VL 0.6150 | VD 0.6487 | VI 0.5994 | LR 1.00e-04

C04_amp=on | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.11it/s]
C04_amp=on | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.55it/s]

[C04_amp=on] ep27 | TL 0.1314 | VL 0.5784 | VD 0.6822 | VI 0.6377 | LR 1.00e-04
  ✓ best saved (val_dice=0.682223) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.54it/s]
C04_amp=on | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.06it/s]

[C04_amp=on] ep28 | TL 0.1129 | VL 0.6160 | VD 0.6753 | VI 0.6358 | LR 1.00e-04

C04_amp=on | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.05it/s]
C04_amp=on | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.78it/s]

[C04_amp=on] ep29 | TL 0.0867 | VL 0.5549 | VD 0.6985 | VI 0.6571 | LR 1.00e-04
  ✓ best saved (val_dice=0.698459) -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth

C04_amp=on | 30/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.19it/s]
C04_amp=on | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.71it/s]

[C04_amp=on] ep30 | TL 0.0846 | VL 0.7695 | VD 0.6509 | VI 0.6080 | LR 1.00e-04

C04_amp=on | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 64.43it/s]
C05_clip=1.0 | 1/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.53it/s]
C05_clip=1.0 | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.88it/s]

[C05_clip=1.0] ep01 | TL 1.0099 | VL 0.8058 | VD 0.4715 | VI 0.4199 | LR 1.00e-04
  ✓ best saved (val_dice=0.471458) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.48it/s]
C05_clip=1.0 | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.50it/s]

[C05_clip=1.0] ep02 | TL 0.8201 | VL 0.7924 | VD 0.4362 | VI 0.3903 | LR 1.00e-04

C05_clip=1.0 | 3/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.89it/s]
C05_clip=1.0 | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.63it/s]

[C05_clip=1.0] ep03 | TL 0.6940 | VL 0.7586 | VD 0.5735 | VI 0.5219 | LR 1.00e-04
  ✓ best saved (val_dice=0.573531) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 4/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.40it/s]
C05_clip=1.0 | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.49it/s]

[C05_clip=1.0] ep04 | TL 0.5581 | VL 0.7807 | VD 0.5539 | VI 0.5049 | LR 1.00e-04

C05_clip=1.0 | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.33it/s]
C05_clip=1.0 | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.99it/s]

[C05_clip=1.0] ep05 | TL 0.4824 | VL 0.7294 | VD 0.5737 | VI 0.5209 | LR 1.00e-04
  ✓ best saved (val_dice=0.573690) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 6/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.83it/s]
C05_clip=1.0 | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.87it/s]

[C05_clip=1.0] ep06 | TL 0.3910 | VL 0.6867 | VD 0.6328 | VI 0.5809 | LR 1.00e-04
  ✓ best saved (val_dice=0.632802) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.44it/s]
C05_clip=1.0 | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 62.21it/s]

[C05_clip=1.0] ep07 | TL 0.3660 | VL 0.6684 | VD 0.6471 | VI 0.5961 | LR 1.00e-04
  ✓ best saved (val_dice=0.647062) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.06it/s]
C05_clip=1.0 | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.83it/s]

[C05_clip=1.0] ep08 | TL 0.3255 | VL 0.7257 | VD 0.6226 | VI 0.5732 | LR 1.00e-04

C05_clip=1.0 | 9/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.57it/s]
C05_clip=1.0 | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.97it/s]

[C05_clip=1.0] ep09 | TL 0.2829 | VL 0.6678 | VD 0.6148 | VI 0.5665 | LR 1.00e-04

C05_clip=1.0 | 10/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.92it/s]
C05_clip=1.0 | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.66it/s]

[C05_clip=1.0] ep10 | TL 0.2408 | VL 0.5577 | VD 0.6483 | VI 0.6009 | LR 1.00e-04
  ✓ best saved (val_dice=0.648297) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 11/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.93it/s]
C05_clip=1.0 | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.52it/s]

[C05_clip=1.0] ep11 | TL 0.2498 | VL 0.6355 | VD 0.6724 | VI 0.6236 | LR 1.00e-04
  ✓ best saved (val_dice=0.672441) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.89it/s]
C05_clip=1.0 | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.84it/s]

[C05_clip=1.0] ep12 | TL 0.2061 | VL 0.6213 | VD 0.6619 | VI 0.6161 | LR 1.00e-04

C05_clip=1.0 | 13/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.91it/s]
C05_clip=1.0 | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.00it/s]

[C05_clip=1.0] ep13 | TL 0.1822 | VL 0.7127 | VD 0.6395 | VI 0.5896 | LR 1.00e-04

C05_clip=1.0 | 14/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.24it/s]
C05_clip=1.0 | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.86it/s]

[C05_clip=1.0] ep14 | TL 0.1782 | VL 0.7342 | VD 0.6513 | VI 0.6040 | LR 1.00e-04

C05_clip=1.0 | 15/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.54it/s]
C05_clip=1.0 | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.91it/s]

[C05_clip=1.0] ep15 | TL 0.1738 | VL 0.6005 | VD 0.6565 | VI 0.6121 | LR 1.00e-04

C05_clip=1.0 | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.08it/s]
C05_clip=1.0 | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.50it/s]

[C05_clip=1.0] ep16 | TL 0.1347 | VL 0.7527 | VD 0.6772 | VI 0.6304 | LR 1.00e-04
  ✓ best saved (val_dice=0.677199) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 17/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.31it/s]
C05_clip=1.0 | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.40it/s]

[C05_clip=1.0] ep17 | TL 0.1137 | VL 0.6828 | VD 0.6649 | VI 0.6173 | LR 1.00e-04

C05_clip=1.0 | 18/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.93it/s]
C05_clip=1.0 | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.66it/s]

[C05_clip=1.0] ep18 | TL 0.1171 | VL 0.7513 | VD 0.6674 | VI 0.6215 | LR 1.00e-04

C05_clip=1.0 | 19/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.92it/s]
C05_clip=1.0 | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.40it/s]

[C05_clip=1.0] ep19 | TL 0.0909 | VL 0.6638 | VD 0.6826 | VI 0.6411 | LR 1.00e-04
  ✓ best saved (val_dice=0.682579) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 20/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.83it/s]
C05_clip=1.0 | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.63it/s]

[C05_clip=1.0] ep20 | TL 0.0883 | VL 0.6188 | VD 0.7065 | VI 0.6654 | LR 1.00e-04
  ✓ best saved (val_dice=0.706546) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.08it/s]
C05_clip=1.0 | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.25it/s]

[C05_clip=1.0] ep21 | TL 0.0889 | VL 0.6672 | VD 0.6873 | VI 0.6457 | LR 1.00e-04

C05_clip=1.0 | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.93it/s]
C05_clip=1.0 | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.93it/s]

[C05_clip=1.0] ep22 | TL 0.0722 | VL 0.6441 | VD 0.6961 | VI 0.6571 | LR 1.00e-04

C05_clip=1.0 | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.44it/s]
C05_clip=1.0 | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.79it/s]

[C05_clip=1.0] ep23 | TL 0.1135 | VL 0.6668 | VD 0.7097 | VI 0.6666 | LR 1.00e-04
  ✓ best saved (val_dice=0.709704) -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth

C05_clip=1.0 | 24/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.10it/s]
C05_clip=1.0 | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.53it/s]

[C05_clip=1.0] ep24 | TL 0.1050 | VL 0.9654 | VD 0.6818 | VI 0.6385 | LR 1.00e-04

C05_clip=1.0 | 25/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.94it/s]
C05_clip=1.0 | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.38it/s]

[C05_clip=1.0] ep25 | TL 0.0633 | VL 0.7484 | VD 0.6962 | VI 0.6554 | LR 1.00e-04

C05_clip=1.0 | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.26it/s]
C05_clip=1.0 | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.75it/s]

[C05_clip=1.0] ep26 | TL 0.0844 | VL 0.6331 | VD 0.6765 | VI 0.6351 | LR 1.00e-04

C05_clip=1.0 | 27/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.53it/s]
C05_clip=1.0 | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.41it/s]

[C05_clip=1.0] ep27 | TL 0.0789 | VL 0.6888 | VD 0.7073 | VI 0.6679 | LR 1.00e-04

C05_clip=1.0 | 28/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.98it/s]
C05_clip=1.0 | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.06it/s]

[C05_clip=1.0] ep28 | TL 0.0904 | VL 0.7927 | VD 0.6685 | VI 0.6299 | LR 1.00e-04

C05_clip=1.0 | 29/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.93it/s]
C05_clip=1.0 | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.82it/s]

[C05_clip=1.0] ep29 | TL 0.0531 | VL 0.7375 | VD 0.6851 | VI 0.6451 | LR 1.00e-04

C05_clip=1.0 | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.96it/s]
C05_clip=1.0 | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.20it/s]

[C05_clip=1.0] ep30 | TL 0.0575 | VL 0.9562 | VD 0.6683 | VI 0.6274 | LR 1.00e-04

C05_clip=1.0 | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 68.74it/s]
C06_freeze=2ep | 1/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.47it/s]
C06_freeze=2ep | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.54it/s]

[C06_freeze=2ep] ep01 | TL 1.1275 | VL 0.9771 | VD 0.4864 | VI 0.4188 | LR 1.00e-04
  ✓ best saved (val_dice=0.486371) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.45it/s]
C06_freeze=2ep | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.65it/s]

[C06_freeze=2ep] ep02 | TL 1.0341 | VL 0.9386 | VD 0.4775 | VI 0.4107 | LR 1.00e-04

C06_freeze=2ep | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.21it/s]
C06_freeze=2ep | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.99it/s]

[C06_freeze=2ep] ep03 | TL 0.9444 | VL 0.7789 | VD 0.4787 | VI 0.4285 | LR 1.00e-04

C06_freeze=2ep | 4/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.26it/s]
C06_freeze=2ep | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.94it/s]

[C06_freeze=2ep] ep04 | TL 0.7728 | VL 0.8282 | VD 0.3940 | VI 0.3471 | LR 1.00e-04

C06_freeze=2ep | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.19it/s]
C06_freeze=2ep | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.14it/s]

[C06_freeze=2ep] ep05 | TL 0.6839 | VL 0.7247 | VD 0.5479 | VI 0.4970 | LR 1.00e-04
  ✓ best saved (val_dice=0.547872) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.15it/s]
C06_freeze=2ep | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.21it/s]

[C06_freeze=2ep] ep06 | TL 0.5359 | VL 0.9129 | VD 0.5621 | VI 0.5041 | LR 1.00e-04
  ✓ best saved (val_dice=0.562055) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.27it/s]
C06_freeze=2ep | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.12it/s]

[C06_freeze=2ep] ep07 | TL 0.5018 | VL 0.7070 | VD 0.5670 | VI 0.5184 | LR 1.00e-04
  ✓ best saved (val_dice=0.566995) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.12it/s]
C06_freeze=2ep | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.45it/s]

[C06_freeze=2ep] ep08 | TL 0.4467 | VL 0.6553 | VD 0.6013 | VI 0.5526 | LR 1.00e-04
  ✓ best saved (val_dice=0.601259) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.37it/s]
C06_freeze=2ep | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.61it/s]

[C06_freeze=2ep] ep09 | TL 0.3855 | VL 0.6156 | VD 0.6163 | VI 0.5681 | LR 1.00e-04
  ✓ best saved (val_dice=0.616287) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.24it/s]
C06_freeze=2ep | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.07it/s]

[C06_freeze=2ep] ep10 | TL 0.3526 | VL 0.7194 | VD 0.5814 | VI 0.5277 | LR 1.00e-04

C06_freeze=2ep | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.15it/s]
C06_freeze=2ep | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.16it/s]

[C06_freeze=2ep] ep11 | TL 0.3898 | VL 0.8679 | VD 0.5366 | VI 0.4857 | LR 1.00e-04

C06_freeze=2ep | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.23it/s]
C06_freeze=2ep | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.78it/s]

[C06_freeze=2ep] ep12 | TL 0.3172 | VL 0.5988 | VD 0.6411 | VI 0.5964 | LR 1.00e-04
  ✓ best saved (val_dice=0.641056) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.16it/s]
C06_freeze=2ep | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.52it/s]

[C06_freeze=2ep] ep13 | TL 0.2789 | VL 0.5204 | VD 0.6501 | VI 0.6025 | LR 1.00e-04
  ✓ best saved (val_dice=0.650105) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 14/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.89it/s]
C06_freeze=2ep | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.64it/s]

[C06_freeze=2ep] ep14 | TL 0.2567 | VL 0.5420 | VD 0.6504 | VI 0.6056 | LR 1.00e-04
  ✓ best saved (val_dice=0.650439) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.25it/s]
C06_freeze=2ep | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.79it/s]

[C06_freeze=2ep] ep15 | TL 0.2527 | VL 0.5712 | VD 0.6005 | VI 0.5484 | LR 1.00e-04

C06_freeze=2ep | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.87it/s]
C06_freeze=2ep | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.67it/s]

[C06_freeze=2ep] ep16 | TL 0.2179 | VL 0.5878 | VD 0.6480 | VI 0.6020 | LR 1.00e-04

C06_freeze=2ep | 17/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.26it/s]
C06_freeze=2ep | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.23it/s]

[C06_freeze=2ep] ep17 | TL 0.1864 | VL 0.5558 | VD 0.6237 | VI 0.5753 | LR 1.00e-04

C06_freeze=2ep | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.24it/s]
C06_freeze=2ep | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.70it/s]

[C06_freeze=2ep] ep18 | TL 0.2069 | VL 0.5219 | VD 0.6592 | VI 0.6160 | LR 1.00e-04
  ✓ best saved (val_dice=0.659208) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.13it/s]
C06_freeze=2ep | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.70it/s]

[C06_freeze=2ep] ep19 | TL 0.1566 | VL 0.5331 | VD 0.6506 | VI 0.6066 | LR 1.00e-04

C06_freeze=2ep | 20/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.70it/s]
C06_freeze=2ep | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.20it/s]

[C06_freeze=2ep] ep20 | TL 0.1394 | VL 0.5362 | VD 0.6565 | VI 0.6136 | LR 1.00e-04

C06_freeze=2ep | 21/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.83it/s]
C06_freeze=2ep | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.01it/s]

[C06_freeze=2ep] ep21 | TL 0.1778 | VL 1.0070 | VD 0.5576 | VI 0.4996 | LR 1.00e-04

C06_freeze=2ep | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.03it/s]
C06_freeze=2ep | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.54it/s]

[C06_freeze=2ep] ep22 | TL 0.1461 | VL 0.5970 | VD 0.6466 | VI 0.6026 | LR 1.00e-04

C06_freeze=2ep | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.85it/s]
C06_freeze=2ep | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.35it/s]

[C06_freeze=2ep] ep23 | TL 0.2341 | VL 0.8023 | VD 0.5890 | VI 0.5355 | LR 1.00e-04

C06_freeze=2ep | 24/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.55it/s]
C06_freeze=2ep | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.09it/s]

[C06_freeze=2ep] ep24 | TL 0.2270 | VL 0.5742 | VD 0.6541 | VI 0.6098 | LR 1.00e-04

C06_freeze=2ep | 25/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.81it/s]
C06_freeze=2ep | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.07it/s]

[C06_freeze=2ep] ep25 | TL 0.1364 | VL 0.5200 | VD 0.6719 | VI 0.6279 | LR 1.00e-04
  ✓ best saved (val_dice=0.671911) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.22it/s]
C06_freeze=2ep | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.46it/s]

[C06_freeze=2ep] ep26 | TL 0.1378 | VL 0.6997 | VD 0.6252 | VI 0.5806 | LR 1.00e-04

C06_freeze=2ep | 27/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.93it/s]
C06_freeze=2ep | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.83it/s]

[C06_freeze=2ep] ep27 | TL 0.1573 | VL 0.5370 | VD 0.6643 | VI 0.6185 | LR 1.00e-04

C06_freeze=2ep | 28/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.70it/s]
C06_freeze=2ep | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.63it/s]

[C06_freeze=2ep] ep28 | TL 0.1359 | VL 0.6328 | VD 0.6562 | VI 0.6124 | LR 1.00e-04

C06_freeze=2ep | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.16it/s]
C06_freeze=2ep | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.95it/s]

[C06_freeze=2ep] ep29 | TL 0.1097 | VL 0.5694 | VD 0.6795 | VI 0.6387 | LR 1.00e-04
  ✓ best saved (val_dice=0.679492) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.83it/s]
C06_freeze=2ep | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.22it/s]

[C06_freeze=2ep] ep30 | TL 0.0927 | VL 0.6055 | VD 0.6840 | VI 0.6459 | LR 1.00e-04
  ✓ best saved (val_dice=0.684024) -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth

C06_freeze=2ep | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 69.03it/s]
C07_ES=on | 1/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.53it/s]
C07_ES=on | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.41it/s]

[C07_ES=on] ep01 | TL 1.0161 | VL 0.8118 | VD 0.4622 | VI 0.4125 | LR 1.00e-04
  ✓ best saved (val_dice=0.462162) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.11it/s]
C07_ES=on | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.23it/s]

[C07_ES=on] ep02 | TL 0.8206 | VL 0.7362 | VD 0.5006 | VI 0.4490 | LR 1.00e-04
  ✓ best saved (val_dice=0.500566) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 3/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.60it/s]
C07_ES=on | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.81it/s]

[C07_ES=on] ep03 | TL 0.7102 | VL 0.7448 | VD 0.4512 | VI 0.4051 | LR 1.00e-04

C07_ES=on | 4/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.46it/s]
C07_ES=on | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.46it/s]

[C07_ES=on] ep04 | TL 0.5684 | VL 0.8340 | VD 0.4937 | VI 0.4429 | LR 1.00e-04

C07_ES=on | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.35it/s]
C07_ES=on | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.36it/s]

[C07_ES=on] ep05 | TL 0.5400 | VL 0.8042 | VD 0.5401 | VI 0.4851 | LR 1.00e-04
  ✓ best saved (val_dice=0.540093) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.18it/s]
C07_ES=on | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.37it/s]

[C07_ES=on] ep06 | TL 0.4127 | VL 0.6064 | VD 0.6222 | VI 0.5735 | LR 1.00e-04
  ✓ best saved (val_dice=0.622159) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.52it/s]
C07_ES=on | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.40it/s]

[C07_ES=on] ep07 | TL 0.4139 | VL 0.8083 | VD 0.5658 | VI 0.5193 | LR 1.00e-04

C07_ES=on | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.43it/s]
C07_ES=on | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.34it/s]

[C07_ES=on] ep08 | TL 0.3586 | VL 0.6412 | VD 0.6234 | VI 0.5782 | LR 1.00e-04
  ✓ best saved (val_dice=0.623389) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 9/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.74it/s]
C07_ES=on | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.80it/s]

[C07_ES=on] ep09 | TL 0.3212 | VL 0.6536 | VD 0.6417 | VI 0.5906 | LR 1.00e-04
  ✓ best saved (val_dice=0.641675) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 10/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.69it/s]
C07_ES=on | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.84it/s]

[C07_ES=on] ep10 | TL 0.2668 | VL 0.5602 | VD 0.6338 | VI 0.5878 | LR 1.00e-04

C07_ES=on | 11/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.77it/s]
C07_ES=on | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.84it/s]

[C07_ES=on] ep11 | TL 0.3016 | VL 0.6013 | VD 0.6505 | VI 0.6072 | LR 1.00e-04
  ✓ best saved (val_dice=0.650516) -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth

C07_ES=on | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.54it/s]
C07_ES=on | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.11it/s]

[C07_ES=on] ep12 | TL 0.2367 | VL 0.6389 | VD 0.6465 | VI 0.6021 | LR 1.00e-04

C07_ES=on | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.03it/s]
C07_ES=on | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.68it/s]

[C07_ES=on] ep13 | TL 0.2250 | VL 0.5435 | VD 0.6450 | VI 0.5973 | LR 1.00e-04

C07_ES=on | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.29it/s]
C07_ES=on | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.82it/s]

[C07_ES=on] ep14 | TL 0.2508 | VL 0.5719 | VD 0.6440 | VI 0.5995 | LR 1.00e-04

C07_ES=on | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.09it/s]
C07_ES=on | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.06it/s]

[C07_ES=on] ep15 | TL 0.2347 | VL 0.6213 | VD 0.6000 | VI 0.5406 | LR 1.00e-04

C07_ES=on | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.23it/s]
C07_ES=on | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.34it/s]

[C07_ES=on] ep16 | TL 0.2248 | VL 0.6117 | VD 0.6484 | VI 0.6029 | LR 1.00e-04

C07_ES=on | 17/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.98it/s]
C07_ES=on | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.85it/s]

[C07_ES=on] ep17 | TL 0.1685 | VL 0.5486 | VD 0.6493 | VI 0.6003 | LR 1.00e-04
⛔ early stop (best ep=11, best val_dice=0.650516)

C07_ES=on | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 70.62it/s]
C08_lr=5e-5 | 1/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.38it/s]
C08_lr=5e-5 | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.10it/s]

[C08_lr=5e-5] ep01 | TL 1.0638 | VL 0.8175 | VD 0.4780 | VI 0.4230 | LR 5.00e-05
  ✓ best saved (val_dice=0.477967) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 2/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.49it/s]
C08_lr=5e-5 | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.35it/s]

[C08_lr=5e-5] ep02 | TL 0.8249 | VL 0.7572 | VD 0.4886 | VI 0.4358 | LR 5.00e-05
  ✓ best saved (val_dice=0.488584) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 3/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.89it/s]
C08_lr=5e-5 | 3/30 VAL: 100%|██████████| 54/54 [00:01<00:00, 53.04it/s]

[C08_lr=5e-5] ep03 | TL 0.6916 | VL 0.7397 | VD 0.4593 | VI 0.4105 | LR 5.00e-05

C08_lr=5e-5 | 4/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 33.71it/s]
C08_lr=5e-5 | 4/30 VAL: 100%|██████████| 54/54 [00:01<00:00, 52.70it/s]

[C08_lr=5e-5] ep04 | TL 0.5486 | VL 0.6630 | VD 0.5199 | VI 0.4681 | LR 5.00e-05
  ✓ best saved (val_dice=0.519939) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 5/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.24it/s]
C08_lr=5e-5 | 5/30 VAL: 100%|██████████| 54/54 [00:01<00:00, 50.73it/s]

[C08_lr=5e-5] ep05 | TL 0.5038 | VL 0.6625 | VD 0.5332 | VI 0.4826 | LR 5.00e-05
  ✓ best saved (val_dice=0.533241) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.00it/s]
C08_lr=5e-5 | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.77it/s]

[C08_lr=5e-5] ep06 | TL 0.4016 | VL 0.6027 | VD 0.6153 | VI 0.5650 | LR 5.00e-05
  ✓ best saved (val_dice=0.615329) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.18it/s]
C08_lr=5e-5 | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.62it/s]

[C08_lr=5e-5] ep07 | TL 0.4082 | VL 0.6826 | VD 0.5796 | VI 0.5322 | LR 5.00e-05

C08_lr=5e-5 | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.11it/s]
C08_lr=5e-5 | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.15it/s]

[C08_lr=5e-5] ep08 | TL 0.3544 | VL 0.6028 | VD 0.6259 | VI 0.5760 | LR 5.00e-05
  ✓ best saved (val_dice=0.625942) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 9/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.67it/s]
C08_lr=5e-5 | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.13it/s]

[C08_lr=5e-5] ep09 | TL 0.3149 | VL 0.5727 | VD 0.6180 | VI 0.5729 | LR 5.00e-05

C08_lr=5e-5 | 10/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.99it/s]
C08_lr=5e-5 | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.08it/s]

[C08_lr=5e-5] ep10 | TL 0.2783 | VL 0.6947 | VD 0.5781 | VI 0.5292 | LR 5.00e-05

C08_lr=5e-5 | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.46it/s]
C08_lr=5e-5 | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.24it/s]

[C08_lr=5e-5] ep11 | TL 0.2887 | VL 0.6181 | VD 0.6147 | VI 0.5694 | LR 5.00e-05

C08_lr=5e-5 | 12/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.41it/s]
C08_lr=5e-5 | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.43it/s]

[C08_lr=5e-5] ep12 | TL 0.2587 | VL 0.5544 | VD 0.6282 | VI 0.5798 | LR 5.00e-05
  ✓ best saved (val_dice=0.628167) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 13/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.69it/s]
C08_lr=5e-5 | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.02it/s]

[C08_lr=5e-5] ep13 | TL 0.2543 | VL 0.5489 | VD 0.6166 | VI 0.5690 | LR 5.00e-05

C08_lr=5e-5 | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.27it/s]
C08_lr=5e-5 | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.12it/s]

[C08_lr=5e-5] ep14 | TL 0.2392 | VL 0.5935 | VD 0.6299 | VI 0.5867 | LR 5.00e-05
  ✓ best saved (val_dice=0.629944) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.46it/s]
C08_lr=5e-5 | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.62it/s]

[C08_lr=5e-5] ep15 | TL 0.2326 | VL 0.8032 | VD 0.6014 | VI 0.5447 | LR 5.00e-05

C08_lr=5e-5 | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.79it/s]
C08_lr=5e-5 | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.29it/s]

[C08_lr=5e-5] ep16 | TL 0.2127 | VL 0.5751 | VD 0.6466 | VI 0.5995 | LR 5.00e-05
  ✓ best saved (val_dice=0.646604) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 17/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.25it/s]
C08_lr=5e-5 | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.15it/s]

[C08_lr=5e-5] ep17 | TL 0.1856 | VL 0.5510 | VD 0.6316 | VI 0.5823 | LR 5.00e-05

C08_lr=5e-5 | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.03it/s]
C08_lr=5e-5 | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.02it/s]

[C08_lr=5e-5] ep18 | TL 0.2008 | VL 0.5758 | VD 0.6258 | VI 0.5767 | LR 5.00e-05

C08_lr=5e-5 | 19/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.88it/s]
C08_lr=5e-5 | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.69it/s]

[C08_lr=5e-5] ep19 | TL 0.1642 | VL 0.5933 | VD 0.6349 | VI 0.5914 | LR 5.00e-05

C08_lr=5e-5 | 20/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.36it/s]
C08_lr=5e-5 | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.90it/s]

[C08_lr=5e-5] ep20 | TL 0.1446 | VL 0.5424 | VD 0.6444 | VI 0.5980 | LR 5.00e-05

C08_lr=5e-5 | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.04it/s]
C08_lr=5e-5 | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.47it/s]

[C08_lr=5e-5] ep21 | TL 0.1413 | VL 0.6083 | VD 0.6359 | VI 0.5841 | LR 5.00e-05

C08_lr=5e-5 | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.36it/s]
C08_lr=5e-5 | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.50it/s]

[C08_lr=5e-5] ep22 | TL 0.1342 | VL 0.5615 | VD 0.6604 | VI 0.6153 | LR 5.00e-05
  ✓ best saved (val_dice=0.660400) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.07it/s]
C08_lr=5e-5 | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.32it/s]

[C08_lr=5e-5] ep23 | TL 0.1635 | VL 0.6124 | VD 0.6163 | VI 0.5639 | LR 5.00e-05

C08_lr=5e-5 | 24/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.15it/s]
C08_lr=5e-5 | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.24it/s]

[C08_lr=5e-5] ep24 | TL 0.1805 | VL 0.6000 | VD 0.6382 | VI 0.5920 | LR 5.00e-05

C08_lr=5e-5 | 25/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.50it/s]
C08_lr=5e-5 | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.83it/s]

[C08_lr=5e-5] ep25 | TL 0.1513 | VL 0.5945 | VD 0.6526 | VI 0.6070 | LR 5.00e-05

C08_lr=5e-5 | 26/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.65it/s]
C08_lr=5e-5 | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.49it/s]

[C08_lr=5e-5] ep26 | TL 0.1298 | VL 0.6605 | VD 0.6292 | VI 0.5836 | LR 5.00e-05

C08_lr=5e-5 | 27/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.81it/s]
C08_lr=5e-5 | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.68it/s]

[C08_lr=5e-5] ep27 | TL 0.1210 | VL 0.6126 | VD 0.6429 | VI 0.5967 | LR 5.00e-05

C08_lr=5e-5 | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.29it/s]
C08_lr=5e-5 | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.34it/s]

[C08_lr=5e-5] ep28 | TL 0.1305 | VL 0.6138 | VD 0.6686 | VI 0.6227 | LR 5.00e-05
  ✓ best saved (val_dice=0.668578) -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 29/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.10it/s]
C08_lr=5e-5 | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.23it/s]

[C08_lr=5e-5] ep29 | TL 0.1091 | VL 0.6020 | VD 0.6534 | VI 0.6096 | LR 5.00e-05

C08_lr=5e-5 | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.00it/s]
C08_lr=5e-5 | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.45it/s]

[C08_lr=5e-5] ep30 | TL 0.1137 | VL 0.6264 | VD 0.6670 | VI 0.6224 | LR 5.00e-05

C08_lr=5e-5 | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 68.46it/s]
C09_lr=2e-4 | 1/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.66it/s]
C09_lr=2e-4 | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.78it/s]

[C09_lr=2e-4] ep01 | TL 1.0242 | VL 1.7740 | VD 0.2548 | VI 0.2154 | LR 2.00e-04
  ✓ best saved (val_dice=0.254802) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 2/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.47it/s]
C09_lr=2e-4 | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.65it/s]

[C09_lr=2e-4] ep02 | TL 0.8931 | VL 0.8697 | VD 0.3792 | VI 0.3336 | LR 2.00e-04
  ✓ best saved (val_dice=0.379176) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 3/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.73it/s]
C09_lr=2e-4 | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.44it/s]

[C09_lr=2e-4] ep03 | TL 0.8340 | VL 1.1844 | VD 0.5403 | VI 0.4832 | LR 2.00e-04
  ✓ best saved (val_dice=0.540288) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 4/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.17it/s]
C09_lr=2e-4 | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.43it/s]

[C09_lr=2e-4] ep04 | TL 0.7308 | VL 0.8287 | VD 0.4874 | VI 0.4422 | LR 2.00e-04

C09_lr=2e-4 | 5/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.97it/s]
C09_lr=2e-4 | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.88it/s]

[C09_lr=2e-4] ep05 | TL 0.6926 | VL 0.8158 | VD 0.5574 | VI 0.5023 | LR 2.00e-04
  ✓ best saved (val_dice=0.557360) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 6/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.75it/s]
C09_lr=2e-4 | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.29it/s]

[C09_lr=2e-4] ep06 | TL 0.5581 | VL 1.2085 | VD 0.4326 | VI 0.3805 | LR 2.00e-04

C09_lr=2e-4 | 7/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.87it/s]
C09_lr=2e-4 | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.95it/s]

[C09_lr=2e-4] ep07 | TL 0.5467 | VL 1.4094 | VD 0.5835 | VI 0.5292 | LR 2.00e-04
  ✓ best saved (val_dice=0.583521) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 8/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.24it/s]
C09_lr=2e-4 | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.22it/s]

[C09_lr=2e-4] ep08 | TL 0.4697 | VL 0.7263 | VD 0.5600 | VI 0.5095 | LR 2.00e-04

C09_lr=2e-4 | 9/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.42it/s]
C09_lr=2e-4 | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.73it/s]

[C09_lr=2e-4] ep09 | TL 0.3823 | VL 0.6867 | VD 0.6164 | VI 0.5692 | LR 2.00e-04
  ✓ best saved (val_dice=0.616385) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.36it/s]
C09_lr=2e-4 | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.27it/s]

[C09_lr=2e-4] ep10 | TL 0.3752 | VL 0.6340 | VD 0.6453 | VI 0.5974 | LR 2.00e-04
  ✓ best saved (val_dice=0.645314) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.04it/s]
C09_lr=2e-4 | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.19it/s]

[C09_lr=2e-4] ep11 | TL 0.3901 | VL 0.9558 | VD 0.5379 | VI 0.4810 | LR 2.00e-04

C09_lr=2e-4 | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.30it/s]
C09_lr=2e-4 | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.50it/s]

[C09_lr=2e-4] ep12 | TL 0.3425 | VL 0.7039 | VD 0.5961 | VI 0.5540 | LR 2.00e-04

C09_lr=2e-4 | 13/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.50it/s]
C09_lr=2e-4 | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.44it/s]

[C09_lr=2e-4] ep13 | TL 0.3041 | VL 0.6787 | VD 0.6375 | VI 0.5868 | LR 2.00e-04

C09_lr=2e-4 | 14/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.42it/s]
C09_lr=2e-4 | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.08it/s]

[C09_lr=2e-4] ep14 | TL 0.3029 | VL 0.6303 | VD 0.6360 | VI 0.5921 | LR 2.00e-04

C09_lr=2e-4 | 15/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.57it/s]
C09_lr=2e-4 | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.91it/s]

[C09_lr=2e-4] ep15 | TL 0.2632 | VL 0.6427 | VD 0.5943 | VI 0.5417 | LR 2.00e-04

C09_lr=2e-4 | 16/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.84it/s]
C09_lr=2e-4 | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.07it/s]

[C09_lr=2e-4] ep16 | TL 0.2283 | VL 0.5595 | VD 0.6573 | VI 0.6105 | LR 2.00e-04
  ✓ best saved (val_dice=0.657311) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 17/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.00it/s]
C09_lr=2e-4 | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.89it/s]

[C09_lr=2e-4] ep17 | TL 0.1980 | VL 0.5567 | VD 0.6756 | VI 0.6306 | LR 2.00e-04
  ✓ best saved (val_dice=0.675642) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 18/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.93it/s]
C09_lr=2e-4 | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.12it/s]

[C09_lr=2e-4] ep18 | TL 0.2149 | VL 1.0611 | VD 0.6222 | VI 0.5704 | LR 2.00e-04

C09_lr=2e-4 | 19/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.58it/s]
C09_lr=2e-4 | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.82it/s]

[C09_lr=2e-4] ep19 | TL 0.1796 | VL 0.5588 | VD 0.6716 | VI 0.6260 | LR 2.00e-04

C09_lr=2e-4 | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.19it/s]
C09_lr=2e-4 | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.10it/s]

[C09_lr=2e-4] ep20 | TL 0.1513 | VL 0.6866 | VD 0.6461 | VI 0.6043 | LR 2.00e-04

C09_lr=2e-4 | 21/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.99it/s]
C09_lr=2e-4 | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.62it/s]

[C09_lr=2e-4] ep21 | TL 0.1840 | VL 0.6392 | VD 0.6266 | VI 0.5762 | LR 2.00e-04

C09_lr=2e-4 | 22/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.95it/s]
C09_lr=2e-4 | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.65it/s]

[C09_lr=2e-4] ep22 | TL 0.1601 | VL 0.7316 | VD 0.6062 | VI 0.5504 | LR 2.00e-04

C09_lr=2e-4 | 23/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.81it/s]
C09_lr=2e-4 | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.22it/s]

[C09_lr=2e-4] ep23 | TL 0.2180 | VL 0.8989 | VD 0.6002 | VI 0.5435 | LR 2.00e-04

C09_lr=2e-4 | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.19it/s]
C09_lr=2e-4 | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.16it/s]

[C09_lr=2e-4] ep24 | TL 0.2079 | VL 0.5963 | VD 0.6905 | VI 0.6436 | LR 2.00e-04
  ✓ best saved (val_dice=0.690541) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 25/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.93it/s]
C09_lr=2e-4 | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.28it/s]

[C09_lr=2e-4] ep25 | TL 0.1452 | VL 0.5219 | VD 0.7021 | VI 0.6595 | LR 2.00e-04
  ✓ best saved (val_dice=0.702100) -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.03it/s]
C09_lr=2e-4 | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.19it/s]

[C09_lr=2e-4] ep26 | TL 0.1398 | VL 0.8662 | VD 0.6744 | VI 0.6252 | LR 2.00e-04

C09_lr=2e-4 | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.05it/s]
C09_lr=2e-4 | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.61it/s]

[C09_lr=2e-4] ep27 | TL 0.1558 | VL 0.6510 | VD 0.6618 | VI 0.6163 | LR 2.00e-04

C09_lr=2e-4 | 28/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.83it/s]
C09_lr=2e-4 | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.60it/s]

[C09_lr=2e-4] ep28 | TL 0.1598 | VL 0.6091 | VD 0.6894 | VI 0.6441 | LR 2.00e-04

C09_lr=2e-4 | 29/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 34.54it/s]
C09_lr=2e-4 | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.36it/s]

[C09_lr=2e-4] ep29 | TL 0.1161 | VL 0.5532 | VD 0.6928 | VI 0.6515 | LR 2.00e-04

C09_lr=2e-4 | 30/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.98it/s]
C09_lr=2e-4 | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.82it/s]

[C09_lr=2e-4] ep30 | TL 0.1306 | VL 0.6449 | VD 0.6756 | VI 0.6279 | LR 2.00e-04

C09_lr=2e-4 | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 67.64it/s]

Saved runs under: /content/drive/MyDrive/burned_area_outputs_unet
C00_BASE -> /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE
  best: /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C00_BASE/history.csv
  best_epoch: 27 | test_dice: 0.6421 | test_iou: 0.6005
C01_loss=BCE -> /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE
  best: /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C01_loss=BCE/history.csv
  best_epoch: 22 | test_dice: 0.6297 | test_iou: 0.5899
C02_loss=Focal+Dice -> /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice
  best: /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C02_loss=Focal+Dice/history.csv
  best_epoch: 29 | test_dice: 0.6484 | test_iou: 0.6066
C03_sched=plateau -> /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau
  best: /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C03_sched=plateau/history.csv
  best_epoch: 13 | test_dice: 0.6244 | test_iou: 0.5835
C04_amp=on -> /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on
  best: /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C04_amp=on/history.csv
  best_epoch: 29 | test_dice: 0.6464 | test_iou: 0.6052
C05_clip=1.0 -> /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0
  best: /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C05_clip=1.0/history.csv
  best_epoch: 23 | test_dice: 0.6533 | test_iou: 0.6101
C06_freeze=2ep -> /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep
  best: /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C06_freeze=2ep/history.csv
  best_epoch: 30 | test_dice: 0.6521 | test_iou: 0.6135
C07_ES=on -> /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on
  best: /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C07_ES=on/history.csv
  best_epoch: 11 | test_dice: 0.6212 | test_iou: 0.5802
C08_lr=5e-5 -> /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5
  best: /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C08_lr=5e-5/history.csv
  best_epoch: 28 | test_dice: 0.6077 | test_iou: 0.5639
C09_lr=2e-4 -> /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4
  best: /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_unet/C09_lr=2e-4/history.csv
  best_epoch: 25 | test_dice: 0.6545 | test_iou: 0.6128

In [ ]:
print("train batches:", len(train_loader))
print("val batches:", len(val_loader))
print("test batches:", len(test_loader))

# mümkünse dataset uzunlukları
print("train n:", len(train_loader.dataset))
print("val n:", len(val_loader.dataset))
print("test n:", len(test_loader.dataset))

train batches: 252
val batches: 54
test batches: 54
train n: 2011
val n: 431
test n: 432

In [ ]:
train_ids = set(getattr(train_loader.dataset, "files", []))
val_ids   = set(getattr(val_loader.dataset, "files", []))
test_ids  = set(getattr(test_loader.dataset, "files", []))

print("train∩val:", len(train_ids & val_ids))
print("train∩test:", len(train_ids & test_ids))
print("val∩test:", len(val_ids & test_ids))

train∩val: 0
train∩test: 0
val∩test: 0

In [ ]:
x, y = next(iter(train_loader))
print("y min/max:", y.min().item(), y.max().item())
print("unique sample:", torch.unique(y[:1]).cpu()[:10])

y min/max: 0 1
unique sample: tensor([0, 1])

In [ ]:
import torch

def empty_mask_stats(loader, name=""):
    empty = 0
    total = 0
    pos_pixels = 0
    all_pixels = 0

    for x, y in loader:
        # y: (B,H,W) varsayıyorum
        y = y.float()
        # boş mask: tüm pikseller 0
        is_empty = (y.sum(dim=(1,2)) == 0)
        empty += is_empty.sum().item()
        total += y.size(0)

        pos_pixels += y.sum().item()
        all_pixels += y.numel()

    print(f"{name} empty masks: {empty}/{total} = {empty/total:.3f}")
    print(f"{name} foreground pixel ratio: {pos_pixels/all_pixels:.6f}")

empty_mask_stats(val_loader, "VAL")
empty_mask_stats(test_loader, "TEST")

VAL empty masks: 73/431 = 0.169
VAL foreground pixel ratio: 0.474912
TEST empty masks: 88/432 = 0.204
TEST foreground pixel ratio: 0.421664

In [ ]:
import torch

@torch.no_grad()
def baseline_all_zero(loader, thr=0.5, name=""):
    eps=1e-7
    dices=[]
    ious=[]
    for x,y in loader:
        y = y.unsqueeze(1).float().to(device)
        pred = torch.zeros_like(y)  # her şeyi background tahmin et
        inter = (pred*y).sum(dim=(1,2,3))

        union_d = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3))
        dice = ((2*inter + eps) / (union_d + eps)).mean().item()

        union_i = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3)) - inter
        iou = ((inter + eps) / (union_i + eps)).mean().item()

        dices.append(dice); ious.append(iou)

    print(f"{name} ALL-ZERO baseline | Dice={sum(dices)/len(dices):.4f} IoU={sum(ious)/len(ious):.4f}")

baseline_all_zero(val_loader, name="VAL")
baseline_all_zero(test_loader, name="TEST")

VAL ALL-ZERO baseline | Dice=0.1690 IoU=0.1690
TEST ALL-ZERO baseline | Dice=0.2037 IoU=0.2037

# **Training DeepLabv3**

In [ ]:
# ============================================================
# DeepLabV3+ CONTROLLED ABLATION PIPELINE + SAVE EVERYTHING (Drive)
# (same structure as your U-Net code, just model changed)
# ============================================================
import os, copy, random, math, json
import numpy as np
import torch
import segmentation_models_pytorch as smp
from tqdm import tqdm

# === CHANGE THIS: where to save runs in your Drive ===
RUNS_DIR = "/content/drive/MyDrive/burned_area_outputs_deeplabv3"
os.makedirs(RUNS_DIR, exist_ok=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ----------------------------
# Utils
# ----------------------------
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ----------------------------
# Model: DeepLabV3+
# ----------------------------
def build_model(encoder_name="resnet18", encoder_weights="imagenet"):
    return smp.DeepLabV3Plus(
        encoder_name=encoder_name,
        encoder_weights=encoder_weights,
        in_channels=3,
        classes=1,
        activation=None
    )


# ----------------------------
# Loss
# ----------------------------
def make_loss(loss_cfg):
    name = loss_cfg["name"]

    if name == "bce":
        bce = torch.nn.BCEWithLogitsLoss()
        return lambda logits, y: bce(logits, y), "BCE"

    if name == "bce_dice":
        bce = torch.nn.BCEWithLogitsLoss()
        dice = smp.losses.DiceLoss(mode="binary")
        w_bce  = loss_cfg.get("w_bce", 1.0)
        w_dice = loss_cfg.get("w_dice", 1.0)
        return (lambda logits, y: w_bce*bce(logits, y) + w_dice*dice(logits, y),
                f"BCE+Dice({w_bce},{w_dice})")

    if name == "focal_dice":
        alpha = loss_cfg.get("alpha", 0.8)
        gamma = loss_cfg.get("gamma", 2.0)
        focal = smp.losses.FocalLoss(mode="binary", alpha=alpha, gamma=gamma)
        dice  = smp.losses.DiceLoss(mode="binary")
        w_focal = loss_cfg.get("w_focal", 1.0)
        w_dice  = loss_cfg.get("w_dice", 1.0)
        return (lambda logits, y: w_focal*focal(logits, y) + w_dice*dice(logits, y),
                f"Focal(a={alpha},g={gamma})+Dice")

    raise ValueError(f"Unknown loss: {name}")


@torch.no_grad()
def dice_iou_from_logits(logits, y, thr=0.5, eps=1e-7):
    probs = torch.sigmoid(logits)
    pred = (probs > thr).float()

    inter = (pred * y).sum(dim=(1,2,3))

    union_d = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3))
    dice = ((2*inter + eps) / (union_d + eps)).mean().item()

    union_i = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3)) - inter
    iou = ((inter + eps) / (union_i + eps)).mean().item()

    return dice, iou


def run_epoch(model, loader, loss_fn, optimizer=None, use_amp=False, scaler=None, grad_clip=None, desc=""):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    tot_loss = 0.0
    tot_dice = 0.0
    tot_iou  = 0.0
    n = 0

    context = torch.enable_grad() if is_train else torch.no_grad()
    with context:
        for x, y in tqdm(loader, desc=desc):
            x = x.to(device, non_blocking=True)
            y = y.unsqueeze(1).float().to(device, non_blocking=True)

            if is_train:
                optimizer.zero_grad(set_to_none=True)

            if use_amp:
                with torch.cuda.amp.autocast(True):
                    logits = model(x)
                    loss = loss_fn(logits, y)
            else:
                logits = model(x)
                loss = loss_fn(logits, y)

            if is_train:
                if use_amp:
                    scaler.scale(loss).backward()
                    if grad_clip is not None:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    if grad_clip is not None:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
                    optimizer.step()

            dice, iou = dice_iou_from_logits(logits, y)

            tot_loss += float(loss.item())
            tot_dice += dice
            tot_iou  += iou
            n += 1

    if n == 0:
        return math.nan, math.nan, math.nan
    return tot_loss/n, tot_dice/n, tot_iou/n


def save_csv(path, rows, header):
    with open(path, "w") as f:
        f.write(",".join(header) + "\n")
        for r in rows:
            f.write(",".join(str(r.get(h,"")) for h in header) + "\n")


# ----------------------------
# Train one condition
# ----------------------------
def train_one(cfg):
    set_seed(cfg.get("seed", 42))

    run_dir = os.path.join(RUNS_DIR, cfg["name"])
    os.makedirs(run_dir, exist_ok=True)

    with open(os.path.join(run_dir, "config.json"), "w") as f:
        json.dump(cfg, f, indent=2)

    best_path = os.path.join(run_dir, "best.pth")
    last_path = os.path.join(run_dir, "last.pth")
    hist_path = os.path.join(run_dir, "history.csv")

    model = build_model(cfg["encoder"], cfg["weights"]).to(device)
    loss_fn, _ = make_loss(cfg["loss"])

    opt = cfg["optimizer"]["name"]
    lr  = cfg["optimizer"]["lr"]
    wd  = cfg["optimizer"].get("weight_decay", 0.0)
    if opt == "adam":
        optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
    elif opt == "adamw":
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
    else:
        raise ValueError(opt)

    scheduler = None
    if cfg.get("scheduler", None):
        sc = cfg["scheduler"]
        if sc["name"] == "plateau":
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                optimizer, mode=sc.get("mode","min"),
                factor=sc.get("factor",0.5),
                patience=sc.get("patience",2),
                min_lr=sc.get("min_lr",1e-6),
            )
        elif sc["name"] == "cosine":
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer, T_max=sc.get("T_max", cfg["epochs"])
            )
        else:
            raise ValueError(sc["name"])

    use_amp = bool(cfg.get("amp", True)) and torch.cuda.is_available()
    scaler = torch.cuda.amp.GradScaler(enabled=use_amp) if use_amp else None

    freeze_epochs = int(cfg.get("freeze_epochs", 0))
    if freeze_epochs > 0:
        for p in model.encoder.parameters():
            p.requires_grad = False

    es = cfg.get("early_stopping", {"enabled": False})
    es_enabled = bool(es.get("enabled", False))
    monitor = es.get("monitor","val_dice")  # or val_loss
    mode    = es.get("mode","max")          # max for dice, min for loss
    patience = int(es.get("patience", 6))

    best = -1e9 if mode=="max" else 1e9
    best_epoch = -1
    bad = 0

    grad_clip = cfg.get("grad_clip", None)
    plateau_on = cfg.get("plateau_on","val_loss")

    history = []

    for epoch in range(1, cfg["epochs"]+1):
        if freeze_epochs > 0 and epoch == freeze_epochs + 1:
            for p in model.encoder.parameters():
                p.requires_grad = True

            if cfg.get("reset_opt_on_unfreeze", True):
                new_lr = cfg.get("lr_unfreeze", lr)
                if opt == "adam":
                    optimizer = torch.optim.Adam(model.parameters(), lr=new_lr, weight_decay=wd)
                else:
                    optimizer = torch.optim.AdamW(model.parameters(), lr=new_lr, weight_decay=wd)

                if cfg.get("scheduler", None):
                    sc = cfg["scheduler"]
                    if sc["name"] == "plateau":
                        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                            optimizer, mode=sc.get("mode","min"),
                            factor=sc.get("factor",0.5),
                            patience=sc.get("patience",2),
                            min_lr=sc.get("min_lr",1e-6),
                        )
                    elif sc["name"] == "cosine":
                        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                            optimizer, T_max=sc.get("T_max", cfg["epochs"])
                        )

                scaler = torch.cuda.amp.GradScaler(enabled=use_amp) if use_amp else None

        tl, td, ti = run_epoch(
            model, train_loader, loss_fn,
            optimizer=optimizer,
            use_amp=use_amp, scaler=scaler,
            grad_clip=grad_clip,
            desc=f"{cfg['name']} | {epoch}/{cfg['epochs']} TRAIN"
        )

        vl, vd, vi = run_epoch(
            model, val_loader, loss_fn,
            optimizer=None,
            use_amp=use_amp, scaler=scaler,
            desc=f"{cfg['name']} | {epoch}/{cfg['epochs']} VAL"
        )

        if scheduler is not None:
            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
                metric = vl if plateau_on=="val_loss" else (1.0 - vd)
                scheduler.step(metric)
            else:
                scheduler.step()

        lr_now = optimizer.param_groups[0]["lr"]
        row = {
            "epoch": epoch,
            "lr": lr_now,
            "train_loss": tl,
            "train_dice": td,
            "train_iou": ti,
            "val_loss": vl,
            "val_dice": vd,
            "val_iou": vi,
        }
        history.append(row)

        print(f"[{cfg['name']}] ep{epoch:02d} | TL {tl:.4f} | VL {vl:.4f} | VD {vd:.4f} | VI {vi:.4f} | LR {lr_now:.2e}")

        torch.save(
            {"epoch": epoch, "model": model.state_dict(), "cfg": cfg, "history": history},
            last_path
        )

        current = vd if monitor=="val_dice" else vl
        improved = (current > best) if mode=="max" else (current < best)

        if improved:
            best = current
            best_epoch = epoch
            bad = 0
            torch.save(
                {"epoch": epoch, "model": model.state_dict(), "cfg": cfg, "best": best, "history": history},
                best_path
            )
            print(f"  ✓ best saved ({monitor}={best:.6f}) -> {best_path}")
        else:
            if es_enabled:
                bad += 1
                if bad >= patience:
                    print(f"⛔ early stop (best ep={best_epoch}, best {monitor}={best:.6f})")
                    break

    header = ["epoch","lr","train_loss","train_dice","train_iou","val_loss","val_dice","val_iou"]
    save_csv(hist_path, history, header)

    ckpt_path = best_path if os.path.exists(best_path) else last_path
    ckpt = torch.load(ckpt_path, map_location=device)
    model.load_state_dict(ckpt["model"])
    model.eval()

    test_loss, test_dice, test_iou = run_epoch(
        model, test_loader, loss_fn,
        optimizer=None,
        use_amp=use_amp, scaler=scaler,
        desc=f"{cfg['name']} | TEST ({'best' if ckpt_path==best_path else 'last'})"
    )

    summary = {
        "name": cfg["name"],
        "run_dir": run_dir,
        "best_path": best_path,
        "last_path": last_path,
        "hist_path": hist_path,
        "best_epoch": ckpt.get("epoch", None),
        "best_metric": ckpt.get("best", None),
        "test_loss": test_loss,
        "test_dice": test_dice,
        "test_iou": test_iou,
    }
    return summary


# ----------------------------
# Conditions (same idea)
# ----------------------------
BASE = {
    "name": "C00_BASE",
    "seed": 42,
    "encoder": "resnet18",
    "weights": "imagenet",
    "epochs": 30,
    "loss": {"name": "bce_dice", "w_bce": 1.0, "w_dice": 1.0},
    "optimizer": {"name": "adamw", "lr": 1e-4, "weight_decay": 1e-4},
    "scheduler": None,
    "plateau_on": "val_loss",
    "amp": False,
    "grad_clip": None,
    "freeze_epochs": 0,
    "reset_opt_on_unfreeze": True,
    "lr_unfreeze": 1e-4,
    "early_stopping": {"enabled": False, "monitor":"val_dice", "mode":"max", "patience":6},
}

ABLATIONS = [
    ("loss", {"name": "bce"}, "loss=BCE"),
    ("loss", {"name": "focal_dice", "alpha":0.8, "gamma":2.0}, "loss=Focal+Dice"),
    ("scheduler", {"name":"plateau","mode":"min","factor":0.5,"patience":2,"min_lr":1e-6}, "sched=plateau"),
    ("amp", True, "amp=on"),
    ("grad_clip", 1.0, "clip=1.0"),
    ("freeze_epochs", 2, "freeze=2ep"),
    ("early_stopping", {"enabled": True, "monitor":"val_dice", "mode":"max", "patience":6}, "ES=on"),
    ("optimizer.lr", 5e-5, "lr=5e-5"),
    ("optimizer.lr", 2e-4, "lr=2e-4"),
]

def apply_change(cfg, path, value):
    keys = path.split(".")
    ref = cfg
    for k in keys[:-1]:
        ref = ref[k]
    ref[keys[-1]] = value

def build_conditions(base_cfg, ablations):
    conds = [copy.deepcopy(base_cfg)]
    for i, (path, val, tag) in enumerate(ablations, start=1):
        c = copy.deepcopy(base_cfg)
        c["name"] = f"C{i:02d}_{tag}"
        apply_change(c, path, val)
        conds.append(c)
    return conds

CONDITIONS_deeplab = build_conditions(BASE, ABLATIONS)


# ----------------------------
# RUN ALL
# ----------------------------
summaries = []
for cfg in CONDITIONS_deeplab:
    summaries.append(train_one(cfg))

print("\n\nSaved runs under:", RUNS_DIR)
for s in summaries:
    print(s["name"], "->", s["run_dir"])
    print("  best:", s["best_path"])
    print("  last:", s["last_path"])
    print("  hist:", s["hist_path"])
    print("  best_epoch:", s["best_epoch"], "| test_dice:", f"{s['test_dice']:.4f}", "| test_iou:", f"{s['test_iou']:.4f}")

C00_BASE | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.22it/s]
C00_BASE | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.36it/s]

[C00_BASE] ep01 | TL 0.9512 | VL 1.1055 | VD 0.5709 | VI 0.5183 | LR 1.00e-04
  ✓ best saved (val_dice=0.570946) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.68it/s]
C00_BASE | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.29it/s]

[C00_BASE] ep02 | TL 0.7811 | VL 0.9346 | VD 0.5035 | VI 0.4663 | LR 1.00e-04

C00_BASE | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.41it/s]
C00_BASE | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.80it/s]

[C00_BASE] ep03 | TL 0.6910 | VL 0.7762 | VD 0.5499 | VI 0.5027 | LR 1.00e-04

C00_BASE | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.05it/s]
C00_BASE | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.28it/s]

[C00_BASE] ep04 | TL 0.5669 | VL 0.7135 | VD 0.6263 | VI 0.5743 | LR 1.00e-04
  ✓ best saved (val_dice=0.626309) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 5/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.24it/s]
C00_BASE | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.35it/s]

[C00_BASE] ep05 | TL 0.5136 | VL 0.6264 | VD 0.6352 | VI 0.5864 | LR 1.00e-04
  ✓ best saved (val_dice=0.635238) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 6/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.19it/s]
C00_BASE | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.24it/s]

[C00_BASE] ep06 | TL 0.4644 | VL 0.5912 | VD 0.6177 | VI 0.5712 | LR 1.00e-04

C00_BASE | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.55it/s]
C00_BASE | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.75it/s]

[C00_BASE] ep07 | TL 0.4354 | VL 0.6165 | VD 0.6471 | VI 0.5958 | LR 1.00e-04
  ✓ best saved (val_dice=0.647117) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.72it/s]
C00_BASE | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.57it/s]

[C00_BASE] ep08 | TL 0.3967 | VL 0.6054 | VD 0.6429 | VI 0.5897 | LR 1.00e-04

C00_BASE | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.76it/s]
C00_BASE | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.91it/s]

[C00_BASE] ep09 | TL 0.3689 | VL 0.5410 | VD 0.6409 | VI 0.5940 | LR 1.00e-04

C00_BASE | 10/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.65it/s]
C00_BASE | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.93it/s]

[C00_BASE] ep10 | TL 0.3056 | VL 0.5011 | VD 0.6484 | VI 0.6029 | LR 1.00e-04
  ✓ best saved (val_dice=0.648369) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 11/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.80it/s]
C00_BASE | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.53it/s]

[C00_BASE] ep11 | TL 0.3019 | VL 0.6229 | VD 0.6487 | VI 0.6019 | LR 1.00e-04
  ✓ best saved (val_dice=0.648708) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 12/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.42it/s]
C00_BASE | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.63it/s]

[C00_BASE] ep12 | TL 0.2725 | VL 0.4918 | VD 0.6851 | VI 0.6407 | LR 1.00e-04
  ✓ best saved (val_dice=0.685076) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 13/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.11it/s]
C00_BASE | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.04it/s]

[C00_BASE] ep13 | TL 0.2601 | VL 0.8431 | VD 0.5932 | VI 0.5360 | LR 1.00e-04

C00_BASE | 14/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.93it/s]
C00_BASE | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.42it/s]

[C00_BASE] ep14 | TL 0.2782 | VL 0.5843 | VD 0.6354 | VI 0.5911 | LR 1.00e-04

C00_BASE | 15/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.81it/s]
C00_BASE | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.09it/s]

[C00_BASE] ep15 | TL 0.2349 | VL 0.5108 | VD 0.6768 | VI 0.6274 | LR 1.00e-04

C00_BASE | 16/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.55it/s]
C00_BASE | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.29it/s]

[C00_BASE] ep16 | TL 0.2049 | VL 0.5228 | VD 0.6748 | VI 0.6303 | LR 1.00e-04

C00_BASE | 17/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.51it/s]
C00_BASE | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.89it/s]

[C00_BASE] ep17 | TL 0.2286 | VL 0.5292 | VD 0.6741 | VI 0.6315 | LR 1.00e-04

C00_BASE | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.53it/s]
C00_BASE | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.88it/s]

[C00_BASE] ep18 | TL 0.1961 | VL 0.5095 | VD 0.6938 | VI 0.6504 | LR 1.00e-04
  ✓ best saved (val_dice=0.693778) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | 19/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.51it/s]
C00_BASE | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.21it/s]

[C00_BASE] ep19 | TL 0.2246 | VL 0.6287 | VD 0.6510 | VI 0.6079 | LR 1.00e-04

C00_BASE | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.02it/s]
C00_BASE | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.46it/s]

[C00_BASE] ep20 | TL 0.1993 | VL 0.5016 | VD 0.6651 | VI 0.6222 | LR 1.00e-04

C00_BASE | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.72it/s]
C00_BASE | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.20it/s]

[C00_BASE] ep21 | TL 0.1703 | VL 0.4579 | VD 0.6728 | VI 0.6288 | LR 1.00e-04

C00_BASE | 22/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.01it/s]
C00_BASE | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.09it/s]

[C00_BASE] ep22 | TL 0.1408 | VL 0.5343 | VD 0.6805 | VI 0.6390 | LR 1.00e-04

C00_BASE | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.44it/s]
C00_BASE | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.13it/s]

[C00_BASE] ep23 | TL 0.1552 | VL 0.5300 | VD 0.6618 | VI 0.6130 | LR 1.00e-04

C00_BASE | 24/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.47it/s]
C00_BASE | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.13it/s]

[C00_BASE] ep24 | TL 0.1636 | VL 1.1967 | VD 0.5122 | VI 0.4763 | LR 1.00e-04

C00_BASE | 25/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.84it/s]
C00_BASE | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.44it/s]

[C00_BASE] ep25 | TL 0.1556 | VL 0.6158 | VD 0.6427 | VI 0.5990 | LR 1.00e-04

C00_BASE | 26/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.98it/s]
C00_BASE | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.78it/s]

[C00_BASE] ep26 | TL 0.1414 | VL 0.4958 | VD 0.6758 | VI 0.6327 | LR 1.00e-04

C00_BASE | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.95it/s]
C00_BASE | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.71it/s]

[C00_BASE] ep27 | TL 0.1168 | VL 0.4957 | VD 0.6934 | VI 0.6493 | LR 1.00e-04

C00_BASE | 28/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.99it/s]
C00_BASE | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.33it/s]

[C00_BASE] ep28 | TL 0.1351 | VL 0.5758 | VD 0.6644 | VI 0.6248 | LR 1.00e-04

C00_BASE | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.39it/s]
C00_BASE | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.44it/s]

[C00_BASE] ep29 | TL 0.1132 | VL 1.0707 | VD 0.5392 | VI 0.4850 | LR 1.00e-04

C00_BASE | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.27it/s]
C00_BASE | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.90it/s]

[C00_BASE] ep30 | TL 0.1256 | VL 0.4991 | VD 0.7048 | VI 0.6632 | LR 1.00e-04
  ✓ best saved (val_dice=0.704804) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth

C00_BASE | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 70.12it/s]
C01_loss=BCE | 1/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.91it/s]
C01_loss=BCE | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.11it/s]

[C01_loss=BCE] ep01 | TL 0.5415 | VL 0.9708 | VD 0.5665 | VI 0.5117 | LR 1.00e-04
  ✓ best saved (val_dice=0.566499) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.41it/s]
C01_loss=BCE | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.74it/s]

[C01_loss=BCE] ep02 | TL 0.4510 | VL 0.4457 | VD 0.5278 | VI 0.4918 | LR 1.00e-04

C01_loss=BCE | 3/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 46.79it/s]
C01_loss=BCE | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.93it/s]

[C01_loss=BCE] ep03 | TL 0.3960 | VL 0.3935 | VD 0.5970 | VI 0.5531 | LR 1.00e-04
  ✓ best saved (val_dice=0.597002) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 46.26it/s]
C01_loss=BCE | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.55it/s]

[C01_loss=BCE] ep04 | TL 0.3251 | VL 0.5188 | VD 0.6149 | VI 0.5614 | LR 1.00e-04
  ✓ best saved (val_dice=0.614878) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 5/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.64it/s]
C01_loss=BCE | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.10it/s]

[C01_loss=BCE] ep05 | TL 0.3051 | VL 0.4029 | VD 0.6025 | VI 0.5579 | LR 1.00e-04

C01_loss=BCE | 6/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.25it/s]
C01_loss=BCE | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.62it/s]

[C01_loss=BCE] ep06 | TL 0.2799 | VL 0.3448 | VD 0.6243 | VI 0.5810 | LR 1.00e-04
  ✓ best saved (val_dice=0.624314) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.25it/s]
C01_loss=BCE | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.81it/s]

[C01_loss=BCE] ep07 | TL 0.2494 | VL 0.5846 | VD 0.5400 | VI 0.4972 | LR 1.00e-04

C01_loss=BCE | 8/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.53it/s]
C01_loss=BCE | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.64it/s]

[C01_loss=BCE] ep08 | TL 0.2287 | VL 0.3357 | VD 0.6400 | VI 0.5962 | LR 1.00e-04
  ✓ best saved (val_dice=0.639956) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 9/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.65it/s]
C01_loss=BCE | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.12it/s]

[C01_loss=BCE] ep09 | TL 0.2110 | VL 0.3206 | VD 0.6290 | VI 0.5816 | LR 1.00e-04

C01_loss=BCE | 10/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.11it/s]
C01_loss=BCE | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.52it/s]

[C01_loss=BCE] ep10 | TL 0.1813 | VL 0.3474 | VD 0.6303 | VI 0.5790 | LR 1.00e-04

C01_loss=BCE | 11/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.38it/s]
C01_loss=BCE | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.70it/s]

[C01_loss=BCE] ep11 | TL 0.1739 | VL 0.5276 | VD 0.5782 | VI 0.5320 | LR 1.00e-04

C01_loss=BCE | 12/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.85it/s]
C01_loss=BCE | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.78it/s]

[C01_loss=BCE] ep12 | TL 0.1639 | VL 0.7701 | VD 0.6241 | VI 0.5722 | LR 1.00e-04

C01_loss=BCE | 13/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.34it/s]
C01_loss=BCE | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.36it/s]

[C01_loss=BCE] ep13 | TL 0.1742 | VL 0.3341 | VD 0.6500 | VI 0.6001 | LR 1.00e-04
  ✓ best saved (val_dice=0.650003) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 14/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.11it/s]
C01_loss=BCE | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.01it/s]

[C01_loss=BCE] ep14 | TL 0.1563 | VL 0.2920 | VD 0.6600 | VI 0.6148 | LR 1.00e-04
  ✓ best saved (val_dice=0.660003) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 15/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.65it/s]
C01_loss=BCE | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.83it/s]

[C01_loss=BCE] ep15 | TL 0.1280 | VL 0.3367 | VD 0.6549 | VI 0.6075 | LR 1.00e-04

C01_loss=BCE | 16/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.30it/s]
C01_loss=BCE | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.60it/s]

[C01_loss=BCE] ep16 | TL 0.1353 | VL 0.3578 | VD 0.6284 | VI 0.5814 | LR 1.00e-04

C01_loss=BCE | 17/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.73it/s]
C01_loss=BCE | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.64it/s]

[C01_loss=BCE] ep17 | TL 0.1269 | VL 0.3195 | VD 0.6650 | VI 0.6193 | LR 1.00e-04
  ✓ best saved (val_dice=0.664979) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 18/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.35it/s]
C01_loss=BCE | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.61it/s]

[C01_loss=BCE] ep18 | TL 0.1053 | VL 0.3207 | VD 0.6743 | VI 0.6306 | LR 1.00e-04
  ✓ best saved (val_dice=0.674262) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 19/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.84it/s]
C01_loss=BCE | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.21it/s]

[C01_loss=BCE] ep19 | TL 0.1287 | VL 0.5401 | VD 0.6092 | VI 0.5590 | LR 1.00e-04

C01_loss=BCE | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.04it/s]
C01_loss=BCE | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.57it/s]

[C01_loss=BCE] ep20 | TL 0.1155 | VL 0.3188 | VD 0.6743 | VI 0.6286 | LR 1.00e-04
  ✓ best saved (val_dice=0.674327) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.60it/s]
C01_loss=BCE | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.68it/s]

[C01_loss=BCE] ep21 | TL 0.1018 | VL 0.3466 | VD 0.6495 | VI 0.6069 | LR 1.00e-04

C01_loss=BCE | 22/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.17it/s]
C01_loss=BCE | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.20it/s]

[C01_loss=BCE] ep22 | TL 0.0924 | VL 0.3410 | VD 0.6659 | VI 0.6227 | LR 1.00e-04

C01_loss=BCE | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.70it/s]
C01_loss=BCE | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.52it/s]

[C01_loss=BCE] ep23 | TL 0.0926 | VL 0.4850 | VD 0.5976 | VI 0.5534 | LR 1.00e-04

C01_loss=BCE | 24/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 45.76it/s]
C01_loss=BCE | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.09it/s]

[C01_loss=BCE] ep24 | TL 0.1411 | VL 0.9907 | VD 0.3605 | VI 0.3150 | LR 1.00e-04

C01_loss=BCE | 25/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.06it/s]
C01_loss=BCE | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.57it/s]

[C01_loss=BCE] ep25 | TL 0.1032 | VL 0.3013 | VD 0.6657 | VI 0.6232 | LR 1.00e-04

C01_loss=BCE | 26/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 46.51it/s]
C01_loss=BCE | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.26it/s]

[C01_loss=BCE] ep26 | TL 0.0868 | VL 0.3098 | VD 0.6551 | VI 0.6098 | LR 1.00e-04

C01_loss=BCE | 27/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.50it/s]
C01_loss=BCE | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.88it/s]

[C01_loss=BCE] ep27 | TL 0.0787 | VL 0.3380 | VD 0.6906 | VI 0.6494 | LR 1.00e-04
  ✓ best saved (val_dice=0.690566) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | 28/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 46.58it/s]
C01_loss=BCE | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 77.08it/s]

[C01_loss=BCE] ep28 | TL 0.0910 | VL 0.3573 | VD 0.6493 | VI 0.6026 | LR 1.00e-04

C01_loss=BCE | 29/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.24it/s]
C01_loss=BCE | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.83it/s]

[C01_loss=BCE] ep29 | TL 0.0696 | VL 0.3800 | VD 0.6774 | VI 0.6354 | LR 1.00e-04

C01_loss=BCE | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.60it/s]
C01_loss=BCE | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.64it/s]

[C01_loss=BCE] ep30 | TL 0.0656 | VL 0.3324 | VD 0.6932 | VI 0.6530 | LR 1.00e-04
  ✓ best saved (val_dice=0.693226) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth

C01_loss=BCE | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 72.99it/s]
C02_loss=Focal+Dice | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.85it/s]
C02_loss=Focal+Dice | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.59it/s]

[C02_loss=Focal+Dice] ep01 | TL 0.4670 | VL 0.4266 | VD 0.5566 | VI 0.5046 | LR 1.00e-04
  ✓ best saved (val_dice=0.556573) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.98it/s]
C02_loss=Focal+Dice | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.09it/s]

[C02_loss=Focal+Dice] ep02 | TL 0.4066 | VL 0.7159 | VD 0.4305 | VI 0.3964 | LR 1.00e-04

C02_loss=Focal+Dice | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.95it/s]
C02_loss=Focal+Dice | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.69it/s]

[C02_loss=Focal+Dice] ep03 | TL 0.3645 | VL 0.3635 | VD 0.6040 | VI 0.5494 | LR 1.00e-04
  ✓ best saved (val_dice=0.604027) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.23it/s]
C02_loss=Focal+Dice | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.29it/s]

[C02_loss=Focal+Dice] ep04 | TL 0.3076 | VL 0.3374 | VD 0.6221 | VI 0.5701 | LR 1.00e-04
  ✓ best saved (val_dice=0.622076) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.54it/s]
C02_loss=Focal+Dice | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.78it/s]

[C02_loss=Focal+Dice] ep05 | TL 0.2803 | VL 0.5041 | VD 0.5606 | VI 0.5228 | LR 1.00e-04

C02_loss=Focal+Dice | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.09it/s]
C02_loss=Focal+Dice | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.03it/s]

[C02_loss=Focal+Dice] ep06 | TL 0.2532 | VL 0.4535 | VD 0.5853 | VI 0.5393 | LR 1.00e-04

C02_loss=Focal+Dice | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.07it/s]
C02_loss=Focal+Dice | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.46it/s]

[C02_loss=Focal+Dice] ep07 | TL 0.2451 | VL 0.3172 | VD 0.6188 | VI 0.5646 | LR 1.00e-04

C02_loss=Focal+Dice | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.38it/s]
C02_loss=Focal+Dice | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.69it/s]

[C02_loss=Focal+Dice] ep08 | TL 0.2244 | VL 0.3304 | VD 0.6386 | VI 0.5855 | LR 1.00e-04
  ✓ best saved (val_dice=0.638640) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 9/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.64it/s]
C02_loss=Focal+Dice | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.44it/s]

[C02_loss=Focal+Dice] ep09 | TL 0.2160 | VL 0.3870 | VD 0.6195 | VI 0.5705 | LR 1.00e-04

C02_loss=Focal+Dice | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.56it/s]
C02_loss=Focal+Dice | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.06it/s]

[C02_loss=Focal+Dice] ep10 | TL 0.1869 | VL 0.2982 | VD 0.6517 | VI 0.6016 | LR 1.00e-04
  ✓ best saved (val_dice=0.651666) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.62it/s]
C02_loss=Focal+Dice | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.96it/s]

[C02_loss=Focal+Dice] ep11 | TL 0.1828 | VL 0.4121 | VD 0.6220 | VI 0.5748 | LR 1.00e-04

C02_loss=Focal+Dice | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.81it/s]
C02_loss=Focal+Dice | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.53it/s]

[C02_loss=Focal+Dice] ep12 | TL 0.1670 | VL 0.3950 | VD 0.6404 | VI 0.5877 | LR 1.00e-04

C02_loss=Focal+Dice | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.01it/s]
C02_loss=Focal+Dice | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.44it/s]

[C02_loss=Focal+Dice] ep13 | TL 0.1687 | VL 0.3977 | VD 0.6325 | VI 0.5797 | LR 1.00e-04

C02_loss=Focal+Dice | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.46it/s]
C02_loss=Focal+Dice | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.13it/s]

[C02_loss=Focal+Dice] ep14 | TL 0.1395 | VL 0.3059 | VD 0.6737 | VI 0.6260 | LR 1.00e-04
  ✓ best saved (val_dice=0.673724) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.84it/s]
C02_loss=Focal+Dice | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.24it/s]

[C02_loss=Focal+Dice] ep15 | TL 0.1266 | VL 0.4585 | VD 0.5873 | VI 0.5301 | LR 1.00e-04

C02_loss=Focal+Dice | 16/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.87it/s]
C02_loss=Focal+Dice | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 75.55it/s]

[C02_loss=Focal+Dice] ep16 | TL 0.1314 | VL 0.3134 | VD 0.6752 | VI 0.6299 | LR 1.00e-04
  ✓ best saved (val_dice=0.675188) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.20it/s]
C02_loss=Focal+Dice | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.58it/s]

[C02_loss=Focal+Dice] ep17 | TL 0.1101 | VL 0.4330 | VD 0.6511 | VI 0.6129 | LR 1.00e-04

C02_loss=Focal+Dice | 18/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.60it/s]
C02_loss=Focal+Dice | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.16it/s]

[C02_loss=Focal+Dice] ep18 | TL 0.0969 | VL 0.2544 | VD 0.7047 | VI 0.6568 | LR 1.00e-04
  ✓ best saved (val_dice=0.704662) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.61it/s]
C02_loss=Focal+Dice | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.11it/s]

[C02_loss=Focal+Dice] ep19 | TL 0.1621 | VL 0.3484 | VD 0.6282 | VI 0.5764 | LR 1.00e-04

C02_loss=Focal+Dice | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.89it/s]
C02_loss=Focal+Dice | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.79it/s]

[C02_loss=Focal+Dice] ep20 | TL 0.1142 | VL 0.2903 | VD 0.6818 | VI 0.6383 | LR 1.00e-04

C02_loss=Focal+Dice | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 42.00it/s]
C02_loss=Focal+Dice | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.75it/s]

[C02_loss=Focal+Dice] ep21 | TL 0.0907 | VL 0.2846 | VD 0.6912 | VI 0.6485 | LR 1.00e-04

C02_loss=Focal+Dice | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.59it/s]
C02_loss=Focal+Dice | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.72it/s]

[C02_loss=Focal+Dice] ep22 | TL 0.0757 | VL 0.4624 | VD 0.6370 | VI 0.5935 | LR 1.00e-04

C02_loss=Focal+Dice | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.37it/s]
C02_loss=Focal+Dice | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.41it/s]

[C02_loss=Focal+Dice] ep23 | TL 0.0826 | VL 0.3021 | VD 0.6819 | VI 0.6372 | LR 1.00e-04

C02_loss=Focal+Dice | 24/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.32it/s]
C02_loss=Focal+Dice | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.68it/s]

[C02_loss=Focal+Dice] ep24 | TL 0.0978 | VL 0.5841 | VD 0.5753 | VI 0.5185 | LR 1.00e-04

C02_loss=Focal+Dice | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.91it/s]
C02_loss=Focal+Dice | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.75it/s]

[C02_loss=Focal+Dice] ep25 | TL 0.1300 | VL 0.3685 | VD 0.6495 | VI 0.6091 | LR 1.00e-04

C02_loss=Focal+Dice | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.41it/s]
C02_loss=Focal+Dice | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.70it/s]

[C02_loss=Focal+Dice] ep26 | TL 0.0927 | VL 0.3491 | VD 0.6920 | VI 0.6533 | LR 1.00e-04

C02_loss=Focal+Dice | 27/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.41it/s]
C02_loss=Focal+Dice | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.70it/s]

[C02_loss=Focal+Dice] ep27 | TL 0.0820 | VL 0.3415 | VD 0.6799 | VI 0.6358 | LR 1.00e-04

C02_loss=Focal+Dice | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.52it/s]
C02_loss=Focal+Dice | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.39it/s]

[C02_loss=Focal+Dice] ep28 | TL 0.0882 | VL 0.3270 | VD 0.6341 | VI 0.5856 | LR 1.00e-04

C02_loss=Focal+Dice | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.06it/s]
C02_loss=Focal+Dice | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.95it/s]

[C02_loss=Focal+Dice] ep29 | TL 0.0819 | VL 0.2860 | VD 0.6776 | VI 0.6347 | LR 1.00e-04

C02_loss=Focal+Dice | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.59it/s]
C02_loss=Focal+Dice | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.94it/s]

[C02_loss=Focal+Dice] ep30 | TL 0.0603 | VL 0.2996 | VD 0.7111 | VI 0.6705 | LR 1.00e-04
  ✓ best saved (val_dice=0.711051) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth

C02_loss=Focal+Dice | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 68.83it/s]
C03_sched=plateau | 1/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.30it/s]
C03_sched=plateau | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.71it/s]

[C03_sched=plateau] ep01 | TL 0.9528 | VL 1.1390 | VD 0.5649 | VI 0.5153 | LR 1.00e-04
  ✓ best saved (val_dice=0.564915) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.70it/s]
C03_sched=plateau | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.18it/s]

[C03_sched=plateau] ep02 | TL 0.7806 | VL 1.2096 | VD 0.4132 | VI 0.3807 | LR 1.00e-04

C03_sched=plateau | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.77it/s]
C03_sched=plateau | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.27it/s]

[C03_sched=plateau] ep03 | TL 0.6904 | VL 0.7145 | VD 0.5831 | VI 0.5420 | LR 1.00e-04
  ✓ best saved (val_dice=0.583105) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.19it/s]
C03_sched=plateau | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.28it/s]

[C03_sched=plateau] ep04 | TL 0.5662 | VL 0.7546 | VD 0.5964 | VI 0.5434 | LR 1.00e-04
  ✓ best saved (val_dice=0.596434) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 5/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.37it/s]
C03_sched=plateau | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.70it/s]

[C03_sched=plateau] ep05 | TL 0.5224 | VL 0.6115 | VD 0.6211 | VI 0.5777 | LR 1.00e-04
  ✓ best saved (val_dice=0.621140) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 6/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.68it/s]
C03_sched=plateau | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.27it/s]

[C03_sched=plateau] ep06 | TL 0.4662 | VL 0.6018 | VD 0.6186 | VI 0.5803 | LR 1.00e-04

C03_sched=plateau | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.00it/s]
C03_sched=plateau | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.26it/s]

[C03_sched=plateau] ep07 | TL 0.4303 | VL 0.6411 | VD 0.6165 | VI 0.5710 | LR 1.00e-04

C03_sched=plateau | 8/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.00it/s]
C03_sched=plateau | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.41it/s]

[C03_sched=plateau] ep08 | TL 0.3823 | VL 0.5447 | VD 0.6468 | VI 0.5982 | LR 1.00e-04
  ✓ best saved (val_dice=0.646777) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 9/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.29it/s]
C03_sched=plateau | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.88it/s]

[C03_sched=plateau] ep09 | TL 0.3469 | VL 0.5801 | VD 0.6529 | VI 0.6078 | LR 1.00e-04
  ✓ best saved (val_dice=0.652897) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 10/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.45it/s]
C03_sched=plateau | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.89it/s]

[C03_sched=plateau] ep10 | TL 0.3487 | VL 0.6089 | VD 0.6302 | VI 0.5778 | LR 1.00e-04

C03_sched=plateau | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.47it/s]
C03_sched=plateau | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.01it/s]

[C03_sched=plateau] ep11 | TL 0.3111 | VL 0.5583 | VD 0.6333 | VI 0.5875 | LR 5.00e-05

C03_sched=plateau | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.44it/s]
C03_sched=plateau | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.23it/s]

[C03_sched=plateau] ep12 | TL 0.2566 | VL 0.4873 | VD 0.6786 | VI 0.6318 | LR 5.00e-05
  ✓ best saved (val_dice=0.678595) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 13/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.65it/s]
C03_sched=plateau | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.06it/s]

[C03_sched=plateau] ep13 | TL 0.2384 | VL 0.4680 | VD 0.6793 | VI 0.6346 | LR 5.00e-05
  ✓ best saved (val_dice=0.679344) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.57it/s]
C03_sched=plateau | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.29it/s]

[C03_sched=plateau] ep14 | TL 0.1989 | VL 0.4474 | VD 0.6777 | VI 0.6342 | LR 5.00e-05

C03_sched=plateau | 15/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.10it/s]
C03_sched=plateau | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.02it/s]

[C03_sched=plateau] ep15 | TL 0.1737 | VL 0.4544 | VD 0.6784 | VI 0.6321 | LR 5.00e-05

C03_sched=plateau | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.10it/s]
C03_sched=plateau | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.34it/s]

[C03_sched=plateau] ep16 | TL 0.1724 | VL 0.4571 | VD 0.6873 | VI 0.6449 | LR 5.00e-05
  ✓ best saved (val_dice=0.687346) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.50it/s]
C03_sched=plateau | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.34it/s]

[C03_sched=plateau] ep17 | TL 0.1691 | VL 0.4924 | VD 0.6784 | VI 0.6348 | LR 2.50e-05

C03_sched=plateau | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.88it/s]
C03_sched=plateau | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.56it/s]

[C03_sched=plateau] ep18 | TL 0.1396 | VL 0.4552 | VD 0.6906 | VI 0.6477 | LR 2.50e-05
  ✓ best saved (val_dice=0.690642) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 19/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.20it/s]
C03_sched=plateau | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 76.24it/s]

[C03_sched=plateau] ep19 | TL 0.1664 | VL 0.4591 | VD 0.6916 | VI 0.6484 | LR 2.50e-05
  ✓ best saved (val_dice=0.691586) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.86it/s]
C03_sched=plateau | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.82it/s]

[C03_sched=plateau] ep20 | TL 0.1317 | VL 0.4376 | VD 0.6958 | VI 0.6524 | LR 2.50e-05
  ✓ best saved (val_dice=0.695838) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.55it/s]
C03_sched=plateau | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.75it/s]

[C03_sched=plateau] ep21 | TL 0.1244 | VL 0.4656 | VD 0.6915 | VI 0.6496 | LR 2.50e-05

C03_sched=plateau | 22/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.82it/s]
C03_sched=plateau | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.77it/s]

[C03_sched=plateau] ep22 | TL 0.1167 | VL 0.4608 | VD 0.6967 | VI 0.6543 | LR 2.50e-05
  ✓ best saved (val_dice=0.696678) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.64it/s]
C03_sched=plateau | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.95it/s]

[C03_sched=plateau] ep23 | TL 0.1342 | VL 0.4587 | VD 0.6966 | VI 0.6527 | LR 1.25e-05

C03_sched=plateau | 24/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.24it/s]
C03_sched=plateau | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.61it/s]

[C03_sched=plateau] ep24 | TL 0.1258 | VL 0.4723 | VD 0.6939 | VI 0.6508 | LR 1.25e-05

C03_sched=plateau | 25/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.63it/s]
C03_sched=plateau | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.13it/s]

[C03_sched=plateau] ep25 | TL 0.1209 | VL 0.4504 | VD 0.6922 | VI 0.6495 | LR 1.25e-05

C03_sched=plateau | 26/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.63it/s]
C03_sched=plateau | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.22it/s]

[C03_sched=plateau] ep26 | TL 0.1147 | VL 0.4589 | VD 0.6959 | VI 0.6531 | LR 6.25e-06

C03_sched=plateau | 27/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.73it/s]
C03_sched=plateau | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.01it/s]

[C03_sched=plateau] ep27 | TL 0.1099 | VL 0.4714 | VD 0.6995 | VI 0.6561 | LR 6.25e-06
  ✓ best saved (val_dice=0.699540) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth

C03_sched=plateau | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 38.69it/s]
C03_sched=plateau | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.91it/s]

[C03_sched=plateau] ep28 | TL 0.1216 | VL 0.4614 | VD 0.6952 | VI 0.6519 | LR 6.25e-06

C03_sched=plateau | 29/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.46it/s]
C03_sched=plateau | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.40it/s]

[C03_sched=plateau] ep29 | TL 0.1084 | VL 0.4613 | VD 0.6903 | VI 0.6472 | LR 3.13e-06

C03_sched=plateau | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.09it/s]
C03_sched=plateau | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.42it/s]

[C03_sched=plateau] ep30 | TL 0.1033 | VL 0.4473 | VD 0.6935 | VI 0.6504 | LR 3.13e-06

C03_sched=plateau | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 70.80it/s]
/tmp/ipython-input-3479599924.py:196: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=use_amp) if use_amp else None
C04_amp=on | 1/30 TRAIN:   0%|          | 0/252 [00:00<?, ?it/s]/tmp/ipython-input-3479599924.py:109: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(True):
C04_amp=on | 1/30 TRAIN: 100%|██████████| 252/252 [00:14<00:00, 17.99it/s]
C04_amp=on | 1/30 VAL: 100%|██████████| 54/54 [00:01<00:00, 28.86it/s]

[C04_amp=on] ep01 | TL 0.9576 | VL 0.9632 | VD 0.5737 | VI 0.5213 | LR 1.00e-04
  ✓ best saved (val_dice=0.573662) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.28it/s]
C04_amp=on | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.31it/s]

[C04_amp=on] ep02 | TL 0.7769 | VL 1.0883 | VD 0.4193 | VI 0.3992 | LR 1.00e-04

C04_amp=on | 3/30 TRAIN: 100%|██████████| 252/252 [00:07<00:00, 35.88it/s]
C04_amp=on | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 61.78it/s]

[C04_amp=on] ep03 | TL 0.6938 | VL 0.6867 | VD 0.5885 | VI 0.5469 | LR 1.00e-04
  ✓ best saved (val_dice=0.588469) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 4/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.57it/s]
C04_amp=on | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.98it/s]

[C04_amp=on] ep04 | TL 0.5679 | VL 0.6866 | VD 0.5935 | VI 0.5504 | LR 1.00e-04
  ✓ best saved (val_dice=0.593489) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.99it/s]
C04_amp=on | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.23it/s]

[C04_amp=on] ep05 | TL 0.5323 | VL 0.6478 | VD 0.6045 | VI 0.5583 | LR 1.00e-04
  ✓ best saved (val_dice=0.604496) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.68it/s]
C04_amp=on | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 63.74it/s]

[C04_amp=on] ep06 | TL 0.4603 | VL 0.9380 | VD 0.5302 | VI 0.4893 | LR 1.00e-04

C04_amp=on | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.09it/s]
C04_amp=on | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.08it/s]

[C04_amp=on] ep07 | TL 0.4318 | VL 0.5683 | VD 0.6196 | VI 0.5747 | LR 1.00e-04
  ✓ best saved (val_dice=0.619551) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.24it/s]
C04_amp=on | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.40it/s]

[C04_amp=on] ep08 | TL 0.3863 | VL 0.6750 | VD 0.6012 | VI 0.5570 | LR 1.00e-04

C04_amp=on | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.53it/s]
C04_amp=on | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.75it/s]

[C04_amp=on] ep09 | TL 0.3680 | VL 0.6531 | VD 0.6589 | VI 0.6122 | LR 1.00e-04
  ✓ best saved (val_dice=0.658859) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.89it/s]
C04_amp=on | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.86it/s]

[C04_amp=on] ep10 | TL 0.3122 | VL 0.6108 | VD 0.6523 | VI 0.6042 | LR 1.00e-04

C04_amp=on | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.20it/s]
C04_amp=on | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.90it/s]

[C04_amp=on] ep11 | TL 0.3149 | VL 0.5681 | VD 0.6547 | VI 0.6072 | LR 1.00e-04

C04_amp=on | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.72it/s]
C04_amp=on | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.35it/s]

[C04_amp=on] ep12 | TL 0.2736 | VL 0.5238 | VD 0.6744 | VI 0.6328 | LR 1.00e-04
  ✓ best saved (val_dice=0.674445) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.63it/s]
C04_amp=on | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.06it/s]

[C04_amp=on] ep13 | TL 0.2733 | VL 0.5067 | VD 0.6497 | VI 0.6042 | LR 1.00e-04

C04_amp=on | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.36it/s]
C04_amp=on | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.97it/s]

[C04_amp=on] ep14 | TL 0.2414 | VL 0.5453 | VD 0.6579 | VI 0.6201 | LR 1.00e-04

C04_amp=on | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.93it/s]
C04_amp=on | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.54it/s]

[C04_amp=on] ep15 | TL 0.1914 | VL 0.5091 | VD 0.6747 | VI 0.6293 | LR 1.00e-04
  ✓ best saved (val_dice=0.674708) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.15it/s]
C04_amp=on | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.28it/s]

[C04_amp=on] ep16 | TL 0.1996 | VL 0.5716 | VD 0.6668 | VI 0.6222 | LR 1.00e-04

C04_amp=on | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.16it/s]
C04_amp=on | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.87it/s]

[C04_amp=on] ep17 | TL 0.2074 | VL 0.6060 | VD 0.6605 | VI 0.6098 | LR 1.00e-04

C04_amp=on | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.60it/s]
C04_amp=on | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 61.13it/s]

[C04_amp=on] ep18 | TL 0.2466 | VL 0.5591 | VD 0.6701 | VI 0.6210 | LR 1.00e-04

C04_amp=on | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.14it/s]
C04_amp=on | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.06it/s]

[C04_amp=on] ep19 | TL 0.2417 | VL 0.6837 | VD 0.6509 | VI 0.6005 | LR 1.00e-04

C04_amp=on | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.02it/s]
C04_amp=on | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.11it/s]

[C04_amp=on] ep20 | TL 0.1743 | VL 0.5422 | VD 0.6671 | VI 0.6222 | LR 1.00e-04

C04_amp=on | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.08it/s]
C04_amp=on | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.04it/s]

[C04_amp=on] ep21 | TL 0.1689 | VL 0.5272 | VD 0.6671 | VI 0.6263 | LR 1.00e-04

C04_amp=on | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.70it/s]
C04_amp=on | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 63.71it/s]

[C04_amp=on] ep22 | TL 0.1293 | VL 0.4921 | VD 0.6973 | VI 0.6551 | LR 1.00e-04
  ✓ best saved (val_dice=0.697255) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 23/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.47it/s]
C04_amp=on | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.02it/s]

[C04_amp=on] ep23 | TL 0.1611 | VL 0.6776 | VD 0.6309 | VI 0.5823 | LR 1.00e-04

C04_amp=on | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.89it/s]
C04_amp=on | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.66it/s]

[C04_amp=on] ep24 | TL 0.1818 | VL 1.0238 | VD 0.5050 | VI 0.4468 | LR 1.00e-04

C04_amp=on | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.63it/s]
C04_amp=on | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 63.56it/s]

[C04_amp=on] ep25 | TL 0.1638 | VL 0.6131 | VD 0.6489 | VI 0.6074 | LR 1.00e-04

C04_amp=on | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.25it/s]
C04_amp=on | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.56it/s]

[C04_amp=on] ep26 | TL 0.1588 | VL 0.5500 | VD 0.6497 | VI 0.6058 | LR 1.00e-04

C04_amp=on | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.25it/s]
C04_amp=on | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.02it/s]

[C04_amp=on] ep27 | TL 0.1461 | VL 0.4897 | VD 0.7007 | VI 0.6612 | LR 1.00e-04
  ✓ best saved (val_dice=0.700655) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 36.36it/s]
C04_amp=on | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.29it/s]

[C04_amp=on] ep28 | TL 0.1387 | VL 0.5323 | VD 0.6690 | VI 0.6250 | LR 1.00e-04

C04_amp=on | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.09it/s]
C04_amp=on | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.99it/s]

[C04_amp=on] ep29 | TL 0.1101 | VL 0.5039 | VD 0.7054 | VI 0.6642 | LR 1.00e-04
  ✓ best saved (val_dice=0.705376) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth

C04_amp=on | 30/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.18it/s]
C04_amp=on | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.16it/s]

[C04_amp=on] ep30 | TL 0.0949 | VL 0.5174 | VD 0.7039 | VI 0.6654 | LR 1.00e-04

C04_amp=on | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 65.82it/s]
C05_clip=1.0 | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.24it/s]
C05_clip=1.0 | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.81it/s]

[C05_clip=1.0] ep01 | TL 0.9505 | VL 1.6336 | VD 0.5653 | VI 0.5117 | LR 1.00e-04
  ✓ best saved (val_dice=0.565314) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 2/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.68it/s]
C05_clip=1.0 | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.26it/s]

[C05_clip=1.0] ep02 | TL 0.7838 | VL 1.0665 | VD 0.4527 | VI 0.4186 | LR 1.00e-04

C05_clip=1.0 | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.65it/s]
C05_clip=1.0 | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.59it/s]

[C05_clip=1.0] ep03 | TL 0.6713 | VL 0.6470 | VD 0.6087 | VI 0.5636 | LR 1.00e-04
  ✓ best saved (val_dice=0.608734) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 4/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.35it/s]
C05_clip=1.0 | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.50it/s]

[C05_clip=1.0] ep04 | TL 0.5636 | VL 0.8054 | VD 0.6056 | VI 0.5539 | LR 1.00e-04

C05_clip=1.0 | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.14it/s]
C05_clip=1.0 | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.21it/s]

[C05_clip=1.0] ep05 | TL 0.5248 | VL 0.8779 | VD 0.5518 | VI 0.5215 | LR 1.00e-04

C05_clip=1.0 | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.00it/s]
C05_clip=1.0 | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.11it/s]

[C05_clip=1.0] ep06 | TL 0.4492 | VL 0.6176 | VD 0.6173 | VI 0.5732 | LR 1.00e-04
  ✓ best saved (val_dice=0.617267) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 7/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.10it/s]
C05_clip=1.0 | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.07it/s]

[C05_clip=1.0] ep07 | TL 0.4068 | VL 0.5981 | VD 0.6382 | VI 0.5926 | LR 1.00e-04
  ✓ best saved (val_dice=0.638158) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 8/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.23it/s]
C05_clip=1.0 | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.39it/s]

[C05_clip=1.0] ep08 | TL 0.3668 | VL 0.7712 | VD 0.6118 | VI 0.5717 | LR 1.00e-04

C05_clip=1.0 | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 37.93it/s]
C05_clip=1.0 | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.40it/s]

[C05_clip=1.0] ep09 | TL 0.3401 | VL 0.6112 | VD 0.6414 | VI 0.5954 | LR 1.00e-04
  ✓ best saved (val_dice=0.641411) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.65it/s]
C05_clip=1.0 | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.34it/s]

[C05_clip=1.0] ep10 | TL 0.2812 | VL 1.0791 | VD 0.6287 | VI 0.5792 | LR 1.00e-04

C05_clip=1.0 | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.96it/s]
C05_clip=1.0 | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 66.11it/s]

[C05_clip=1.0] ep11 | TL 0.2559 | VL 0.6401 | VD 0.6373 | VI 0.5908 | LR 1.00e-04

C05_clip=1.0 | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.65it/s]
C05_clip=1.0 | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.21it/s]

[C05_clip=1.0] ep12 | TL 0.2530 | VL 0.6573 | VD 0.6520 | VI 0.6027 | LR 1.00e-04
  ✓ best saved (val_dice=0.652017) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.82it/s]
C05_clip=1.0 | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.27it/s]

[C05_clip=1.0] ep13 | TL 0.2370 | VL 1.5461 | VD 0.5272 | VI 0.4733 | LR 1.00e-04

C05_clip=1.0 | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.61it/s]
C05_clip=1.0 | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.02it/s]

[C05_clip=1.0] ep14 | TL 0.2050 | VL 0.6114 | VD 0.6774 | VI 0.6396 | LR 1.00e-04
  ✓ best saved (val_dice=0.677420) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.92it/s]
C05_clip=1.0 | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.90it/s]

[C05_clip=1.0] ep15 | TL 0.1637 | VL 0.5479 | VD 0.6828 | VI 0.6388 | LR 1.00e-04
  ✓ best saved (val_dice=0.682781) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.03it/s]
C05_clip=1.0 | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.77it/s]

[C05_clip=1.0] ep16 | TL 0.1555 | VL 0.6573 | VD 0.6671 | VI 0.6296 | LR 1.00e-04

C05_clip=1.0 | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.53it/s]
C05_clip=1.0 | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.07it/s]

[C05_clip=1.0] ep17 | TL 0.1395 | VL 0.7451 | VD 0.6677 | VI 0.6282 | LR 1.00e-04

C05_clip=1.0 | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.98it/s]
C05_clip=1.0 | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.08it/s]

[C05_clip=1.0] ep18 | TL 0.1200 | VL 0.5591 | VD 0.6872 | VI 0.6463 | LR 1.00e-04
  ✓ best saved (val_dice=0.687247) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.54it/s]
C05_clip=1.0 | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.48it/s]

[C05_clip=1.0] ep19 | TL 0.1512 | VL 0.6264 | VD 0.7031 | VI 0.6638 | LR 1.00e-04
  ✓ best saved (val_dice=0.703137) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 20/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.61it/s]
C05_clip=1.0 | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.51it/s]

[C05_clip=1.0] ep20 | TL 0.0995 | VL 0.7089 | VD 0.6505 | VI 0.6148 | LR 1.00e-04

C05_clip=1.0 | 21/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.62it/s]
C05_clip=1.0 | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.88it/s]

[C05_clip=1.0] ep21 | TL 0.1040 | VL 0.6640 | VD 0.6687 | VI 0.6294 | LR 1.00e-04

C05_clip=1.0 | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.61it/s]
C05_clip=1.0 | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.02it/s]

[C05_clip=1.0] ep22 | TL 0.0824 | VL 0.6840 | VD 0.6987 | VI 0.6622 | LR 1.00e-04

C05_clip=1.0 | 23/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.16it/s]
C05_clip=1.0 | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.54it/s]

[C05_clip=1.0] ep23 | TL 0.1161 | VL 0.7920 | VD 0.6871 | VI 0.6520 | LR 1.00e-04

C05_clip=1.0 | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.13it/s]
C05_clip=1.0 | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.55it/s]

[C05_clip=1.0] ep24 | TL 0.1096 | VL 0.9808 | VD 0.6367 | VI 0.5982 | LR 1.00e-04

C05_clip=1.0 | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 38.51it/s]
C05_clip=1.0 | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.03it/s]

[C05_clip=1.0] ep25 | TL 0.0894 | VL 0.5951 | VD 0.7086 | VI 0.6736 | LR 1.00e-04
  ✓ best saved (val_dice=0.708551) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.33it/s]
C05_clip=1.0 | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.77it/s]

[C05_clip=1.0] ep26 | TL 0.0824 | VL 0.6691 | VD 0.6845 | VI 0.6493 | LR 1.00e-04

C05_clip=1.0 | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.22it/s]
C05_clip=1.0 | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.30it/s]

[C05_clip=1.0] ep27 | TL 0.0833 | VL 0.6727 | VD 0.6906 | VI 0.6552 | LR 1.00e-04

C05_clip=1.0 | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.11it/s]
C05_clip=1.0 | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.91it/s]

[C05_clip=1.0] ep28 | TL 0.1039 | VL 0.5818 | VD 0.7003 | VI 0.6586 | LR 1.00e-04

C05_clip=1.0 | 29/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.96it/s]
C05_clip=1.0 | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.18it/s]

[C05_clip=1.0] ep29 | TL 0.0758 | VL 0.7669 | VD 0.7100 | VI 0.6781 | LR 1.00e-04
  ✓ best saved (val_dice=0.709957) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth

C05_clip=1.0 | 30/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.04it/s]
C05_clip=1.0 | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.08it/s]

[C05_clip=1.0] ep30 | TL 0.0646 | VL 0.6729 | VD 0.6999 | VI 0.6607 | LR 1.00e-04

C05_clip=1.0 | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 70.77it/s]
C06_freeze=2ep | 1/30 TRAIN: 100%|██████████| 252/252 [00:04<00:00, 55.45it/s]
C06_freeze=2ep | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.51it/s]

[C06_freeze=2ep] ep01 | TL 1.0451 | VL 0.8714 | VD 0.5342 | VI 0.4855 | LR 1.00e-04
  ✓ best saved (val_dice=0.534238) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 2/30 TRAIN: 100%|██████████| 252/252 [00:04<00:00, 57.22it/s]
C06_freeze=2ep | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.06it/s]

[C06_freeze=2ep] ep02 | TL 0.9118 | VL 0.8337 | VD 0.5206 | VI 0.4756 | LR 1.00e-04

C06_freeze=2ep | 3/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.04it/s]
C06_freeze=2ep | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.46it/s]

[C06_freeze=2ep] ep03 | TL 0.9253 | VL 0.8107 | VD 0.5729 | VI 0.5239 | LR 1.00e-04
  ✓ best saved (val_dice=0.572940) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 44.20it/s]
C06_freeze=2ep | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.96it/s]

[C06_freeze=2ep] ep04 | TL 0.7368 | VL 0.7675 | VD 0.5695 | VI 0.5204 | LR 1.00e-04

C06_freeze=2ep | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.34it/s]
C06_freeze=2ep | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.53it/s]

[C06_freeze=2ep] ep05 | TL 0.6768 | VL 0.6847 | VD 0.5946 | VI 0.5553 | LR 1.00e-04
  ✓ best saved (val_dice=0.594595) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.91it/s]
C06_freeze=2ep | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.84it/s]

[C06_freeze=2ep] ep06 | TL 0.5905 | VL 0.7544 | VD 0.5903 | VI 0.5388 | LR 1.00e-04

C06_freeze=2ep | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.15it/s]
C06_freeze=2ep | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.65it/s]

[C06_freeze=2ep] ep07 | TL 0.5209 | VL 0.6379 | VD 0.5917 | VI 0.5482 | LR 1.00e-04

C06_freeze=2ep | 8/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.24it/s]
C06_freeze=2ep | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.07it/s]

[C06_freeze=2ep] ep08 | TL 0.4621 | VL 0.6553 | VD 0.6007 | VI 0.5623 | LR 1.00e-04
  ✓ best saved (val_dice=0.600696) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 9/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.17it/s]
C06_freeze=2ep | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.26it/s]

[C06_freeze=2ep] ep09 | TL 0.4477 | VL 0.6761 | VD 0.6212 | VI 0.5749 | LR 1.00e-04
  ✓ best saved (val_dice=0.621191) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 10/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.59it/s]
C06_freeze=2ep | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.51it/s]

[C06_freeze=2ep] ep10 | TL 0.3992 | VL 0.5620 | VD 0.6526 | VI 0.6027 | LR 1.00e-04
  ✓ best saved (val_dice=0.652630) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 11/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.95it/s]
C06_freeze=2ep | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.90it/s]

[C06_freeze=2ep] ep11 | TL 0.3669 | VL 1.0649 | VD 0.4885 | VI 0.4350 | LR 1.00e-04

C06_freeze=2ep | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.41it/s]
C06_freeze=2ep | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.44it/s]

[C06_freeze=2ep] ep12 | TL 0.3721 | VL 0.5668 | VD 0.6471 | VI 0.5993 | LR 1.00e-04

C06_freeze=2ep | 13/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.80it/s]
C06_freeze=2ep | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.36it/s]

[C06_freeze=2ep] ep13 | TL 0.3347 | VL 0.8337 | VD 0.5764 | VI 0.5250 | LR 1.00e-04

C06_freeze=2ep | 14/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.19it/s]
C06_freeze=2ep | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.30it/s]

[C06_freeze=2ep] ep14 | TL 0.2880 | VL 0.7677 | VD 0.5936 | VI 0.5478 | LR 1.00e-04

C06_freeze=2ep | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 38.37it/s]
C06_freeze=2ep | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.38it/s]

[C06_freeze=2ep] ep15 | TL 0.2480 | VL 0.6512 | VD 0.6493 | VI 0.6038 | LR 1.00e-04

C06_freeze=2ep | 16/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.23it/s]
C06_freeze=2ep | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.70it/s]

[C06_freeze=2ep] ep16 | TL 0.2736 | VL 0.9253 | VD 0.5781 | VI 0.5295 | LR 1.00e-04

C06_freeze=2ep | 17/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.71it/s]
C06_freeze=2ep | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.84it/s]

[C06_freeze=2ep] ep17 | TL 0.2493 | VL 0.6853 | VD 0.6200 | VI 0.5670 | LR 1.00e-04

C06_freeze=2ep | 18/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.90it/s]
C06_freeze=2ep | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.47it/s]

[C06_freeze=2ep] ep18 | TL 0.2072 | VL 0.5991 | VD 0.6822 | VI 0.6383 | LR 1.00e-04
  ✓ best saved (val_dice=0.682210) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.19it/s]
C06_freeze=2ep | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 63.52it/s]

[C06_freeze=2ep] ep19 | TL 0.2440 | VL 0.7311 | VD 0.6377 | VI 0.5863 | LR 1.00e-04

C06_freeze=2ep | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.50it/s]
C06_freeze=2ep | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.55it/s]

[C06_freeze=2ep] ep20 | TL 0.1998 | VL 0.5848 | VD 0.6612 | VI 0.6156 | LR 1.00e-04

C06_freeze=2ep | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.03it/s]
C06_freeze=2ep | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.72it/s]

[C06_freeze=2ep] ep21 | TL 0.1830 | VL 0.6133 | VD 0.6452 | VI 0.5968 | LR 1.00e-04

C06_freeze=2ep | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.58it/s]
C06_freeze=2ep | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.99it/s]

[C06_freeze=2ep] ep22 | TL 0.1569 | VL 0.5287 | VD 0.6697 | VI 0.6299 | LR 1.00e-04

C06_freeze=2ep | 23/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.26it/s]
C06_freeze=2ep | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.14it/s]

[C06_freeze=2ep] ep23 | TL 0.1622 | VL 0.6673 | VD 0.6488 | VI 0.6077 | LR 1.00e-04

C06_freeze=2ep | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.78it/s]
C06_freeze=2ep | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.85it/s]

[C06_freeze=2ep] ep24 | TL 0.1964 | VL 1.4167 | VD 0.4614 | VI 0.4147 | LR 1.00e-04

C06_freeze=2ep | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.84it/s]
C06_freeze=2ep | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.88it/s]

[C06_freeze=2ep] ep25 | TL 0.2170 | VL 0.5855 | VD 0.6590 | VI 0.6153 | LR 1.00e-04

C06_freeze=2ep | 26/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.34it/s]
C06_freeze=2ep | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.69it/s]

[C06_freeze=2ep] ep26 | TL 0.1863 | VL 0.6163 | VD 0.6426 | VI 0.5982 | LR 1.00e-04

C06_freeze=2ep | 27/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.23it/s]
C06_freeze=2ep | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.24it/s]

[C06_freeze=2ep] ep27 | TL 0.1565 | VL 0.5261 | VD 0.6728 | VI 0.6337 | LR 1.00e-04

C06_freeze=2ep | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.71it/s]
C06_freeze=2ep | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.97it/s]

[C06_freeze=2ep] ep28 | TL 0.1686 | VL 0.5683 | VD 0.6632 | VI 0.6208 | LR 1.00e-04

C06_freeze=2ep | 29/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.05it/s]
C06_freeze=2ep | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.48it/s]

[C06_freeze=2ep] ep29 | TL 0.1726 | VL 0.6344 | VD 0.6638 | VI 0.6169 | LR 1.00e-04

C06_freeze=2ep | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.38it/s]
C06_freeze=2ep | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.81it/s]

[C06_freeze=2ep] ep30 | TL 0.1350 | VL 0.5110 | VD 0.6959 | VI 0.6536 | LR 1.00e-04
  ✓ best saved (val_dice=0.695856) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth

C06_freeze=2ep | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 70.16it/s]
C07_ES=on | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.77it/s]
C07_ES=on | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.79it/s]

[C07_ES=on] ep01 | TL 0.9484 | VL 1.3697 | VD 0.5676 | VI 0.5142 | LR 1.00e-04
  ✓ best saved (val_dice=0.567550) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.23it/s]
C07_ES=on | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.91it/s]

[C07_ES=on] ep02 | TL 0.7890 | VL 0.9377 | VD 0.4936 | VI 0.4515 | LR 1.00e-04

C07_ES=on | 3/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.55it/s]
C07_ES=on | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.65it/s]

[C07_ES=on] ep03 | TL 0.7029 | VL 0.6928 | VD 0.6137 | VI 0.5603 | LR 1.00e-04
  ✓ best saved (val_dice=0.613712) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.18it/s]
C07_ES=on | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.27it/s]

[C07_ES=on] ep04 | TL 0.5704 | VL 0.7887 | VD 0.6053 | VI 0.5513 | LR 1.00e-04

C07_ES=on | 5/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.53it/s]
C07_ES=on | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.64it/s]

[C07_ES=on] ep05 | TL 0.5213 | VL 0.7546 | VD 0.5644 | VI 0.5229 | LR 1.00e-04

C07_ES=on | 6/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.17it/s]
C07_ES=on | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.80it/s]

[C07_ES=on] ep06 | TL 0.4693 | VL 0.6466 | VD 0.6082 | VI 0.5648 | LR 1.00e-04

C07_ES=on | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.75it/s]
C07_ES=on | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.37it/s]

[C07_ES=on] ep07 | TL 0.4284 | VL 0.6004 | VD 0.6273 | VI 0.5772 | LR 1.00e-04
  ✓ best saved (val_dice=0.627263) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 8/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.61it/s]
C07_ES=on | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.84it/s]

[C07_ES=on] ep08 | TL 0.3995 | VL 0.5304 | VD 0.6473 | VI 0.5980 | LR 1.00e-04
  ✓ best saved (val_dice=0.647294) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 9/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 38.57it/s]
C07_ES=on | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.74it/s]

[C07_ES=on] ep09 | TL 0.3774 | VL 0.6923 | VD 0.5993 | VI 0.5586 | LR 1.00e-04

C07_ES=on | 10/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.48it/s]
C07_ES=on | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.85it/s]

[C07_ES=on] ep10 | TL 0.3418 | VL 0.6500 | VD 0.5955 | VI 0.5392 | LR 1.00e-04

C07_ES=on | 11/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.19it/s]
C07_ES=on | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.77it/s]

[C07_ES=on] ep11 | TL 0.3034 | VL 0.9634 | VD 0.5430 | VI 0.4799 | LR 1.00e-04

C07_ES=on | 12/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.13it/s]
C07_ES=on | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.04it/s]

[C07_ES=on] ep12 | TL 0.3073 | VL 0.5414 | VD 0.6469 | VI 0.5994 | LR 1.00e-04

C07_ES=on | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.14it/s]
C07_ES=on | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.18it/s]

[C07_ES=on] ep13 | TL 0.3005 | VL 0.6224 | VD 0.6561 | VI 0.6144 | LR 1.00e-04
  ✓ best saved (val_dice=0.656087) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 14/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.59it/s]
C07_ES=on | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.50it/s]

[C07_ES=on] ep14 | TL 0.2548 | VL 0.5472 | VD 0.6506 | VI 0.6061 | LR 1.00e-04

C07_ES=on | 15/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.25it/s]
C07_ES=on | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.57it/s]

[C07_ES=on] ep15 | TL 0.2309 | VL 0.4884 | VD 0.6826 | VI 0.6396 | LR 1.00e-04
  ✓ best saved (val_dice=0.682570) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 16/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.39it/s]
C07_ES=on | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.58it/s]

[C07_ES=on] ep16 | TL 0.1913 | VL 0.5075 | VD 0.6890 | VI 0.6456 | LR 1.00e-04
  ✓ best saved (val_dice=0.689024) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 17/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.58it/s]
C07_ES=on | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.99it/s]

[C07_ES=on] ep17 | TL 0.1824 | VL 0.4849 | VD 0.6823 | VI 0.6400 | LR 1.00e-04

C07_ES=on | 18/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.68it/s]
C07_ES=on | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.80it/s]

[C07_ES=on] ep18 | TL 0.1536 | VL 0.5313 | VD 0.6717 | VI 0.6250 | LR 1.00e-04

C07_ES=on | 19/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.47it/s]
C07_ES=on | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.16it/s]

[C07_ES=on] ep19 | TL 0.2915 | VL 0.6861 | VD 0.6535 | VI 0.6030 | LR 1.00e-04

C07_ES=on | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.24it/s]
C07_ES=on | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.67it/s]

[C07_ES=on] ep20 | TL 0.2089 | VL 0.5141 | VD 0.6889 | VI 0.6458 | LR 1.00e-04

C07_ES=on | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.21it/s]
C07_ES=on | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.85it/s]

[C07_ES=on] ep21 | TL 0.1673 | VL 0.7654 | VD 0.5880 | VI 0.5403 | LR 1.00e-04

C07_ES=on | 22/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.71it/s]
C07_ES=on | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.28it/s]

[C07_ES=on] ep22 | TL 0.1371 | VL 0.4806 | VD 0.6962 | VI 0.6568 | LR 1.00e-04
  ✓ best saved (val_dice=0.696214) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth

C07_ES=on | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.19it/s]
C07_ES=on | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.46it/s]

[C07_ES=on] ep23 | TL 0.1438 | VL 0.5784 | VD 0.6791 | VI 0.6335 | LR 1.00e-04

C07_ES=on | 24/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.90it/s]
C07_ES=on | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.11it/s]

[C07_ES=on] ep24 | TL 0.1682 | VL 1.4746 | VD 0.4892 | VI 0.4470 | LR 1.00e-04

C07_ES=on | 25/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.18it/s]
C07_ES=on | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.51it/s]

[C07_ES=on] ep25 | TL 0.2016 | VL 0.8909 | VD 0.5955 | VI 0.5528 | LR 1.00e-04

C07_ES=on | 26/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.35it/s]
C07_ES=on | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.19it/s]

[C07_ES=on] ep26 | TL 0.2284 | VL 0.7047 | VD 0.6306 | VI 0.5913 | LR 1.00e-04

C07_ES=on | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.44it/s]
C07_ES=on | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.90it/s]

[C07_ES=on] ep27 | TL 0.1551 | VL 0.5279 | VD 0.6916 | VI 0.6496 | LR 1.00e-04

C07_ES=on | 28/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.18it/s]
C07_ES=on | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.98it/s]

[C07_ES=on] ep28 | TL 0.1565 | VL 0.5267 | VD 0.6602 | VI 0.6191 | LR 1.00e-04
⛔ early stop (best ep=22, best val_dice=0.696214)

C07_ES=on | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 68.94it/s]
C08_lr=5e-5 | 1/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.32it/s]
C08_lr=5e-5 | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.60it/s]

[C08_lr=5e-5] ep01 | TL 0.9652 | VL 1.2076 | VD 0.5724 | VI 0.5178 | LR 5.00e-05
  ✓ best saved (val_dice=0.572359) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.83it/s]
C08_lr=5e-5 | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.61it/s]

[C08_lr=5e-5] ep02 | TL 0.7557 | VL 0.8105 | VD 0.5137 | VI 0.4830 | LR 5.00e-05

C08_lr=5e-5 | 3/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.71it/s]
C08_lr=5e-5 | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.28it/s]

[C08_lr=5e-5] ep03 | TL 0.6552 | VL 0.7033 | VD 0.5803 | VI 0.5368 | LR 5.00e-05
  ✓ best saved (val_dice=0.580346) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.74it/s]
C08_lr=5e-5 | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.72it/s]

[C08_lr=5e-5] ep04 | TL 0.5270 | VL 0.7624 | VD 0.6040 | VI 0.5529 | LR 5.00e-05
  ✓ best saved (val_dice=0.603995) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 5/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.75it/s]
C08_lr=5e-5 | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.05it/s]

[C08_lr=5e-5] ep05 | TL 0.4898 | VL 0.6000 | VD 0.6190 | VI 0.5777 | LR 5.00e-05
  ✓ best saved (val_dice=0.619023) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.15it/s]
C08_lr=5e-5 | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.81it/s]

[C08_lr=5e-5] ep06 | TL 0.4359 | VL 0.7163 | VD 0.5911 | VI 0.5495 | LR 5.00e-05

C08_lr=5e-5 | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.96it/s]
C08_lr=5e-5 | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.60it/s]

[C08_lr=5e-5] ep07 | TL 0.4071 | VL 0.5884 | VD 0.5985 | VI 0.5532 | LR 5.00e-05

C08_lr=5e-5 | 8/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.83it/s]
C08_lr=5e-5 | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.16it/s]

[C08_lr=5e-5] ep08 | TL 0.3657 | VL 0.7536 | VD 0.5874 | VI 0.5412 | LR 5.00e-05

C08_lr=5e-5 | 9/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.01it/s]
C08_lr=5e-5 | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.78it/s]

[C08_lr=5e-5] ep09 | TL 0.3589 | VL 0.5728 | VD 0.6400 | VI 0.5945 | LR 5.00e-05
  ✓ best saved (val_dice=0.640005) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 10/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.62it/s]
C08_lr=5e-5 | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 65.74it/s]

[C08_lr=5e-5] ep10 | TL 0.3300 | VL 0.5462 | VD 0.6321 | VI 0.5856 | LR 5.00e-05

C08_lr=5e-5 | 11/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 39.95it/s]
C08_lr=5e-5 | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 63.59it/s]

[C08_lr=5e-5] ep11 | TL 0.3017 | VL 0.5735 | VD 0.6278 | VI 0.5824 | LR 5.00e-05

C08_lr=5e-5 | 12/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.82it/s]
C08_lr=5e-5 | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.12it/s]

[C08_lr=5e-5] ep12 | TL 0.3058 | VL 0.5588 | VD 0.6569 | VI 0.6094 | LR 5.00e-05
  ✓ best saved (val_dice=0.656899) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.05it/s]
C08_lr=5e-5 | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.96it/s]

[C08_lr=5e-5] ep13 | TL 0.3017 | VL 0.5266 | VD 0.6425 | VI 0.5928 | LR 5.00e-05

C08_lr=5e-5 | 14/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.62it/s]
C08_lr=5e-5 | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.79it/s]

[C08_lr=5e-5] ep14 | TL 0.2508 | VL 0.5555 | VD 0.6319 | VI 0.5890 | LR 5.00e-05

C08_lr=5e-5 | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.47it/s]
C08_lr=5e-5 | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.77it/s]

[C08_lr=5e-5] ep15 | TL 0.2195 | VL 0.5022 | VD 0.6593 | VI 0.6163 | LR 5.00e-05
  ✓ best saved (val_dice=0.659344) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 16/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.48it/s]
C08_lr=5e-5 | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.13it/s]

[C08_lr=5e-5] ep16 | TL 0.2151 | VL 0.5359 | VD 0.6606 | VI 0.6166 | LR 5.00e-05
  ✓ best saved (val_dice=0.660629) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 17/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.39it/s]
C08_lr=5e-5 | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.65it/s]

[C08_lr=5e-5] ep17 | TL 0.1921 | VL 0.5065 | VD 0.6674 | VI 0.6227 | LR 5.00e-05
  ✓ best saved (val_dice=0.667442) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 18/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.65it/s]
C08_lr=5e-5 | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.27it/s]

[C08_lr=5e-5] ep18 | TL 0.1706 | VL 0.5059 | VD 0.6704 | VI 0.6232 | LR 5.00e-05
  ✓ best saved (val_dice=0.670440) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.19it/s]
C08_lr=5e-5 | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.98it/s]

[C08_lr=5e-5] ep19 | TL 0.2332 | VL 0.5762 | VD 0.6579 | VI 0.6110 | LR 5.00e-05

C08_lr=5e-5 | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.17it/s]
C08_lr=5e-5 | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.89it/s]

[C08_lr=5e-5] ep20 | TL 0.1936 | VL 0.5175 | VD 0.6704 | VI 0.6269 | LR 5.00e-05

C08_lr=5e-5 | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.81it/s]
C08_lr=5e-5 | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.53it/s]

[C08_lr=5e-5] ep21 | TL 0.1818 | VL 0.5925 | VD 0.6561 | VI 0.6144 | LR 5.00e-05

C08_lr=5e-5 | 22/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.39it/s]
C08_lr=5e-5 | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.50it/s]

[C08_lr=5e-5] ep22 | TL 0.1567 | VL 0.5518 | VD 0.6791 | VI 0.6348 | LR 5.00e-05
  ✓ best saved (val_dice=0.679071) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.45it/s]
C08_lr=5e-5 | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.30it/s]

[C08_lr=5e-5] ep23 | TL 0.1772 | VL 0.5688 | VD 0.6628 | VI 0.6174 | LR 5.00e-05

C08_lr=5e-5 | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.52it/s]
C08_lr=5e-5 | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.49it/s]

[C08_lr=5e-5] ep24 | TL 0.1909 | VL 1.0801 | VD 0.5457 | VI 0.4968 | LR 5.00e-05

C08_lr=5e-5 | 25/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.14it/s]
C08_lr=5e-5 | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.14it/s]

[C08_lr=5e-5] ep25 | TL 0.2177 | VL 0.5263 | VD 0.6609 | VI 0.6144 | LR 5.00e-05

C08_lr=5e-5 | 26/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.73it/s]
C08_lr=5e-5 | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.86it/s]

[C08_lr=5e-5] ep26 | TL 0.1662 | VL 0.4976 | VD 0.6749 | VI 0.6283 | LR 5.00e-05

C08_lr=5e-5 | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.72it/s]
C08_lr=5e-5 | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.63it/s]

[C08_lr=5e-5] ep27 | TL 0.1458 | VL 0.5459 | VD 0.6598 | VI 0.6158 | LR 5.00e-05

C08_lr=5e-5 | 28/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.94it/s]
C08_lr=5e-5 | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.38it/s]

[C08_lr=5e-5] ep28 | TL 0.1639 | VL 0.5640 | VD 0.6758 | VI 0.6303 | LR 5.00e-05

C08_lr=5e-5 | 29/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.09it/s]
C08_lr=5e-5 | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.13it/s]

[C08_lr=5e-5] ep29 | TL 0.1513 | VL 0.5118 | VD 0.6795 | VI 0.6383 | LR 5.00e-05
  ✓ best saved (val_dice=0.679461) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.42it/s]
C08_lr=5e-5 | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.88it/s]

[C08_lr=5e-5] ep30 | TL 0.1224 | VL 0.5395 | VD 0.6812 | VI 0.6401 | LR 5.00e-05
  ✓ best saved (val_dice=0.681247) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth

C08_lr=5e-5 | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 68.76it/s]
C09_lr=2e-4 | 1/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.44it/s]
C09_lr=2e-4 | 1/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.62it/s]

[C09_lr=2e-4] ep01 | TL 0.9838 | VL 1.3315 | VD 0.5651 | VI 0.5124 | LR 2.00e-04
  ✓ best saved (val_dice=0.565109) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 2/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.52it/s]
C09_lr=2e-4 | 2/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.96it/s]

[C09_lr=2e-4] ep02 | TL 0.8705 | VL 0.8952 | VD 0.5057 | VI 0.4679 | LR 2.00e-04

C09_lr=2e-4 | 3/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.55it/s]
C09_lr=2e-4 | 3/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.26it/s]

[C09_lr=2e-4] ep03 | TL 0.8069 | VL 1.3990 | VD 0.5420 | VI 0.4904 | LR 2.00e-04

C09_lr=2e-4 | 4/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.42it/s]
C09_lr=2e-4 | 4/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.76it/s]

[C09_lr=2e-4] ep04 | TL 0.6866 | VL 0.9261 | VD 0.4920 | VI 0.4455 | LR 2.00e-04

C09_lr=2e-4 | 5/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.46it/s]
C09_lr=2e-4 | 5/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.86it/s]

[C09_lr=2e-4] ep05 | TL 0.6661 | VL 1.1867 | VD 0.4304 | VI 0.4064 | LR 2.00e-04

C09_lr=2e-4 | 6/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.13it/s]
C09_lr=2e-4 | 6/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 74.01it/s]

[C09_lr=2e-4] ep06 | TL 0.5882 | VL 0.7291 | VD 0.5707 | VI 0.5308 | LR 2.00e-04
  ✓ best saved (val_dice=0.570707) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 7/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.95it/s]
C09_lr=2e-4 | 7/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.19it/s]

[C09_lr=2e-4] ep07 | TL 0.5353 | VL 0.7292 | VD 0.5954 | VI 0.5525 | LR 2.00e-04
  ✓ best saved (val_dice=0.595449) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 8/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.23it/s]
C09_lr=2e-4 | 8/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.54it/s]

[C09_lr=2e-4] ep08 | TL 0.4768 | VL 0.6348 | VD 0.5950 | VI 0.5434 | LR 2.00e-04

C09_lr=2e-4 | 9/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.58it/s]
C09_lr=2e-4 | 9/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 64.64it/s]

[C09_lr=2e-4] ep09 | TL 0.4789 | VL 0.6681 | VD 0.6308 | VI 0.5848 | LR 2.00e-04
  ✓ best saved (val_dice=0.630790) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 10/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.46it/s]
C09_lr=2e-4 | 10/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.80it/s]

[C09_lr=2e-4] ep10 | TL 0.4182 | VL 0.6929 | VD 0.5750 | VI 0.5290 | LR 2.00e-04

C09_lr=2e-4 | 11/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.95it/s]
C09_lr=2e-4 | 11/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.73it/s]

[C09_lr=2e-4] ep11 | TL 0.3981 | VL 0.6956 | VD 0.6151 | VI 0.5652 | LR 2.00e-04

C09_lr=2e-4 | 12/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.51it/s]
C09_lr=2e-4 | 12/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.67it/s]

[C09_lr=2e-4] ep12 | TL 0.3732 | VL 0.6319 | VD 0.6179 | VI 0.5757 | LR 2.00e-04

C09_lr=2e-4 | 13/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.93it/s]
C09_lr=2e-4 | 13/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.52it/s]

[C09_lr=2e-4] ep13 | TL 0.3533 | VL 0.7322 | VD 0.5979 | VI 0.5556 | LR 2.00e-04

C09_lr=2e-4 | 14/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.44it/s]
C09_lr=2e-4 | 14/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.63it/s]

[C09_lr=2e-4] ep14 | TL 0.2996 | VL 0.6984 | VD 0.6117 | VI 0.5713 | LR 2.00e-04

C09_lr=2e-4 | 15/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.96it/s]
C09_lr=2e-4 | 15/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.06it/s]

[C09_lr=2e-4] ep15 | TL 0.3153 | VL 0.9996 | VD 0.5055 | VI 0.4556 | LR 2.00e-04

C09_lr=2e-4 | 16/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.81it/s]
C09_lr=2e-4 | 16/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.67it/s]

[C09_lr=2e-4] ep16 | TL 0.3163 | VL 0.7316 | VD 0.5950 | VI 0.5605 | LR 2.00e-04

C09_lr=2e-4 | 17/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.08it/s]
C09_lr=2e-4 | 17/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 73.75it/s]

[C09_lr=2e-4] ep17 | TL 0.2726 | VL 0.5408 | VD 0.6834 | VI 0.6413 | LR 2.00e-04
  ✓ best saved (val_dice=0.683434) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 18/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.76it/s]
C09_lr=2e-4 | 18/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 70.41it/s]

[C09_lr=2e-4] ep18 | TL 0.2025 | VL 0.5733 | VD 0.6687 | VI 0.6243 | LR 2.00e-04

C09_lr=2e-4 | 19/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.79it/s]
C09_lr=2e-4 | 19/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.49it/s]

[C09_lr=2e-4] ep19 | TL 0.2564 | VL 0.5609 | VD 0.6489 | VI 0.6082 | LR 2.00e-04

C09_lr=2e-4 | 20/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 43.02it/s]
C09_lr=2e-4 | 20/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 67.67it/s]

[C09_lr=2e-4] ep20 | TL 0.1885 | VL 0.6846 | VD 0.6463 | VI 0.5977 | LR 2.00e-04

C09_lr=2e-4 | 21/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.18it/s]
C09_lr=2e-4 | 21/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.05it/s]

[C09_lr=2e-4] ep21 | TL 0.2090 | VL 0.5722 | VD 0.6596 | VI 0.6120 | LR 2.00e-04

C09_lr=2e-4 | 22/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.38it/s]
C09_lr=2e-4 | 22/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 68.07it/s]

[C09_lr=2e-4] ep22 | TL 0.1579 | VL 0.5640 | VD 0.6898 | VI 0.6465 | LR 2.00e-04
  ✓ best saved (val_dice=0.689750) -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth

C09_lr=2e-4 | 23/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.64it/s]
C09_lr=2e-4 | 23/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.96it/s]

[C09_lr=2e-4] ep23 | TL 0.1749 | VL 0.6004 | VD 0.6469 | VI 0.6052 | LR 2.00e-04

C09_lr=2e-4 | 24/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.28it/s]
C09_lr=2e-4 | 24/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.54it/s]

[C09_lr=2e-4] ep24 | TL 0.1645 | VL 0.5932 | VD 0.6392 | VI 0.5929 | LR 2.00e-04

C09_lr=2e-4 | 25/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.55it/s]
C09_lr=2e-4 | 25/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.10it/s]

[C09_lr=2e-4] ep25 | TL 0.2838 | VL 1.9038 | VD 0.3502 | VI 0.3146 | LR 2.00e-04

C09_lr=2e-4 | 26/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.50it/s]
C09_lr=2e-4 | 26/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 71.12it/s]

[C09_lr=2e-4] ep26 | TL 0.1946 | VL 0.6875 | VD 0.6236 | VI 0.5878 | LR 2.00e-04

C09_lr=2e-4 | 27/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 41.82it/s]
C09_lr=2e-4 | 27/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.10it/s]

[C09_lr=2e-4] ep27 | TL 0.1780 | VL 0.6539 | VD 0.6770 | VI 0.6334 | LR 2.00e-04

C09_lr=2e-4 | 28/30 TRAIN: 100%|██████████| 252/252 [00:06<00:00, 40.72it/s]
C09_lr=2e-4 | 28/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.87it/s]

[C09_lr=2e-4] ep28 | TL 0.1749 | VL 0.6238 | VD 0.6771 | VI 0.6347 | LR 2.00e-04

C09_lr=2e-4 | 29/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.86it/s]
C09_lr=2e-4 | 29/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 69.56it/s]

[C09_lr=2e-4] ep29 | TL 0.1719 | VL 0.5616 | VD 0.6571 | VI 0.6208 | LR 2.00e-04

C09_lr=2e-4 | 30/30 TRAIN: 100%|██████████| 252/252 [00:05<00:00, 42.92it/s]
C09_lr=2e-4 | 30/30 VAL: 100%|██████████| 54/54 [00:00<00:00, 72.54it/s]

[C09_lr=2e-4] ep30 | TL 0.1529 | VL 0.6579 | VD 0.6333 | VI 0.5934 | LR 2.00e-04

C09_lr=2e-4 | TEST (best): 100%|██████████| 54/54 [00:00<00:00, 69.73it/s]

Saved runs under: /content/drive/MyDrive/burned_area_outputs_deeplabv3
C00_BASE -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C00_BASE/history.csv
  best_epoch: 30 | test_dice: 0.6615 | test_iou: 0.6203
C01_loss=BCE -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C01_loss=BCE/history.csv
  best_epoch: 30 | test_dice: 0.6485 | test_iou: 0.6094
C02_loss=Focal+Dice -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C02_loss=Focal+Dice/history.csv
  best_epoch: 30 | test_dice: 0.6784 | test_iou: 0.6344
C03_sched=plateau -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C03_sched=plateau/history.csv
  best_epoch: 27 | test_dice: 0.6666 | test_iou: 0.6256
C04_amp=on -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C04_amp=on/history.csv
  best_epoch: 29 | test_dice: 0.6609 | test_iou: 0.6218
C05_clip=1.0 -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C05_clip=1.0/history.csv
  best_epoch: 29 | test_dice: 0.6958 | test_iou: 0.6617
C06_freeze=2ep -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C06_freeze=2ep/history.csv
  best_epoch: 30 | test_dice: 0.6632 | test_iou: 0.6232
C07_ES=on -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C07_ES=on/history.csv
  best_epoch: 22 | test_dice: 0.6610 | test_iou: 0.6212
C08_lr=5e-5 -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C08_lr=5e-5/history.csv
  best_epoch: 30 | test_dice: 0.6352 | test_iou: 0.5932
C09_lr=2e-4 -> /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4
  best: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/best.pth
  last: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/last.pth
  hist: /content/drive/MyDrive/burned_area_outputs_deeplabv3/C09_lr=2e-4/history.csv
  best_epoch: 22 | test_dice: 0.6393 | test_iou: 0.5981

# **TEST-UNET**

In [ ]:
!pip install segmentation_models_pytorch

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ============================================
# STEP 1) TILING + NEGATIVE SAMPLING + EVENT-ID FILENAMES
# ============================================

!pip -q install segmentation_models_pytorch

from google.colab import drive
drive.mount('/content/drive')

import os, zipfile, random
import numpy as np
import rasterio
from rasterio.windows import Window
from tqdm import tqdm

ZIP_ROOT  = "/content/drive/MyDrive/burned_area"
BASE_ROOT = "/content/burned_area"
OUT       = "/content/burned_tiles"

os.makedirs(BASE_ROOT, exist_ok=True)
os.makedirs(f"{OUT}/x", exist_ok=True)
os.makedirs(f"{OUT}/y", exist_ok=True)

# --- unzip all parts ---
for fname in sorted(os.listdir(ZIP_ROOT)):
    if fname.endswith(".zip"):
        part_name = fname.replace(".zip", "")
        out_dir = os.path.join(BASE_ROOT, part_name)
        os.makedirs(out_dir, exist_ok=True)
        print(f"Açılıyor: {fname}")
        with zipfile.ZipFile(os.path.join(ZIP_ROOT, fname), "r") as z:
            z.extractall(out_dir)

TILE = 256

# NEGATIVE SAMPLING SETTINGS
KEEP_NEG_RATIO = 0.15   # 0.10-0.30 arası deneyebilirsin
NEG_PER_POS_CAP = 2.0   # negatifleri pozitiflere göre üstten kıs (örn 2.0 => en fazla 2x negatif)

rng = np.random.default_rng(42)

pos_count = 0
neg_count = 0

# --- iterate PART1..PART5 ---
for part in sorted(os.listdir(BASE_ROOT)):
    part_dir = os.path.join(BASE_ROOT, part)
    if not os.path.isdir(part_dir):
        continue

    # inside: real dataset folder
    subdirs = [d for d in os.listdir(part_dir) if os.path.isdir(os.path.join(part_dir, d))]
    if not subdirs:
        continue
    ROOT = os.path.join(part_dir, subdirs[0])
    print(f"\nİşleniyor: {ROOT}")

    # events
    for event in tqdm(sorted(os.listdir(ROOT))):
        evdir = os.path.join(ROOT, event)
        if not os.path.isdir(evdir):
            continue

        masks = [f for f in os.listdir(evdir) if "mask" in f.lower()]
        s2s = [
            f for f in os.listdir(evdir)
            if f.lower().startswith("sentinel2_")
            and f.lower().endswith(".tiff")
            and "cloud" not in f.lower()
        ]
        if not masks or not s2s:
            continue

        # mask read (assume same H,W as images)
        with rasterio.open(os.path.join(evdir, masks[0])) as msk_src:
            mask_arr = msk_src.read(1)

        for s2 in sorted(s2s):
            with rasterio.open(os.path.join(evdir, s2)) as src:
                if src.count < 3:
                    continue

                H, W = src.height, src.width

                for top in range(0, H - TILE + 1, TILE):
                    for left in range(0, W - TILE + 1, TILE):
                        w = Window(left, top, TILE, TILE)

                        img_patch = src.read([1, 2, 3], window=w).astype(np.float32)  # (3,H,W)
                        mask_patch = mask_arr[top:top+TILE, left:left+TILE]

                        is_pos = (mask_patch > 0).any()

                        # --- balance logic ---
                        if not is_pos:
                            # random downsample negatives
                            if rng.random() > KEEP_NEG_RATIO:
                                continue
                            # cap negatives vs positives
                            if pos_count > 0 and neg_count >= int(NEG_PER_POS_CAP * pos_count):
                                continue

                        # event id & spatial id in filename
                        base_id = f"{part}__{event}__{os.path.splitext(s2)[0]}__t{top}_l{left}"
                        np.save(f"{OUT}/x/{base_id}.npy", img_patch)
                        np.save(f"{OUT}/y/{base_id}.npy", mask_patch)

                        if is_pos:
                            pos_count += 1
                        else:
                            neg_count += 1

print(f"\nSaved patches => pos={pos_count}, neg={neg_count}, total={pos_count+neg_count}")
print("OUT:", OUT)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.8/154.8 kB 4.1 MB/s eta 0:00:00
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Açılıyor: Satellite_burned_area_dataset_part1.zip
Açılıyor: Satellite_burned_area_dataset_part2.zip
Açılıyor: Satellite_burned_area_dataset_part3.zip
Açılıyor: Satellite_burned_area_dataset_part4.zip
Açılıyor: Satellite_burned_area_dataset_part5.zip

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part1/Satellite_burned_area_dataset_part1

  0%|          | 0/17 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/rasterio/__init__.py:356: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
  6%|▌         | 1/17 [00:00<00:15,  1.02it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 12%|█▏        | 2/17 [00:01<00:12,  1.21it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 18%|█▊        | 3/17 [00:02<00:11,  1.25it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 24%|██▎       | 4/17 [00:03<00:10,  1.24it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 29%|██▉       | 5/17 [00:04<00:09,  1.26it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 35%|███▌      | 6/17 [00:04<00:08,  1.31it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 41%|████      | 7/17 [00:05<00:07,  1.29it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 47%|████▋     | 8/17 [00:06<00:06,  1.30it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 53%|█████▎    | 9/17 [00:06<00:05,  1.41it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 59%|█████▉    | 10/17 [00:07<00:04,  1.53it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 65%|██████▍   | 11/17 [00:07<00:03,  1.74it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-29.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 71%|███████   | 12/17 [00:10<00:05,  1.20s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-29.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 76%|███████▋  | 13/17 [00:13<00:06,  1.69s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 82%|████████▏ | 14/17 [00:13<00:03,  1.27s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 88%|████████▊ | 15/17 [00:15<00:02,  1.41s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 94%|█████████▍| 16/17 [00:15<00:01,  1.09s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-26.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-16.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 17/17 [00:15<00:00,  1.08it/s]

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part2/Satellite_burned_area_dataset_part2

  0%|          | 0/11 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
  9%|▉         | 1/11 [00:00<00:05,  1.83it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 18%|█▊        | 2/11 [00:02<00:11,  1.26s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 27%|██▋       | 3/11 [00:03<00:09,  1.13s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 36%|███▋      | 4/11 [00:03<00:05,  1.36it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 45%|████▌     | 5/11 [00:03<00:03,  1.90it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 55%|█████▍    | 6/11 [00:03<00:02,  2.49it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-28.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 64%|██████▎   | 7/11 [00:03<00:01,  3.12it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-12.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 73%|███████▎  | 8/11 [00:15<00:11,  3.97s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-04-25.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-05-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 82%|████████▏ | 9/11 [00:15<00:05,  2.77s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 91%|█████████ | 10/11 [00:16<00:02,  2.10s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-16.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-08-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 11/11 [00:17<00:00,  1.58s/it]

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part3/Satellite_burned_area_dataset_part3

  0%|          | 0/29 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
  3%|▎         | 1/29 [00:00<00:16,  1.74it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-22.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-11.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 10%|█         | 3/29 [00:00<00:05,  4.71it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-11.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 14%|█▍        | 4/29 [00:00<00:04,  5.35it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-11.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 17%|█▋        | 5/29 [00:01<00:06,  3.89it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-26.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-26.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 24%|██▍       | 7/29 [00:01<00:03,  5.87it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-13.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 28%|██▊       | 8/29 [00:02<00:06,  3.02it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 31%|███       | 9/29 [00:06<00:28,  1.41s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-29.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 34%|███▍      | 10/29 [00:08<00:28,  1.49s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 38%|███▊      | 11/29 [00:08<00:21,  1.20s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 41%|████▏     | 12/29 [00:08<00:15,  1.10it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-18.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 52%|█████▏    | 15/29 [00:09<00:06,  2.16it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-02.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 55%|█████▌    | 16/29 [00:09<00:05,  2.37it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-23.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 59%|█████▊    | 17/29 [00:09<00:04,  2.53it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-23.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 62%|██████▏   | 18/29 [00:10<00:03,  2.75it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-08.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 66%|██████▌   | 19/29 [00:11<00:05,  1.75it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part4/Satellite_burned_area_dataset_part4

  0%|          | 0/7 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 14%|█▍        | 1/7 [00:03<00:20,  3.39s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-05.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 29%|██▊       | 2/7 [00:04<00:11,  2.31s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-05-01.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-10.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-20.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 43%|████▎     | 3/7 [00:07<00:08,  2.20s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 57%|█████▋    | 4/7 [00:10<00:07,  2.54s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 71%|███████▏  | 5/7 [00:12<00:05,  2.66s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-17.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 86%|████████▌ | 6/7 [00:15<00:02,  2.54s/it]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 7/7 [00:17<00:00,  2.46s/it]

İşleniyor: /content/burned_area/Satellite_burned_area_dataset_part5/Satellite_burned_area_dataset_part5

  0%|          | 0/9 [00:00<?, ?it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-06-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-04.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 11%|█         | 1/9 [00:00<00:05,  1.44it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-03.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-06.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-15.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 22%|██▏       | 2/9 [00:01<00:06,  1.12it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-08-23.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 33%|███▎      | 3/9 [00:01<00:03,  1.84it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 44%|████▍     | 4/9 [00:02<00:02,  2.26it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 56%|█████▌    | 5/9 [00:02<00:01,  2.55it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-07-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-19.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 67%|██████▋   | 6/9 [00:02<00:01,  2.62it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-09-14.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2017-10-24.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 78%|███████▊  | 7/9 [00:03<00:00,  2.99it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-06-09.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2018-07-27.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
 89%|████████▉ | 8/9 [00:03<00:00,  1.93it/s]WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2019-05-31.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in sentinel2_2019-06-30.tiff: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
WARNING:rasterio._env:CPLE_AppDefined in TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
100%|██████████| 9/9 [00:07<00:00,  1.19it/s]

Saved patches => pos=2330, neg=544, total=2874
OUT: /content/burned_tiles

In [ ]:
import torch
from torch.utils.data import Dataset
import numpy as np
import os

class BurnedPatchDataset(Dataset):
    def __init__(self, tiles_dir, ids, normalize=True):
        self.tiles_dir = tiles_dir
        self.ids = ids
        self.normalize = normalize

    def __len__(self):
        return len(self.ids)

    def __getitem__(self, idx):
        id_ = self.ids[idx]

        x = np.load(os.path.join(self.tiles_dir, "x", f"{id_}.npy"))
        y = np.load(os.path.join(self.tiles_dir, "y", f"{id_}.npy"))

        # (H,W,C) gelirse düzelt
        if x.ndim == 3 and x.shape[-1] == 3:
            x = np.transpose(x, (2, 0, 1))

        x = x.astype(np.float32)
        if self.normalize:
            x = x / 255.0

        y = (y > 0).astype(np.int64)

        return torch.from_numpy(x), torch.from_numpy(y)

In [ ]:
import os
import random
import numpy as np

TILES_DIR = "/content/burned_tiles"
x_dir = os.path.join(TILES_DIR, "x")
y_dir = os.path.join(TILES_DIR, "y")

ids = sorted([os.path.splitext(f)[0] for f in os.listdir(x_dir) if f.endswith(".npy")])

random.seed(42)
random.shuffle(ids)

n = len(ids)
train_ids = ids[:int(0.7*n)]
val_ids   = ids[int(0.7*n):int(0.85*n)]
test_ids  = ids[int(0.85*n):]

print("Train:", len(train_ids), "Val:", len(val_ids), "Test:", len(test_ids))

Train: 2011 Val: 431 Test: 432

In [ ]:
from torch.utils.data import DataLoader
TILES_DIR = "/content/burned_tiles"
train_ds = BurnedPatchDataset(TILES_DIR, train_ids)
val_ds   = BurnedPatchDataset(TILES_DIR, val_ids)
test_ds  = BurnedPatchDataset(TILES_DIR, test_ids)

train_loader = DataLoader(train_ds, batch_size=8, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=8, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=8, shuffle=False)

In [ ]:
import os, glob, re, math
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

RUNS_DIR = "/content/drive/MyDrive/burned_area_outputs_unet"
DATA_ROOT = "/content/burned_tiles"   # <-- eğitimde kullandığın tile dataset root (x/y olan)
print("RUNS_DIR exists:", os.path.exists(RUNS_DIR), RUNS_DIR)
print("DATA_ROOT exists:", os.path.exists(DATA_ROOT), DATA_ROOT)

device: cuda
RUNS_DIR exists: True /content/drive/MyDrive/burned_area_outputs_unet
DATA_ROOT exists: True /content/burned_tiles

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

import os, glob, math
import numpy as np
import torch
import segmentation_models_pytorch as smp
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

RUNS_DIR = "/content/drive/MyDrive/burned_area_outputs_unet"
runs = sorted([d for d in glob.glob(os.path.join(RUNS_DIR, "*")) if os.path.isdir(d)])
print("Found runs:", len(runs))
for r in runs:
    print(" -", os.path.basename(r))

def pick_ckpt(run_dir):
    best = os.path.join(run_dir, "best.pth")
    last = os.path.join(run_dir, "last.pth")
    if os.path.exists(best): return best
    if os.path.exists(last): return last
    # fallback: herhangi bir .pth/.pt bul
    cands = sorted(glob.glob(os.path.join(run_dir, "*.pth")) + glob.glob(os.path.join(run_dir, "*.pt")))
    return cands[0] if len(cands) else None

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
device: cuda
Found runs: 10
 - C00_BASE
 - C01_loss=BCE
 - C02_loss=Focal+Dice
 - C03_sched=plateau
 - C04_amp=on
 - C05_clip=1.0
 - C06_freeze=2ep
 - C07_ES=on
 - C08_lr=5e-5
 - C09_lr=2e-4

In [ ]:
@torch.no_grad()
def dice_iou_from_logits(logits, y, thr=0.5, eps=1e-7):
    probs = torch.sigmoid(logits)
    pred = (probs > thr).float()
    inter = (pred * y).sum(dim=(1,2,3))

    union_d = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3))
    dice = ((2*inter + eps) / (union_d + eps)).mean().item()

    union_i = pred.sum(dim=(1,2,3)) + y.sum(dim=(1,2,3)) - inter
    iou = ((inter + eps) / (union_i + eps)).mean().item()
    return dice, iou

@torch.no_grad()
def eval_dice_iou(model, loader, thr=0.5, desc="TEST"):
    model.eval()
    dices, ious = [], []
    for x, y in tqdm(loader, desc=desc):
        x = x.to(device, non_blocking=True)
        y = y.unsqueeze(1).float().to(device, non_blocking=True)
        logits = model(x)
        d, i = dice_iou_from_logits(logits, y, thr=thr)
        dices.append(d); ious.append(i)
    return float(np.mean(dices)), float(np.mean(ious))

# **TEST-İKİ MODEL**

In [ ]:
import os, json, glob
import pandas as pd
import torch
import segmentation_models_pytorch as smp

# ------------------------------------------------------------
# 0) MODEL BUILDER (arch + encoder/weights)
# ------------------------------------------------------------
def build_model_any(arch: str, encoder: str, weights: str):
    arch = arch.lower()
    if arch == "unet":
        return smp.Unet(
            encoder_name=encoder,
            encoder_weights=weights,
            in_channels=3,
            classes=1,
        )
    if arch in ["deeplabv3", "deeplabv3plus", "deeplabv3+"]:
        # Eğitimde DeepLabV3 (plus değil) kullandıysan şunu yap:
        # return smp.DeepLabV3(...)
        return smp.DeepLabV3Plus(
            encoder_name=encoder,
            encoder_weights=weights,
            in_channels=3,
            classes=1,
        )
    raise ValueError(f"Unknown arch={arch}")

# ------------------------------------------------------------
# 1) Run isminden açıklama çıkar (C01_loss=BCE gibi)
# ------------------------------------------------------------
def parse_ablation_from_name(run_name: str):
    if run_name == "C00_BASE":
        return {"ablation_group":"BASE","change_applied":"Baseline config","changed_param":"-","changed_value":"-"}

    tag = run_name.split("_", 1)[-1] if "_" in run_name else run_name

    mapping = {
        "loss=BCE": ("LOSS", "Loss = BCEWithLogits", "loss", "bce"),
        "loss=Focal+Dice": ("LOSS", "Loss = Focal + Dice", "loss", "focal_dice"),
        "sched=plateau": ("SCHED", "Scheduler = ReduceLROnPlateau", "scheduler", "plateau"),
        "amp=on": ("AMP", "AMP = enabled", "amp", True),
        "clip=1.0": ("REG", "Grad clip = 1.0", "grad_clip", 1.0),
        "freeze=2ep": ("FINETUNE", "Encoder frozen for 2 epochs", "freeze_epochs", 2),
        "ES=on": ("ES", "Early stopping = enabled", "early_stopping.enabled", True),
        "lr=5e-5": ("OPT", "LR = 5e-5", "optimizer.lr", 5e-5),
        "lr=2e-4": ("OPT", "LR = 2e-4", "optimizer.lr", 2e-4),
    }
    if tag in mapping:
        g, desc, p, v = mapping[tag]
        return {"ablation_group": g, "change_applied": desc, "changed_param": p, "changed_value": v}

    return {
        "ablation_group": "OTHER",
        "change_applied": f"Custom change: {tag}",
        "changed_param": tag.split("=")[0] if "=" in tag else tag,
        "changed_value": tag.split("=")[1] if "=" in tag else "-"
    }

# ------------------------------------------------------------
# 2) config.json özet
# ------------------------------------------------------------
def cfg_summary(cfg: dict):
    encoder  = cfg.get("encoder", "resnet18")
    weights  = cfg.get("weights", "imagenet")

    loss_cfg = cfg.get("loss", {})
    loss_name = loss_cfg.get("name", "unknown")
    if loss_name == "bce":
        loss_str = "BCE"
    elif loss_name == "bce_dice":
        loss_str = f"BCE+Dice(w_bce={loss_cfg.get('w_bce',1.0)}, w_dice={loss_cfg.get('w_dice',1.0)})"
    elif loss_name == "focal_dice":
        loss_str = f"Focal(a={loss_cfg.get('alpha',0.8)}, g={loss_cfg.get('gamma',2.0)})+Dice"
    else:
        loss_str = str(loss_cfg)

    opt_cfg = cfg.get("optimizer", {})
    opt_name = opt_cfg.get("name", "unknown")
    lr = opt_cfg.get("lr", None)
    wd = opt_cfg.get("weight_decay", None)

    sched_cfg = cfg.get("scheduler", None)
    if sched_cfg is None:
        sched_str = "None"
    else:
        sname = sched_cfg.get("name", "unknown")
        if sname == "plateau":
            sched_str = f"Plateau(factor={sched_cfg.get('factor',0.5)}, patience={sched_cfg.get('patience',2)})"
        elif sname == "cosine":
            sched_str = f"Cosine(T_max={sched_cfg.get('T_max','?')})"
        else:
            sched_str = str(sched_cfg)

    amp = bool(cfg.get("amp", False))
    grad_clip = cfg.get("grad_clip", None)
    freeze_epochs = int(cfg.get("freeze_epochs", 0))
    es_cfg = cfg.get("early_stopping", {})
    es_enabled = bool(es_cfg.get("enabled", False))

    return {
        "encoder": encoder,
        "weights": weights,
        "loss": loss_str,
        "optimizer": opt_name,
        "lr": lr,
        "weight_decay": wd,
        "scheduler": sched_str,
        "amp": amp,
        "grad_clip": grad_clip,
        "freeze_epochs": freeze_epochs,
        "early_stopping": es_enabled
    }

# ------------------------------------------------------------
# 3) RUN klasörlerini bul (RUNS_DIR altındaki tüm run'lar)
# ------------------------------------------------------------
def list_runs(RUNS_DIR: str):
    runs = sorted([d for d in glob.glob(os.path.join(RUNS_DIR, "*")) if os.path.isdir(d)])
    return runs

# ------------------------------------------------------------
# 4) ANA FONKSİYON: belirli arch için test et ve DF döndür
# ------------------------------------------------------------
def test_saved_runs(
    arch: str,
    RUNS_DIR: str,
    device,
    test_loader,
    pick_ckpt_fn,
    eval_fn,
    thr: float = 0.5,
    save_csv: bool = True,
    out_csv_name: str | None = None,
    verbose: bool = True
):
    """
    arch: 'unet' veya 'deeplabv3'
    RUNS_DIR: /content/drive/MyDrive/burned_area_outputs_unet gibi
    pick_ckpt_fn: pick_ckpt fonksiyonun
    eval_fn: eval_dice_iou fonksiyonun
    """

    runs = list_runs(RUNS_DIR)
    if verbose:
        print("ARCH:", arch)
        print("RUNS_DIR:", RUNS_DIR)
        print("Found runs:", len(runs))

    rows = []

    for run_dir in runs:
        name = os.path.basename(run_dir)

        ckpt_path = pick_ckpt_fn(run_dir)
        if ckpt_path is None:
            if verbose: print("[SKIP] no ckpt:", name)
            continue

        # config
        cfg_path = os.path.join(run_dir, "config.json")
        cfg = {}
        if os.path.exists(cfg_path):
            with open(cfg_path, "r") as f:
                cfg = json.load(f)

        summ = cfg_summary(cfg) if cfg else {
            "encoder":"resnet18","weights":"imagenet","loss":"-","optimizer":"-","lr":None,
            "weight_decay":None,"scheduler":"-","amp":None,"grad_clip":None,"freeze_epochs":None,"early_stopping":None
        }

        abl = parse_ablation_from_name(name)

        # ckpt -> state_dict
        ckpt = torch.load(ckpt_path, map_location="cpu")
        sd = ckpt["model"] if (isinstance(ckpt, dict) and "model" in ckpt) else ckpt
        sd = {k.replace("module.", ""): v for k, v in sd.items()}

        # model
        model = build_model_any(arch, summ["encoder"], summ["weights"]).to(device)
        model.load_state_dict(sd, strict=True)
        model.eval()

        # test
        dice, iou = eval_fn(model, test_loader, thr=thr, desc=f"{name} TEST")
        if verbose:
            print(f"[OK] {name} | arch={arch} | {os.path.basename(ckpt_path)} | Dice={dice:.4f} | IoU={iou:.4f}")

        rows.append({
            "run_id": name.split("_")[0] if "_" in name else name,
            "run_tag": name.split("_", 1)[1] if "_" in name else name,

            "arch": arch,
            "ablation_group": abl["ablation_group"],
            "change_applied": abl["change_applied"],
            "changed_param": abl["changed_param"],
            "changed_value": abl["changed_value"],

            "encoder": summ["encoder"],
            "weights": summ["weights"],
            "loss": summ["loss"],
            "optimizer": summ["optimizer"],
            "lr": summ["lr"],
            "weight_decay": summ["weight_decay"],
            "scheduler": summ["scheduler"],
            "amp": summ["amp"],
            "grad_clip": summ["grad_clip"],
            "freeze_epochs": summ["freeze_epochs"],
            "early_stopping": summ["early_stopping"],

            "ckpt_file": os.path.basename(ckpt_path),
            "test_dice@0.5": dice,
            "test_iou@0.5": iou,
        })

    df = pd.DataFrame(rows)
    if len(df) == 0:
        if verbose:
            print("[WARN] No rows produced. Check RUNS_DIR / ckpt names.")
        return df

    df = df.sort_values("test_iou@0.5", ascending=False).reset_index(drop=True)
    df.insert(0, "rank", range(1, len(df) + 1))

    # save
    if save_csv:
        if out_csv_name is None:
            out_csv_name = f"test_results_{arch}_readable.csv"
        out_csv = os.path.join(RUNS_DIR, out_csv_name)
        df.to_csv(out_csv, index=False)
        if verbose:
            print("\nSaved:", out_csv)

    return df

# ------------------------------------------------------------
# 5) Kullanım örnekleri
# ------------------------------------------------------------
# UNET_RUNS_DIR = "/content/drive/MyDrive/burned_area_outputs_unet"
# DLV3_RUNS_DIR = "/content/drive/MyDrive/burned_area_outputs_deeplab"

# df_unet = test_saved_runs("unet", UNET_RUNS_DIR, device, test_loader, pick_ckpt, eval_dice_iou)
# df_dlv3 = test_saved_runs("deeplabv3", DLV3_RUNS_DIR, device, test_loader, pick_ckpt, eval_dice_iou)

# df_unet.head(), df_dlv3.head()

In [ ]:
def make_slide_df(df: pd.DataFrame, mode: str = "medium") -> pd.DataFrame:
    """
    mode:
      - "short"  : en minimal
      - "medium" : slayt için ideal (önerilen)
    """
    # güvenlik: df boşsa direkt dön
    if df is None or len(df) == 0:
        return df

    if mode == "short":
        cols = [
            "rank",
            "run_tag",
            "change_applied",
            "test_iou@0.5",
            "test_dice@0.5",
        ]
    else:  # "medium"
        cols = [
            "rank",
            "run_id",
            "run_tag",
            "change_applied",
            "encoder",
            "loss",
            "lr",
            "test_iou@0.5",
            "test_dice@0.5",
        ]

    # df içinde olmayan sütun varsa drop etmeden seçebilmek için:
    cols = [c for c in cols if c in df.columns]

    out = df[cols].copy()

    # okunurluk: metrikleri kısalt
    if "test_iou@0.5" in out.columns:
        out["test_iou@0.5"] = out["test_iou@0.5"].astype(float).round(3)
    if "test_dice@0.5" in out.columns:
        out["test_dice@0.5"] = out["test_dice@0.5"].astype(float).round(3)
    if "lr" in out.columns:
        # LR'yi bilimsel formatla yazdır
        out["lr"] = out["lr"].apply(lambda x: f"{x:.1e}" if pd.notnull(x) else "-")

    # run_tag uzun ise kısalt
    if "run_tag" in out.columns:
        out["run_tag"] = out["run_tag"].astype(str).str.replace("loss=", "loss:", regex=False)
        out["run_tag"] = out["run_tag"].astype(str).str.replace("sched=", "sched:", regex=False)

    # change_applied uzun ise (slayta sığsın)
    if "change_applied" in out.columns:
        out["change_applied"] = out["change_applied"].astype(str).str.replace("Scheduler = ReduceLROnPlateau", "Scheduler: Plateau", regex=False)
        out["change_applied"] = out["change_applied"].astype(str).str.replace("Loss = BCEWithLogits", "Loss: BCE", regex=False)
        out["change_applied"] = out["change_applied"].astype(str).str.replace("Loss = Focal + Dice", "Loss: Focal+Dice", regex=False)
        out["change_applied"] = out["change_applied"].astype(str).str.replace("Encoder frozen for 2 epochs", "Freeze encoder (2 ep)", regex=False)
        out["change_applied"] = out["change_applied"].astype(str).str.replace("Grad clip = 1.0", "Grad clip: 1.0", regex=False)
        out["change_applied"] = out["change_applied"].astype(str).str.replace("Early stopping = enabled", "Early stopping: ON", regex=False)

    return out

In [ ]:
df_unet = test_saved_runs("unet", "/content/drive/MyDrive/burned_area_outputs_unet",
                          device, test_loader, pick_ckpt, eval_dice_iou)

ARCH: unet
RUNS_DIR: /content/drive/MyDrive/burned_area_outputs_unet
Found runs: 10

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/46.8M [00:00<?, ?B/s]

C00_BASE TEST: 100%|██████████| 54/54 [00:01<00:00, 28.06it/s]

[OK] C00_BASE | arch=unet | best.pth | Dice=0.6421 | IoU=0.6005

C01_loss=BCE TEST: 100%|██████████| 54/54 [00:00<00:00, 60.97it/s]

[OK] C01_loss=BCE | arch=unet | best.pth | Dice=0.6297 | IoU=0.5899

C02_loss=Focal+Dice TEST: 100%|██████████| 54/54 [00:00<00:00, 64.32it/s]

[OK] C02_loss=Focal+Dice | arch=unet | best.pth | Dice=0.6484 | IoU=0.6066

C03_sched=plateau TEST: 100%|██████████| 54/54 [00:00<00:00, 65.78it/s]

[OK] C03_sched=plateau | arch=unet | best.pth | Dice=0.6244 | IoU=0.5835

C04_amp=on TEST: 100%|██████████| 54/54 [00:00<00:00, 65.26it/s]

[OK] C04_amp=on | arch=unet | best.pth | Dice=0.6441 | IoU=0.6029

C05_clip=1.0 TEST: 100%|██████████| 54/54 [00:00<00:00, 64.32it/s]

[OK] C05_clip=1.0 | arch=unet | best.pth | Dice=0.6533 | IoU=0.6101

C06_freeze=2ep TEST: 100%|██████████| 54/54 [00:00<00:00, 64.87it/s]

[OK] C06_freeze=2ep | arch=unet | best.pth | Dice=0.6521 | IoU=0.6135

C07_ES=on TEST: 100%|██████████| 54/54 [00:00<00:00, 63.54it/s]

[OK] C07_ES=on | arch=unet | best.pth | Dice=0.6212 | IoU=0.5802

C08_lr=5e-5 TEST: 100%|██████████| 54/54 [00:00<00:00, 64.72it/s]

[OK] C08_lr=5e-5 | arch=unet | best.pth | Dice=0.6077 | IoU=0.5639

C09_lr=2e-4 TEST: 100%|██████████| 54/54 [00:00<00:00, 61.38it/s]

[OK] C09_lr=2e-4 | arch=unet | best.pth | Dice=0.6545 | IoU=0.6128

Saved: /content/drive/MyDrive/burned_area_outputs_unet/test_results_unet_readable.csv

In [ ]:
df_unet

,rank,run_id,run_tag,arch,ablation_group,change_applied,changed_param,changed_value,encoder,weights,...,lr,weight_decay,scheduler,amp,grad_clip,freeze_epochs,early_stopping,ckpt_file,test_dice@0.5,test_iou@0.5
0,1,C06,freeze=2ep,unet,FINETUNE,Encoder frozen for 2 epochs,freeze_epochs,2,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,2,False,best.pth,0.652067,0.613453
1,2,C09,lr=2e-4,unet,OPT,LR = 2e-4,optimizer.lr,0.0002,resnet18,imagenet,...,0.00020,0.0001,None,False,NaN,0,False,best.pth,0.654528,0.612849
2,3,C05,clip=1.0,unet,REG,Grad clip = 1.0,grad_clip,1.0,resnet18,imagenet,...,0.00010,0.0001,None,False,1.0,0,False,best.pth,0.653321,0.610096
3,4,C02,loss=Focal+Dice,unet,LOSS,Loss = Focal + Dice,loss,focal_dice,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,False,best.pth,0.648355,0.606606
4,5,C04,amp=on,unet,AMP,AMP = enabled,amp,True,resnet18,imagenet,...,0.00010,0.0001,None,True,NaN,0,False,best.pth,0.644134,0.602910
5,6,C00,BASE,unet,BASE,Baseline config,-,-,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,False,best.pth,0.642110,0.600501
6,7,C01,loss=BCE,unet,LOSS,Loss = BCEWithLogits,loss,bce,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,False,best.pth,0.629697,0.589902
7,8,C03,sched=plateau,unet,SCHED,Scheduler = ReduceLROnPlateau,scheduler,plateau,resnet18,imagenet,...,0.00010,0.0001,"Plateau(factor=0.5, patience=2)",False,NaN,0,False,best.pth,0.624435,0.583495
8,9,C07,ES=on,unet,ES,Early stopping = enabled,early_stopping.enabled,True,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,True,best.pth,0.621173,0.580221
9,10,C08,lr=5e-5,unet,OPT,LR = 5e-5,optimizer.lr,0.00005,resnet18,imagenet,...,0.00005,0.0001,None,False,NaN,0,False,best.pth,0.607662,0.563928

In [ ]:
df_dlv3 = test_saved_runs("deeplabv3", "/content/drive/MyDrive/burned_area_outputs_deeplabv3",
                          device, test_loader, pick_ckpt, eval_dice_iou)

ARCH: deeplabv3
RUNS_DIR: /content/drive/MyDrive/burned_area_outputs_deeplabv3
Found runs: 10

C00_BASE TEST: 100%|██████████| 54/54 [00:01<00:00, 51.16it/s]

[OK] C00_BASE | arch=deeplabv3 | best.pth | Dice=0.6615 | IoU=0.6203

C01_loss=BCE TEST: 100%|██████████| 54/54 [00:00<00:00, 64.03it/s]

[OK] C01_loss=BCE | arch=deeplabv3 | best.pth | Dice=0.6485 | IoU=0.6094

C02_loss=Focal+Dice TEST: 100%|██████████| 54/54 [00:00<00:00, 65.59it/s]

[OK] C02_loss=Focal+Dice | arch=deeplabv3 | best.pth | Dice=0.6784 | IoU=0.6344

C03_sched=plateau TEST: 100%|██████████| 54/54 [00:00<00:00, 67.32it/s]

[OK] C03_sched=plateau | arch=deeplabv3 | best.pth | Dice=0.6666 | IoU=0.6256

C04_amp=on TEST: 100%|██████████| 54/54 [00:00<00:00, 67.20it/s]

[OK] C04_amp=on | arch=deeplabv3 | best.pth | Dice=0.6608 | IoU=0.6218

C05_clip=1.0 TEST: 100%|██████████| 54/54 [00:00<00:00, 64.91it/s]

[OK] C05_clip=1.0 | arch=deeplabv3 | best.pth | Dice=0.6958 | IoU=0.6617

C06_freeze=2ep TEST: 100%|██████████| 54/54 [00:00<00:00, 67.71it/s]

[OK] C06_freeze=2ep | arch=deeplabv3 | best.pth | Dice=0.6632 | IoU=0.6232

C07_ES=on TEST: 100%|██████████| 54/54 [00:00<00:00, 67.26it/s]

[OK] C07_ES=on | arch=deeplabv3 | best.pth | Dice=0.6610 | IoU=0.6212

C08_lr=5e-5 TEST: 100%|██████████| 54/54 [00:00<00:00, 64.31it/s]

[OK] C08_lr=5e-5 | arch=deeplabv3 | best.pth | Dice=0.6352 | IoU=0.5932

C09_lr=2e-4 TEST: 100%|██████████| 54/54 [00:00<00:00, 68.01it/s]

[OK] C09_lr=2e-4 | arch=deeplabv3 | best.pth | Dice=0.6393 | IoU=0.5981

Saved: /content/drive/MyDrive/burned_area_outputs_deeplabv3/test_results_deeplabv3_readable.csv

In [ ]:
df_dlv3

,rank,run_id,run_tag,arch,ablation_group,change_applied,changed_param,changed_value,encoder,weights,...,lr,weight_decay,scheduler,amp,grad_clip,freeze_epochs,early_stopping,ckpt_file,test_dice@0.5,test_iou@0.5
0,1,C05,clip=1.0,deeplabv3,REG,Grad clip = 1.0,grad_clip,1.0,resnet18,imagenet,...,0.00010,0.0001,None,False,1.0,0,False,best.pth,0.695799,0.661692
1,2,C02,loss=Focal+Dice,deeplabv3,LOSS,Loss = Focal + Dice,loss,focal_dice,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,False,best.pth,0.678381,0.634358
2,3,C03,sched=plateau,deeplabv3,SCHED,Scheduler = ReduceLROnPlateau,scheduler,plateau,resnet18,imagenet,...,0.00010,0.0001,"Plateau(factor=0.5, patience=2)",False,NaN,0,False,best.pth,0.666558,0.625595
3,4,C06,freeze=2ep,deeplabv3,FINETUNE,Encoder frozen for 2 epochs,freeze_epochs,2,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,2,False,best.pth,0.663208,0.623197
4,5,C04,amp=on,deeplabv3,AMP,AMP = enabled,amp,True,resnet18,imagenet,...,0.00010,0.0001,None,True,NaN,0,False,best.pth,0.660798,0.621781
5,6,C07,ES=on,deeplabv3,ES,Early stopping = enabled,early_stopping.enabled,True,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,True,best.pth,0.661020,0.621191
6,7,C00,BASE,deeplabv3,BASE,Baseline config,-,-,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,False,best.pth,0.661517,0.620346
7,8,C01,loss=BCE,deeplabv3,LOSS,Loss = BCEWithLogits,loss,bce,resnet18,imagenet,...,0.00010,0.0001,None,False,NaN,0,False,best.pth,0.648450,0.609371
8,9,C09,lr=2e-4,deeplabv3,OPT,LR = 2e-4,optimizer.lr,0.0002,resnet18,imagenet,...,0.00020,0.0001,None,False,NaN,0,False,best.pth,0.639304,0.598097
9,10,C08,lr=5e-5,deeplabv3,OPT,LR = 5e-5,optimizer.lr,0.00005,resnet18,imagenet,...,0.00005,0.0001,None,False,NaN,0,False,best.pth,0.635245,0.593161

In [ ]:
slide_unet = make_slide_df(df_unet, mode="medium")
slide_unet

,rank,run_id,run_tag,change_applied,encoder,loss,lr,test_iou@0.5,test_dice@0.5
0,1,C06,freeze=2ep,Freeze encoder (2 ep),resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.613,0.652
1,2,C09,lr=2e-4,LR = 2e-4,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",2.0e-04,0.613,0.655
2,3,C05,clip=1.0,Grad clip: 1.0,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.610,0.653
3,4,C02,loss:Focal+Dice,Loss: Focal+Dice,resnet18,"Focal(a=0.8, g=2.0)+Dice",1.0e-04,0.607,0.648
4,5,C04,amp=on,AMP = enabled,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.603,0.644
5,6,C00,BASE,Baseline config,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.601,0.642
6,7,C01,loss:BCE,Loss: BCE,resnet18,BCE,1.0e-04,0.590,0.630
7,8,C03,sched:plateau,Scheduler: Plateau,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.583,0.624
8,9,C07,ES=on,Early stopping: ON,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.580,0.621
9,10,C08,lr=5e-5,LR = 5e-5,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",5.0e-05,0.564,0.608

In [ ]:
slide_dlv3 = make_slide_df(df_dlv3, mode="medium")
slide_dlv3

,rank,run_id,run_tag,change_applied,encoder,loss,lr,test_iou@0.5,test_dice@0.5
0,1,C05,clip=1.0,Grad clip: 1.0,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.662,0.696
1,2,C02,loss:Focal+Dice,Loss: Focal+Dice,resnet18,"Focal(a=0.8, g=2.0)+Dice",1.0e-04,0.634,0.678
2,3,C03,sched:plateau,Scheduler: Plateau,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.626,0.667
3,4,C06,freeze=2ep,Freeze encoder (2 ep),resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.623,0.663
4,5,C04,amp=on,AMP = enabled,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.622,0.661
5,6,C07,ES=on,Early stopping: ON,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.621,0.661
6,7,C00,BASE,Baseline config,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",1.0e-04,0.620,0.662
7,8,C01,loss:BCE,Loss: BCE,resnet18,BCE,1.0e-04,0.609,0.648
8,9,C09,lr=2e-4,LR = 2e-4,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",2.0e-04,0.598,0.639
9,10,C08,lr=5e-5,LR = 5e-5,resnet18,"BCE+Dice(w_bce=1.0, w_dice=1.0)",5.0e-05,0.593,0.635

In [ ]:
import pandas as pd
from io import StringIO

raw = """rank	run_id	run_tag	change_applied	encoder	loss	lr	test_iou@0.5	test_dice@0.5
0	1	C06	freeze=2ep	Freeze encoder (2 ep)	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.613	0.652
1	2	C09	lr=2e-4	LR = 2e-4	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	2.0e-04	0.613	0.655
2	3	C05	clip=1.0	Grad clip: 1.0	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.610	0.653
3	4	C02	loss:Focal+Dice	Loss: Focal+Dice	resnet18	Focal(a=0.8, g=2.0)+Dice	1.0e-04	0.607	0.648
4	5	C04	amp=on	AMP = enabled	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.603	0.644
5	6	C00	BASE	Baseline config	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.601	0.642
6	7	C01	loss:BCE	Loss: BCE	resnet18	BCE	1.0e-04	0.590	0.630
7	8	C03	sched:plateau	Scheduler: Plateau	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.583	0.624
8	9	C07	ES=on	Early stopping: ON	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.580	0.621
9	10	C08	lr=5e-5	LR = 5e-5	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	5.0e-05	0.564	0.608
"""

df = pd.read_csv(StringIO(raw), sep="\t")

df_small_unet = df[["rank", "run_id", "change_applied", "test_iou@0.5", "test_dice@0.5"]].copy()

# İstersen sütun isimlerini kısalt:
df_small_unet = df_small_unet.rename(columns={
    "test_iou@0.5": "IoU",
    "test_dice@0.5": "Dice"
})

df_small_unet

   rank run_id         change_applied    IoU   Dice
0     1    C06  Freeze encoder (2 ep)  0.613  0.652
1     2    C09              LR = 2e-4  0.613  0.655
2     3    C05         Grad clip: 1.0  0.610  0.653
3     4    C02       Loss: Focal+Dice  0.607  0.648
4     5    C04          AMP = enabled  0.603  0.644
5     6    C00        Baseline config  0.601  0.642
6     7    C01              Loss: BCE  0.590  0.630
7     8    C03     Scheduler: Plateau  0.583  0.624
8     9    C07     Early stopping: ON  0.580  0.621
9    10    C08              LR = 5e-5  0.564  0.608

In [ ]:
import pandas as pd
from io import StringIO

raw2 = """rank	run_id	run_tag	change_applied	encoder	loss	lr	test_iou@0.5	test_dice@0.5
0	1	C05	clip=1.0	Grad clip: 1.0	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.662	0.696
1	2	C02	loss:Focal+Dice	Loss: Focal+Dice	resnet18	Focal(a=0.8, g=2.0)+Dice	1.0e-04	0.634	0.678
2	3	C03	sched:plateau	Scheduler: Plateau	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.626	0.667
3	4	C06	freeze=2ep	Freeze encoder (2 ep)	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.623	0.663
4	5	C04	amp=on	AMP = enabled	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.622	0.661
5	6	C07	ES=on	Early stopping: ON	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.621	0.661
6	7	C00	BASE	Baseline config	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	1.0e-04	0.620	0.662
7	8	C01	loss:BCE	Loss: BCE	resnet18	BCE	1.0e-04	0.609	0.648
8	9	C09	lr=2e-4	LR = 2e-4	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	2.0e-04	0.598	0.639
9	10	C08	lr=5e-5	LR = 5e-5	resnet18	BCE+Dice(w_bce=1.0, w_dice=1.0)	5.0e-05	0.593	0.635
"""

df2 = pd.read_csv(StringIO(raw2), sep="\t")

df2_small = df2[["rank", "run_id", "change_applied", "test_iou@0.5", "test_dice@0.5"]].copy()

# İstersen sütun isimlerini kısalt:
df2_small = df2_small.rename(columns={
    "test_iou@0.5": "IoU",
    "test_dice@0.5": "Dice"
})

df2_small

   rank run_id         change_applied    IoU   Dice
0     1    C05         Grad clip: 1.0  0.662  0.696
1     2    C02       Loss: Focal+Dice  0.634  0.678
2     3    C03     Scheduler: Plateau  0.626  0.667
3     4    C06  Freeze encoder (2 ep)  0.623  0.663
4     5    C04          AMP = enabled  0.622  0.661
5     6    C07     Early stopping: ON  0.621  0.661
6     7    C00        Baseline config  0.620  0.662
7     8    C01              Loss: BCE  0.609  0.648
8     9    C09              LR = 2e-4  0.598  0.639
9    10    C08              LR = 5e-5  0.593  0.635

# **Model Optimizasyonu**

In [9]:
import os
import zipfile

zip_path = "/content/drive/MyDrive/burned_area_models/runs_burned.zip"
extract_to = "/content/burned_area_models"

os.makedirs(extract_to, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_to)

print("Bitti.")
print("Çıkarılan klasör:", extract_to)
print("İçerik:", os.listdir(extract_to))

Bitti.
Çıkarılan klasör: /content/burned_area_models
İçerik: ['content']

In [15]:
zip_path = "/content/drive/MyDrive/burned_area_models/runs_burned_deeplabv3.zip"
extract_to = "/content/burned_area_models"

os.makedirs(extract_to, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_to)

print("Bitti.")
print("Çıkarılan klasör:", extract_to)
print("İçerik:", os.listdir(extract_to))

Bitti.
Çıkarılan klasör: /content/burned_area_models
İçerik: ['content']

In [20]:
# ============================================================
# 1) INSTALL
# ============================================================
!pip -q install segmentation-models-pytorch --upgrade

# ============================================================
# 2) IMPORTS
# ============================================================
import os
import copy
import time
import random
import shutil
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.utils.prune as prune
from torch.utils.data import Dataset, DataLoader

import segmentation_models_pytorch as smp
from tqdm import tqdm

# ============================================================
# 3) GOOGLE DRIVE
# ============================================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# 4) CONFIG
# ============================================================
SEED = 42
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ------------------------------------------------------------
# DATA
# ------------------------------------------------------------
TILES_DIR = "/content/burned_tiles"

# ------------------------------------------------------------
# MODEL SELECTION
# sadece bunu değiştir:
# "unet"
# "deeplabv3"
# ------------------------------------------------------------
MODEL_NAME = "unet"

# ------------------------------------------------------------
# CHECKPOINT ROOT
# ------------------------------------------------------------
EXTRACT_ROOT = "/content/burned_area_models/content"

MODEL_RUN_DIRS = {
    "unet": "runs_burned",
    "deeplabv3": "runs_burned_deeplabv3",
    "deeplabv3plus": "runs_burned_deeplabv3",
}

assert MODEL_NAME in MODEL_RUN_DIRS, f"Unsupported MODEL_NAME: {MODEL_NAME}"

RUNS_DIR = os.path.join(EXTRACT_ROOT, MODEL_RUN_DIRS[MODEL_NAME])

# ------------------------------------------------------------
# TRAINING EXPERIMENT SELECTION
# örnekler:
# "C00_BASE"
# "C01_loss=BCE"
# "C02_loss=Focal+Dice"
# "C09_lr=2e-4"
# ------------------------------------------------------------
EXPERIMENT_NAME = "C00_BASE"

CHECKPOINT_PATH = os.path.join(RUNS_DIR, EXPERIMENT_NAME, "best.pth")

ENCODER_NAME = "resnet18"
IN_CHANNELS = 3
CLASSES = 1

# ------------------------------------------------------------
# PRUNING
# ------------------------------------------------------------
PRUNING_TYPE = "unstructured"   # "unstructured" or "structured"
PRUNING_AMOUNT = 0.20
FINETUNE_EPOCHS = 5
FINETUNE_LR = 1e-5

# True -> sparsity-preserving fine-tune
# False -> naive fine-tune
PRESERVE_SPARSITY_DURING_FINETUNE = True

# ------------------------------------------------------------
# LOSS
# checkpoint adına göre otomatik seç
# ------------------------------------------------------------
if "loss=BCE" in EXPERIMENT_NAME:
    LOSS_NAME = "bce"
elif "loss=Focal+Dice" in EXPERIMENT_NAME:
    LOSS_NAME = "focal_dice"
else:
    LOSS_NAME = "bce_dice"

FOCAL_ALPHA = 0.8
FOCAL_GAMMA = 2.0

# ------------------------------------------------------------
# THRESHOLD SEARCH
# ------------------------------------------------------------
THRESHOLDS = np.arange(0.10, 0.91, 0.05)

# ------------------------------------------------------------
# DATALOADER
# ------------------------------------------------------------
BATCH_SIZE = 8
NUM_WORKERS = 2

# ------------------------------------------------------------
# SAVE / EXPORT
# ------------------------------------------------------------
BASE_EXPORT_DIR = "/content/drive/MyDrive/burned_area_models_final"

# Açık deney adı oluştur
PRUNE_TAG = f"prune{int(PRUNING_AMOUNT * 100)}"
FT_TAG = "sparseFT" if PRESERVE_SPARSITY_DURING_FINETUNE else "naiveFT"
FULL_EXPERIMENT_TAG = f"{MODEL_NAME}_{EXPERIMENT_NAME}_{PRUNE_TAG}_{FT_TAG}"

MODEL_EXPORT_DIR = os.path.join(BASE_EXPORT_DIR, MODEL_NAME)
BASELINE_DIR = os.path.join(MODEL_EXPORT_DIR, "baseline")
PRUNING_DIR = os.path.join(MODEL_EXPORT_DIR, "pruning")
REPORTS_DIR = os.path.join(MODEL_EXPORT_DIR, "reports")

os.makedirs(BASELINE_DIR, exist_ok=True)
os.makedirs(PRUNING_DIR, exist_ok=True)
os.makedirs(REPORTS_DIR, exist_ok=True)

BASELINE_COPY_PATH = os.path.join(BASELINE_DIR, f"{MODEL_NAME}_{EXPERIMENT_NAME}_best.pth")
SAVE_PRUNED_PATH = os.path.join(PRUNING_DIR, f"{FULL_EXPERIMENT_TAG}.pth")
SAVE_METRICS_CSV = os.path.join(REPORTS_DIR, f"{FULL_EXPERIMENT_TAG}_metrics.csv")
SAVE_SUMMARY_TXT = os.path.join(REPORTS_DIR, f"{FULL_EXPERIMENT_TAG}_summary.txt")

print("MODEL_NAME        :", MODEL_NAME)
print("RUNS_DIR          :", RUNS_DIR)
print("EXPERIMENT_NAME   :", EXPERIMENT_NAME)
print("CHECKPOINT_PATH   :", CHECKPOINT_PATH)
print("BASELINE_COPY     :", BASELINE_COPY_PATH)
print("SAVE_PRUNED_PATH  :", SAVE_PRUNED_PATH)
print("SAVE_METRICS_CSV  :", SAVE_METRICS_CSV)
print("SAVE_SUMMARY_TXT  :", SAVE_SUMMARY_TXT)
print("LOSS_NAME         :", LOSS_NAME)

# ============================================================
# 5) SEED
# ============================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(SEED)

# ============================================================
# 6) DATASET
# ============================================================
class BurnedPatchDataset(Dataset):
    def __init__(self, tiles_dir, ids, normalize=True):
        self.tiles_dir = tiles_dir
        self.ids = ids
        self.normalize = normalize

    def __len__(self):
        return len(self.ids)

    def __getitem__(self, idx):
        id_ = self.ids[idx]

        x = np.load(os.path.join(self.tiles_dir, "x", f"{id_}.npy"))
        y = np.load(os.path.join(self.tiles_dir, "y", f"{id_}.npy"))

        if x.ndim == 3 and x.shape[-1] == 3:
            x = np.transpose(x, (2, 0, 1))

        x = x.astype(np.float32)
        if self.normalize:
            x = x / 255.0

        y = (y > 0).astype(np.int64)

        return torch.from_numpy(x), torch.from_numpy(y)

# ============================================================
# 7) IDS SPLIT
# ============================================================
x_dir = os.path.join(TILES_DIR, "x")
y_dir = os.path.join(TILES_DIR, "y")

assert os.path.isdir(x_dir), f"x directory not found: {x_dir}"
assert os.path.isdir(y_dir), f"y directory not found: {y_dir}"

ids = sorted([os.path.splitext(f)[0] for f in os.listdir(x_dir) if f.endswith(".npy")])
ids = [id_ for id_ in ids if os.path.exists(os.path.join(y_dir, f"{id_}.npy"))]

random.seed(SEED)
random.shuffle(ids)

n = len(ids)
train_ids = ids[:int(0.7 * n)]
val_ids   = ids[int(0.7 * n):int(0.85 * n)]
test_ids  = ids[int(0.85 * n):]

print("Total :", len(ids))
print("Train :", len(train_ids))
print("Val   :", len(val_ids))
print("Test  :", len(test_ids))

# ============================================================
# 8) DATALOADERS
# ============================================================
train_ds = BurnedPatchDataset(TILES_DIR, train_ids)
val_ds   = BurnedPatchDataset(TILES_DIR, val_ids)
test_ds  = BurnedPatchDataset(TILES_DIR, test_ids)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=NUM_WORKERS, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)

print("Train size:", len(train_ds))
print("Val size  :", len(val_ds))
print("Test size :", len(test_ds))

# ============================================================
# 9) MODEL BUILDER
# ============================================================
def build_model():
    if MODEL_NAME == "unet":
        return smp.Unet(
            encoder_name=ENCODER_NAME,
            encoder_weights="imagenet",
            in_channels=IN_CHANNELS,
            classes=CLASSES,
        )

    elif MODEL_NAME == "deeplabv3":
        return smp.DeepLabV3(
            encoder_name=ENCODER_NAME,
            encoder_weights="imagenet",
            in_channels=IN_CHANNELS,
            classes=CLASSES,
            activation=None,
        )

    elif MODEL_NAME == "deeplabv3plus":
        return smp.DeepLabV3Plus(
            encoder_name=ENCODER_NAME,
            encoder_weights="imagenet",
            in_channels=IN_CHANNELS,
            classes=CLASSES,
            activation=None,
        )

    else:
        raise ValueError(f"Unsupported MODEL_NAME: {MODEL_NAME}")

# ============================================================
# 10) CHECKPOINT LOADER
# ============================================================
def load_checkpoint(model, checkpoint_path, device):
    assert os.path.exists(checkpoint_path), f"Checkpoint not found: {checkpoint_path}"

    checkpoint = torch.load(checkpoint_path, map_location=device)

    if isinstance(checkpoint, dict):
        if "model" in checkpoint:
            state_dict = checkpoint["model"]
        elif "state_dict" in checkpoint:
            state_dict = checkpoint["state_dict"]
        elif "model_state_dict" in checkpoint:
            state_dict = checkpoint["model_state_dict"]
        else:
            state_dict = checkpoint
    else:
        state_dict = checkpoint

    cleaned_state_dict = {}
    for k, v in state_dict.items():
        if k.startswith("module."):
            cleaned_state_dict[k[len("module."):]] = v
        else:
            cleaned_state_dict[k] = v

    model.load_state_dict(cleaned_state_dict, strict=True)
    return model

# baseline checkpoint'i düzenli klasöre kopyala
if not os.path.exists(BASELINE_COPY_PATH):
    shutil.copy2(CHECKPOINT_PATH, BASELINE_COPY_PATH)
    print("Baseline checkpoint copied to:", BASELINE_COPY_PATH)
else:
    print("Baseline checkpoint already exists at:", BASELINE_COPY_PATH)

model = build_model()
model = load_checkpoint(model, CHECKPOINT_PATH, DEVICE)
model = model.to(DEVICE)

print("Checkpoint loaded successfully.")

# ============================================================
# 11) LOSS
# ============================================================
def make_loss(loss_name="bce_dice"):
    if loss_name == "bce":
        bce = torch.nn.BCEWithLogitsLoss()
        return lambda logits, y: bce(logits, y)

    elif loss_name == "bce_dice":
        bce = torch.nn.BCEWithLogitsLoss()
        dice = smp.losses.DiceLoss(mode="binary")
        return lambda logits, y: bce(logits, y) + dice(logits, y)

    elif loss_name == "focal_dice":
        focal = smp.losses.FocalLoss(mode="binary", alpha=FOCAL_ALPHA, gamma=FOCAL_GAMMA)
        dice  = smp.losses.DiceLoss(mode="binary")
        return lambda logits, y: focal(logits, y) + dice(logits, y)

    else:
        raise ValueError(f"Unknown LOSS_NAME: {loss_name}")

criterion = make_loss(LOSS_NAME)

# ============================================================
# 12) METRICS
# ============================================================
@torch.no_grad()
def compute_binary_metrics_from_logits(logits, y, threshold=0.5, eps=1e-7):
    probs = torch.sigmoid(logits)
    pred = (probs > threshold).float()

    pred = pred.view(-1)
    y = y.view(-1)

    tp = (pred * y).sum()
    fp = (pred * (1 - y)).sum()
    fn = ((1 - pred) * y).sum()
    tn = ((1 - pred) * (1 - y)).sum()

    precision = tp / (tp + fp + eps)
    recall    = tp / (tp + fn + eps)
    dice      = (2 * tp) / (2 * tp + fp + fn + eps)
    iou       = tp / (tp + fp + fn + eps)
    accuracy  = (tp + tn) / (tp + tn + fp + fn + eps)

    return {
        "accuracy": accuracy.item(),
        "precision": precision.item(),
        "recall": recall.item(),
        "dice": dice.item(),
        "iou": iou.item()
    }

# ============================================================
# 13) PRUNING HELPERS
# ============================================================
def apply_unstructured_pruning(model, amount=0.2, verbose=True):
    pruned_layers = []
    for name, module in model.named_modules():
        if isinstance(module, (nn.Conv2d, nn.Linear)):
            prune.l1_unstructured(module, name="weight", amount=amount)
            pruned_layers.append(name)

    if verbose:
        print(f"[Unstructured Pruning] amount={amount}")
        print(f"Pruned layer count: {len(pruned_layers)}")
    return model

def apply_structured_pruning(model, amount=0.1, verbose=True):
    pruned_layers = []
    for name, module in model.named_modules():
        if isinstance(module, nn.Conv2d) and module.out_channels > 8:
            prune.ln_structured(module, name="weight", amount=amount, n=2, dim=0)
            pruned_layers.append(name)

    if verbose:
        print(f"[Structured Pruning] amount={amount}")
        print(f"Pruned layer count: {len(pruned_layers)}")
    return model

def make_pruning_permanent(model):
    for module in model.modules():
        if isinstance(module, (nn.Conv2d, nn.Linear)) and hasattr(module, "weight_orig"):
            prune.remove(module, "weight")
    return model

def collect_pruning_masks(model):
    masks = {}
    for name, module in model.named_modules():
        if hasattr(module, "weight_mask"):
            masks[name] = module.weight_mask.detach().clone()
    return masks

def reapply_pruning_masks(model, masks):
    for name, module in model.named_modules():
        if name in masks:
            module.weight.data.mul_(masks[name].to(module.weight.device))

# ============================================================
# 14) TRAIN / EVAL
# ============================================================
def train_one_epoch(model, loader, optimizer, criterion, device, scaler=None, pruning_masks=None):
    model.train()
    running_loss = 0.0

    for x, y in tqdm(loader, desc="Train", leave=False):
        x = x.to(device, non_blocking=True)
        y = y.unsqueeze(1).float().to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        if scaler is not None and device == "cuda":
            with torch.autocast(device_type="cuda", dtype=torch.float16):
                logits = model(x)
                loss = criterion(logits, y)

            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()

        if pruning_masks is not None:
            reapply_pruning_masks(model, pruning_masks)

        running_loss += loss.item()

    return running_loss / len(loader)

@torch.no_grad()
def evaluate_model(model, loader, criterion, device, threshold=0.5, split_name="VAL"):
    model.eval()

    total_loss = 0.0
    metric_sums = {
        "accuracy": 0.0,
        "precision": 0.0,
        "recall": 0.0,
        "dice": 0.0,
        "iou": 0.0
    }

    for x, y in tqdm(loader, desc=f"Eval-{split_name}", leave=False):
        x = x.to(device, non_blocking=True)
        y = y.unsqueeze(1).float().to(device, non_blocking=True)

        logits = model(x)
        loss = criterion(logits, y)
        total_loss += loss.item()

        metrics = compute_binary_metrics_from_logits(logits, y, threshold=threshold)
        for k in metric_sums:
            metric_sums[k] += metrics[k]

    n = len(loader)
    results = {"loss": total_loss / n}
    for k in metric_sums:
        results[k] = metric_sums[k] / n

    return results

@torch.no_grad()
def find_best_threshold(model, loader, device, thresholds=THRESHOLDS):
    model.eval()
    best_threshold = 0.5
    best_dice = -1.0

    for t in thresholds:
        dice_scores = []

        for x, y in loader:
            x = x.to(device, non_blocking=True)
            y = y.unsqueeze(1).float().to(device, non_blocking=True)

            logits = model(x)
            metrics = compute_binary_metrics_from_logits(logits, y, threshold=t)
            dice_scores.append(metrics["dice"])

        avg_dice = float(np.mean(dice_scores))
        if avg_dice > best_dice:
            best_dice = avg_dice
            best_threshold = float(t)

    return best_threshold, best_dice

def finetune_model(model, train_loader, val_loader, criterion, device, epochs=5, lr=1e-5, threshold=0.5, pruning_masks=None):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    scaler = torch.amp.GradScaler("cuda") if device == "cuda" else None

    best_model = copy.deepcopy(model.state_dict())
    best_dice = -1.0
    history = []

    for epoch in range(epochs):
        train_loss = train_one_epoch(
            model=model,
            loader=train_loader,
            optimizer=optimizer,
            criterion=criterion,
            device=device,
            scaler=scaler,
            pruning_masks=pruning_masks
        )

        val_results = evaluate_model(model, val_loader, criterion, device, threshold=threshold, split_name="VAL")

        history.append({
            "epoch": epoch + 1,
            "train_loss": train_loss,
            **val_results
        })

        print(
            f"Epoch [{epoch+1}/{epochs}] | "
            f"train_loss={train_loss:.4f} | "
            f"val_loss={val_results['loss']:.4f} | "
            f"val_dice={val_results['dice']:.4f} | "
            f"val_iou={val_results['iou']:.4f}"
        )

        if val_results["dice"] > best_dice:
            best_dice = val_results["dice"]
            best_model = copy.deepcopy(model.state_dict())

    model.load_state_dict(best_model)

    if pruning_masks is not None:
        reapply_pruning_masks(model, pruning_masks)

    return model, history

# ============================================================
# 15) BENCHMARK (PRUNING-AWARE)
# ============================================================
def get_model_size_mb(model, path="/content/temp_model.pth"):
    torch.save(model.state_dict(), path)
    size_mb = os.path.getsize(path) / (1024 * 1024)
    os.remove(path)
    return size_mb

def count_effective_total_and_nonzero_params(model):
    total = 0
    nonzero = 0

    for module in model.modules():
        if isinstance(module, (nn.Conv2d, nn.Linear)):
            w = module.weight.detach()
            total += w.numel()
            nonzero += (w != 0).sum().item()

            if module.bias is not None:
                b = module.bias.detach()
                total += b.numel()
                nonzero += (b != 0).sum().item()

    return total, nonzero

def get_effective_sparsity(model):
    total, nonzero = count_effective_total_and_nonzero_params(model)
    return 1.0 - (nonzero / total)

def estimate_effective_sparse_size_mb(model):
    _, nonzero = count_effective_total_and_nonzero_params(model)
    return (nonzero * 4) / (1024 * 1024)

def measure_latency(model, input_tensor, device="cuda", warmup=20, runs=100):
    model.eval().to(device)
    input_tensor = input_tensor.to(device)

    with torch.no_grad():
        for _ in range(warmup):
            _ = model(input_tensor)

    if "cuda" in device:
        torch.cuda.synchronize()

    start = time.time()

    with torch.no_grad():
        for _ in range(runs):
            _ = model(input_tensor)

    if "cuda" in device:
        torch.cuda.synchronize()

    end = time.time()
    return (end - start) / runs * 1000.0

def benchmark_model(model, loader, criterion, device, sample_input, threshold=0.5, split_name="VAL"):
    eval_results = evaluate_model(
        model, loader, criterion, device,
        threshold=threshold, split_name=split_name
    )

    runtime_size_mb = get_model_size_mb(model)
    total_params, nonzero_params = count_effective_total_and_nonzero_params(model)
    sparsity = get_effective_sparsity(model)
    effective_sparse_size_mb = estimate_effective_sparse_size_mb(model)
    latency_ms = measure_latency(model, sample_input, device=device)

    return {
        "runtime_size_mb": runtime_size_mb,
        "effective_sparse_size_mb": effective_sparse_size_mb,
        "total_params": total_params,
        "nonzero_params": nonzero_params,
        "sparsity": sparsity,
        "latency_ms": latency_ms,
        **eval_results
    }

# ============================================================
# 16) FULL EXPERIMENT
# ============================================================
def run_pruning_experiment(
    model,
    train_loader,
    val_loader,
    test_loader,
    device,
    sample_input,
    pruning_type="unstructured",
    pruning_amount=0.2,
    finetune_epochs=5,
    finetune_lr=1e-5,
    preserve_sparsity_during_finetune=True,
):
    print("\n================ BASELINE / VAL ================\n")
    baseline_thr, baseline_best_dice = find_best_threshold(model, val_loader, device)
    baseline_val = benchmark_model(model, val_loader, criterion, device, sample_input, threshold=baseline_thr, split_name="VAL")
    baseline_val["best_threshold"] = baseline_thr
    baseline_val["best_val_dice_threshold_search"] = baseline_best_dice
    for k, v in baseline_val.items():
        print(f"{k}: {v}")

    print("\n================ BASELINE / TEST ================\n")
    baseline_test = benchmark_model(model, test_loader, criterion, device, sample_input, threshold=baseline_thr, split_name="TEST")
    baseline_test["used_threshold"] = baseline_thr
    for k, v in baseline_test.items():
        print(f"{k}: {v}")

    pruned_model = copy.deepcopy(model)

    print("\n================ APPLY PRUNING ================\n")
    if pruning_type == "unstructured":
        pruned_model = apply_unstructured_pruning(pruned_model, amount=pruning_amount)
    elif pruning_type == "structured":
        pruned_model = apply_structured_pruning(pruned_model, amount=pruning_amount)
    else:
        raise ValueError("pruning_type must be 'unstructured' or 'structured'")

    pruning_masks = collect_pruning_masks(pruned_model)

    print("\n================ AFTER PRUNING / BEFORE FINETUNE / VAL ================\n")
    pruned_thr, pruned_best_dice = find_best_threshold(pruned_model, val_loader, device)
    pruned_val_before = benchmark_model(pruned_model, val_loader, criterion, device, sample_input, threshold=pruned_thr, split_name="VAL")
    pruned_val_before["best_threshold"] = pruned_thr
    pruned_val_before["best_val_dice_threshold_search"] = pruned_best_dice
    for k, v in pruned_val_before.items():
        print(f"{k}: {v}")

    print("\n================ FINETUNING ================\n")
    active_masks = pruning_masks if preserve_sparsity_during_finetune else None

    pruned_model, history = finetune_model(
        model=pruned_model,
        train_loader=train_loader,
        val_loader=val_loader,
        criterion=criterion,
        device=device,
        epochs=finetune_epochs,
        lr=finetune_lr,
        threshold=pruned_thr,
        pruning_masks=active_masks
    )

    print("\n================ AFTER FINETUNE / VAL ================\n")
    final_thr, final_best_dice = find_best_threshold(pruned_model, val_loader, device)
    final_val = benchmark_model(pruned_model, val_loader, criterion, device, sample_input, threshold=final_thr, split_name="VAL")
    final_val["best_threshold"] = final_thr
    final_val["best_val_dice_threshold_search"] = final_best_dice
    for k, v in final_val.items():
        print(f"{k}: {v}")

    print("\n================ AFTER FINETUNE / TEST ================\n")
    final_test = benchmark_model(pruned_model, test_loader, criterion, device, sample_input, threshold=final_thr, split_name="TEST")
    final_test["used_threshold"] = final_thr
    for k, v in final_test.items():
        print(f"{k}: {v}")

    pruned_model = make_pruning_permanent(pruned_model)

    return {
        "baseline_val": baseline_val,
        "baseline_test": baseline_test,
        "pruned_val_before_ft": pruned_val_before,
        "final_val": final_val,
        "final_test": final_test,
        "history": history,
        "model": pruned_model
    }

# ============================================================
# 17) RUN
# ============================================================
x0, _ = train_ds[0]
C, H, W = x0.shape
sample_input = torch.randn(1, C, H, W)

results = run_pruning_experiment(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    test_loader=test_loader,
    device=DEVICE,
    sample_input=sample_input,
    pruning_type=PRUNING_TYPE,
    pruning_amount=PRUNING_AMOUNT,
    finetune_epochs=FINETUNE_EPOCHS,
    finetune_lr=FINETUNE_LR,
    preserve_sparsity_during_finetune=PRESERVE_SPARSITY_DURING_FINETUNE,
)

# ============================================================
# 18) SAVE PRUNED MODEL
# ============================================================
save_obj = {
    "model_name": MODEL_NAME,
    "experiment_name": EXPERIMENT_NAME,
    "full_experiment_tag": FULL_EXPERIMENT_TAG,
    "model": results["model"].state_dict(),
    "pruning_type": PRUNING_TYPE,
    "pruning_amount": PRUNING_AMOUNT,
    "loss_name": LOSS_NAME,
    "preserve_sparsity_during_finetune": PRESERVE_SPARSITY_DURING_FINETUNE,
    "history": results["history"],
    "results": {
        "baseline_val": results["baseline_val"],
        "baseline_test": results["baseline_test"],
        "pruned_val_before_ft": results["pruned_val_before_ft"],
        "final_val": results["final_val"],
        "final_test": results["final_test"],
    }
}

torch.save(save_obj, SAVE_PRUNED_PATH)
print(f"\nPruned model saved to: {SAVE_PRUNED_PATH}")

# ============================================================
# 19) SAVE REPORTS
# ============================================================
rows = []
for stage_key in ["baseline_val", "baseline_test", "pruned_val_before_ft", "final_val", "final_test"]:
    d = results[stage_key].copy()
    d["stage"] = stage_key
    d["model_name"] = MODEL_NAME
    d["experiment_name"] = EXPERIMENT_NAME
    d["pruning_type"] = PRUNING_TYPE
    d["pruning_amount"] = PRUNING_AMOUNT
    d["finetune_type"] = FT_TAG
    rows.append(d)

df = pd.DataFrame(rows)
df.to_csv(SAVE_METRICS_CSV, index=False)
print(f"Metrics CSV saved to: {SAVE_METRICS_CSV}")

summary_lines = [
    f"Full Experiment Tag: {FULL_EXPERIMENT_TAG}",
    f"Model Name: {MODEL_NAME}",
    f"Experiment Name: {EXPERIMENT_NAME}",
    f"Checkpoint Path: {CHECKPOINT_PATH}",
    f"Pruning Type: {PRUNING_TYPE}",
    f"Pruning Amount: {PRUNING_AMOUNT}",
    f"Fine-tune Type: {FT_TAG}",
    f"Loss Name: {LOSS_NAME}",
    "",
    "==== FINAL TEST RESULTS ====",
]

for k, v in results["final_test"].items():
    summary_lines.append(f"{k}: {v}")

with open(SAVE_SUMMARY_TXT, "w", encoding="utf-8") as f:
    f.write("\n".join(summary_lines))

print(f"Summary TXT saved to: {SAVE_SUMMARY_TXT}")

# ============================================================
# 20) SUMMARY
# ============================================================
def print_summary_block(name, d):
    print("\n" + "="*70)
    print(name)
    print("="*70)
    for k, v in d.items():
        print(f"{k}: {v}")

print_summary_block("BASELINE VAL", results["baseline_val"])
print_summary_block("BASELINE TEST", results["baseline_test"])
print_summary_block("PRUNED BEFORE FT VAL", results["pruned_val_before_ft"])
print_summary_block("FINAL VAL", results["final_val"])
print_summary_block("FINAL TEST", results["final_test"])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
MODEL_NAME        : unet
RUNS_DIR          : /content/burned_area_models/content/runs_burned
EXPERIMENT_NAME   : C00_BASE
CHECKPOINT_PATH   : /content/burned_area_models/content/runs_burned/C00_BASE/best.pth
BASELINE_COPY     : /content/drive/MyDrive/burned_area_models_final/unet/baseline/unet_C00_BASE_best.pth
SAVE_PRUNED_PATH  : /content/drive/MyDrive/burned_area_models_final/unet/pruning/unet_C00_BASE_prune20_sparseFT.pth
SAVE_METRICS_CSV  : /content/drive/MyDrive/burned_area_models_final/unet/reports/unet_C00_BASE_prune20_sparseFT_metrics.csv
SAVE_SUMMARY_TXT  : /content/drive/MyDrive/burned_area_models_final/unet/reports/unet_C00_BASE_prune20_sparseFT_summary.txt
LOSS_NAME         : bce_dice
Total : 2874
Train : 2011
Val   : 431
Test  : 432
Train size: 2011
Val size  : 431
Test size : 432
Baseline checkpoint copied to: /content/drive/MyDrive/burned_area_models_final/unet/baseline/unet_C00_BASE_best.pth
Checkpoint loaded successfully.

================ BASELINE / VAL ================

runtime_size_mb: 54.764655113220215
effective_sparse_size_mb: 54.613590240478516
total_params: 14316625
nonzero_params: 14316625
sparsity: 0.0
latency_ms: 4.4361186027526855
loss: 0.3966823273372871
accuracy: 0.9270641130429728
precision: 0.896759698788325
recall: 0.9402901188090995
dice: 0.9140103669078262
iou: 0.849113815360599
best_threshold: 0.7500000000000002
best_val_dice_threshold_search: 0.9140103669078262

================ BASELINE / TEST ================

runtime_size_mb: 54.764655113220215
effective_sparse_size_mb: 54.613590240478516
total_params: 14316625
nonzero_params: 14316625
sparsity: 0.0
latency_ms: 4.5829033851623535
loss: 0.38062928879150637
accuracy: 0.934316529168023
precision: 0.891299135155148
recall: 0.9500413305229611
dice: 0.9140813615587022
iou: 0.8507862157291837
used_threshold: 0.7500000000000002

================ APPLY PRUNING ================

[Unstructured Pruning] amount=0.2
Pruned layer count: 31

================ AFTER PRUNING / BEFORE FINETUNE / VAL ================

runtime_size_mb: 109.38846397399902
effective_sparse_size_mb: 43.69086837768555
total_params: 14316625
nonzero_params: 11453299
sparsity: 0.20000006984886454
latency_ms: 6.008024215698242
loss: 0.3732313189517569
accuracy: 0.930460798519629
precision: 0.9050478129475205
recall: 0.9380292163954841
dice: 0.9175930199799714
iou: 0.8547419740094079
best_threshold: 0.7500000000000002
best_val_dice_threshold_search: 0.9175930199799714

================ FINETUNING ================

Epoch [1/5] | train_loss=0.3267 | val_loss=0.2576 | val_dice=0.9268 | val_iou=0.8693

Epoch [2/5] | train_loss=0.2452 | val_loss=0.2494 | val_dice=0.9321 | val_iou=0.8781

Epoch [3/5] | train_loss=0.2050 | val_loss=0.2371 | val_dice=0.9347 | val_iou=0.8826

Epoch [4/5] | train_loss=0.1735 | val_loss=0.2444 | val_dice=0.9357 | val_iou=0.8843

Epoch [5/5] | train_loss=0.1447 | val_loss=0.2398 | val_dice=0.9372 | val_iou=0.8868

================ AFTER FINETUNE / VAL ================

runtime_size_mb: 109.38846397399902
effective_sparse_size_mb: 43.69086837768555
total_params: 14316625
nonzero_params: 11453299
sparsity: 0.20000006984886454
latency_ms: 5.738961696624756
loss: 0.23978964266953645
accuracy: 0.9473484026061164
precision: 0.9386470350954268
recall: 0.9419778055614896
dice: 0.9381486729339317
iou: 0.8883343272738986
best_threshold: 0.6500000000000001
best_val_dice_threshold_search: 0.9381486729339317

================ AFTER FINETUNE / TEST ================

runtime_size_mb: 109.38846397399902
effective_sparse_size_mb: 43.69086837768555
total_params: 14316625
nonzero_params: 11453299
sparsity: 0.20000006984886454
latency_ms: 5.812361240386963
loss: 0.24860480275970917
accuracy: 0.9480394080833152
precision: 0.9289803957497632
recall: 0.9445183630342837
dice: 0.9339693563955801
iou: 0.8825208290859505
used_threshold: 0.6500000000000001

Pruned model saved to: /content/drive/MyDrive/burned_area_models_final/unet/pruning/unet_C00_BASE_prune20_sparseFT.pth
Metrics CSV saved to: /content/drive/MyDrive/burned_area_models_final/unet/reports/unet_C00_BASE_prune20_sparseFT_metrics.csv
Summary TXT saved to: /content/drive/MyDrive/burned_area_models_final/unet/reports/unet_C00_BASE_prune20_sparseFT_summary.txt

======================================================================
BASELINE VAL
======================================================================
runtime_size_mb: 54.764655113220215
effective_sparse_size_mb: 54.613590240478516
total_params: 14316625
nonzero_params: 14316625
sparsity: 0.0
latency_ms: 4.4361186027526855
loss: 0.3966823273372871
accuracy: 0.9270641130429728
precision: 0.896759698788325
recall: 0.9402901188090995
dice: 0.9140103669078262
iou: 0.849113815360599
best_threshold: 0.7500000000000002
best_val_dice_threshold_search: 0.9140103669078262

======================================================================
BASELINE TEST
======================================================================
runtime_size_mb: 54.764655113220215
effective_sparse_size_mb: 54.613590240478516
total_params: 14316625
nonzero_params: 14316625
sparsity: 0.0
latency_ms: 4.5829033851623535
loss: 0.38062928879150637
accuracy: 0.934316529168023
precision: 0.891299135155148
recall: 0.9500413305229611
dice: 0.9140813615587022
iou: 0.8507862157291837
used_threshold: 0.7500000000000002

======================================================================
PRUNED BEFORE FT VAL
======================================================================
runtime_size_mb: 109.38846397399902
effective_sparse_size_mb: 43.69086837768555
total_params: 14316625
nonzero_params: 11453299
sparsity: 0.20000006984886454
latency_ms: 6.008024215698242
loss: 0.3732313189517569
accuracy: 0.930460798519629
precision: 0.9050478129475205
recall: 0.9380292163954841
dice: 0.9175930199799714
iou: 0.8547419740094079
best_threshold: 0.7500000000000002
best_val_dice_threshold_search: 0.9175930199799714

======================================================================
FINAL VAL
======================================================================
runtime_size_mb: 109.38846397399902
effective_sparse_size_mb: 43.69086837768555
total_params: 14316625
nonzero_params: 11453299
sparsity: 0.20000006984886454
latency_ms: 5.738961696624756
loss: 0.23978964266953645
accuracy: 0.9473484026061164
precision: 0.9386470350954268
recall: 0.9419778055614896
dice: 0.9381486729339317
iou: 0.8883343272738986
best_threshold: 0.6500000000000001
best_val_dice_threshold_search: 0.9381486729339317

======================================================================
FINAL TEST
======================================================================
runtime_size_mb: 109.38846397399902
effective_sparse_size_mb: 43.69086837768555
total_params: 14316625
nonzero_params: 11453299
sparsity: 0.20000006984886454
latency_ms: 5.812361240386963
loss: 0.24860480275970917
accuracy: 0.9480394080833152
precision: 0.9289803957497632
recall: 0.9445183630342837
dice: 0.9339693563955801
iou: 0.8825208290859505
used_threshold: 0.6500000000000001